### ISSUE TITLE
Empty catalog after upgrading to 5.2.1

### ISSUE THREAD

**Issue by alex-hempel** [kontena/lens#3826]
After upgrading to 5.2.1, Lens presents an empty catalog, despite the kube config being in the list of synced files. Previously pinned clusters are greyed out. After rolling back to a previous version, it works fine again.

**To Reproduce**
1. Upgrade to 5.2.1
2. Go to catalog

**Expected behavior**
Catalog shows all clusters in present config, as it did before the upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/6581307/133716809-06e86be9-047d-44e3-8ce7-68798c360e87.png)
![image](https://user-images.githubusercontent.com/6581307/133716835-3a99fa62-4ad9-45a4-8f4b-bc69b50ecf54.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.1
- OS: Windows 10 (observed on two different machines)

**Logs:**
No log output to speak of.

**Comment by eindrawan** [comment]
having similar issue, try to add new cluster or/and login have no effect
make a high priority please

@alex-hempel how did you roll back?

**Comment by alex-hempel** [comment]
@eindrawan You can just run an older installer, but if you want to make sure, uninstall the old version first.

Download link for 5.2.0 Windows installer is https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.2.0-latest.20210908.1.exe

**Comment by chjtwork** [comment]
Same issue.
If the Kube config uses 'user: exec' , the cluster disappear from the Clusters list. 
```
users:
- name: test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - test-eks
      command: aws
```
 
But if the Kube config uses  'user: token', has no problem
