### ISSUE TITLE
Cannot open shell on pod on Linux (chdir failed)

### ISSUE THREAD

**Issue by Roming22** [kontena/lens#3834]
**Describe the bug**
After deploying a k3d cluster on a remote Raspberry Pi, the Linux Lens application is not able to open a shell on pods, failing with `chdir(2) failed.: No such file or directory`. The Mac Intel Lens application has not such problem.

**To Reproduce**
1. Deploy a k3d cluster on a remote server
2. Connect Lens to the cluster
3. Select the `kube-system` namespace
4. Try to open a shell on the `metrics-server` pod
5. See error

**Expected behavior**
A shell should be opened on the pod's container.

**Screenshots**
N/A

**Environment (please complete the following information):**
- Lens Version: Lens-5.2.2-latest.20210918.1.amd64.snap
- OS: Linux (fedora 34)
- Installation method (e.g. snap or AppImage in Linux): snap

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
chdir(2) failed.: No such file or directory
Terminal will auto-close in 15 seconds ...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://<REDACTED>
  name: k3d-node0-pi
contexts:
- context:
    cluster: k3d-node0-pi
    user: admin@k3d-node0-pi
  name: k3d-node0-pi
current-context: k3d-node0-pi
kind: Config
preferences: {}
users:
- name: admin@k3d-node0-pi
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>

```

**Additional context**
