### ISSUE TITLE
Last update 5.2.3-latest.20210921.1 broke AWS EKS kubernetes connectivity

### ISSUE THREAD

**Issue by Startouf** [kontena/lens#3856]
**Describe the bug**
After upgrading to Lens: 5.2.3-latest.20210921.1 (don't remember which was the previous version)
- An error message appeared the first time I reloaded Lens mentioning plugins that no longer worked (I did not really pay attention to this message to remember it exactly)
- I lost all my configured clusters : they are greyed out on the right, unclickable, no right click option
<img width="1494" alt="Screenshot 2021-09-21 at 15 21 50" src="https://user-images.githubusercontent.com/7388889/134178300-cde9adea-7cdb-4fcd-a675-9e2faa69c586.png">
<img width="213" alt="Screenshot 2021-09-21 at 15 22 21" src="https://user-images.githubusercontent.com/7388889/134178377-14fcd481-ed6f-43b7-87b6-46bbf614cf47.png">

- The sync kubernetes config button does nothing
- I am no longer able to configure & connect to my k8s clusters using aws iam authenticator

**To Reproduce**
My kubeconfig was similar to this one before upgrading

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXX
    server: https://XXXX.gr7.eu-central-1.eks.amazonaws.com
  name: eks_ENV
contexts:
- context:
    cluster: eks_ENV
    user: eks_ENV
  name: eks_ENV
current-context: eks_ENV
kind: Config
preferences: {}
users:
- name: eks_ENV
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - XXX (ENV)
      command: aws-iam-authenticator
      env: null
```

After upgrading to aforementioned lens version, All config are greyed out and unmanageable

When I try to add again the same config, I have an error 
> ExecValidationNotFoundError: User Exec command "aws-iam-authenticator" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig

After adding the absolute path (`/usr/local/bin/aws-iam-authenticator`), I can submit the kubeconfig but it is stuck on loading when I try to connect to a cluster

**Expected behavior**
Preserve existing kubeconfigs

**Screenshots**
Added inline above

**Environment (please complete the following information):**
- Lens Version: 5.2.3-latest.20210921.1
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): clicked auto-update update button

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
How do you do that on macOS ?
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXX
    server: https://XXXX.gr7.eu-central-1.eks.amazonaws.com
  name: eks_ENV
contexts:
- context:
    cluster: eks_ENV
    user: eks_ENV
  name: eks_ENV
current-context: eks_ENV
kind: Config
preferences: {}
users:
- name: eks_ENV
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - XXX (ENV)
      command: aws-iam-authenticator
      env: null
```

**Additional context**
N/A
