### ISSUE TITLE
Warn when add clusters text input doesn't include any contexts

### ISSUE THREAD

**Issue by zozo6015** [kontena/lens#3865]
**Describe the bug**
Cannot add cluster to lens

**To Reproduce**
click on Add cluster paste the config in the text screen and Add cluster button is not active
 Click on the + select the config from the files and nothing happens.

**Expected behavior**
the newly added cluster to show up in the cluster lists

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.3-latest.20210921.1
- OS: Macos BigSur 11.6 (20G165)
- Installation method (e.g. snap or AppImage in Linux):
- AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Nothing in the logs
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
clusters:
  - name: rcc-dev
    cluster:
      server: https://1ejbwc.c1.bhs5.k8s.ovh.net
      certificate-authority-data: >-
        
      insecure-skip-tls-verify: false
users:
  - name: kubernetes-admin-rcc-dev
    user:
      client-certificate-data: >-
        
      client-key-data: >-
        
contexts: []
preferences: {}
current-context: kubernetes-admin@rcc-dev
```

**Additional context**
<img width="897" alt="Screenshot 2021-09-22 at 09 00 10" src="https://user-images.githubusercontent.com/2540250/134291229-001e3375-c0c1-4759-93c5-6ba148299d97.png">
