### ISSUE TITLE
Cannot see any cluster details

### ISSUE THREAD

**Issue by makowskimateusz** [kontena/lens#3891]
I facing the issue that when I'm connected to the cluster I'm not able to see anything. 

What I'm I doing wrong? 
![Screenshot 2021-09-24 at 13 04 23](https://user-images.githubusercontent.com/5725006/134664636-aee4fc0f-6c80-468d-a871-b501e52418a9.png)
![Screenshot 2021-09-24 at 13 04 30](https://user-images.githubusercontent.com/5725006/134664640-53e6eb22-bc19-4675-b27a-e9bcbc20ee1c.png)
![Screenshot 2021-09-24 at 13 04 35](https://user-images.githubusercontent.com/5725006/134664641-6a4035cf-c8a9-44cb-b99a-3881628bdcfc.png)

**Comment by Startouf** [comment]
I'm having the same problem on some of my clusters

Lens: 5.2.4-latest.20210923.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.

**Comment by Startouf** [comment]
I can connect to my active context of my .kube/config but I'm having troubles using a different context in my `.kube/config`  or a different file `.kube/config-production`. 

When I copy paste the relevant part of my kubeconfig into a new cluster config "add from kubeconfig" I can successfully connect to this cluster however.

**Comment by robbesettlemint** [comment]
Also facing this issue with one particular cluster. Strange thing is, all my other clusters are perfectly fine (clusters on eks and gks). The cluster that's not working is one on EKS, but other EKS networks work fine. I can't find anything that would differentiate this cluster from the other ones, except that I used this cluster the most.

**Comment by TemplateXu** [comment]
same problem

**Comment by Nokel81** [comment]
If you disconnect and then reconnect to that cluster does the problem still persist?

**Comment by brainstain** [comment]
I am having the same issue.  Some clusters work, one does not.  I've attempted disconnecting & reconnecting, restarting the computer, removing the entry from .kube/config and regenerating.

**Comment by robbesettlemint** [comment]
Yes, even uninstalled and reinstalled Lens and resetted my kubeconfig.

**Comment by Nokel81** [comment]
Okay thanks, can you try turning off the "download kubectl" preference and then completely restarting lens (including tray) and seeing if that resolves the issue?

**Comment by robbesettlemint** [comment]
Tried that, but still having the same problem.

**Comment by Nokel81** [comment]
if you open up dev tools do you see any errors in the console?

**Comment by themooer1** [comment]
I'm having the same problem with the single cluster in `~/.kube/config`. Here is my kubeconfig (which worked on older versions of Lens) with minimal redactions:

```
apiVersion: v1
kind: Config
clusters:
  - name: kanaan
    cluster:
      server: https://joshua:6443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTWpRek16Y3pORFF3SGhjTk1qRXdOakl5TURRME9UQTBXaGNOTXpFd05qSXdNRFEwT1RBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTWpRek16Y3pORFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZWJOMXBYejhVZWR2dzl3cDBPYkRXaHdla2pkQVNoR2gxTk0zSFg5blgKRU9VR0lGRUpnZjYrdXp0RU1MNG1zd3dOaElRdjlIbHJlc3RuMjg0b3dQMXNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUZVT1d1a1RBc3g5S1FBT21Dd052ClJpTkVyVW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVA5cWRmd3I1QmFoQ29RcTVjaEF6bElubldNMitzWlYKMEpTTnc5SGFLMERwQWlBdERHajl3T0xNdkdmaDJwMUZDZCsrKzRCazRheXhmN1I4ZUxOS3ZCWnVhQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
users:
  - name: default
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJZGhrcXR4eG5JSWN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOakkwTXpNM016UTBNQjRYRFRJeE1EWXlNakEwTkRrd05Gb1hEVEl5TURZeQpNakEwTkRrd05Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOOW5zSWZzNk1UeUhoK08KU05IS2UzOUEwRGFwZTZvNzF2TXNUOVJHeFdJR1hMSDA3d2ZwQ1RPVFBjQkJwRTd2cTE3amk4djFteThUMVhPVQpLTmY3MktpalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUmtQNEZ2aXZ6QnlmQVFYQ1Z4NTg3YWlLSitCekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCOXFWRER1am1heDNMYVFyUDV6aVlaWFV1YjR6cWg4ajFIdXZQTGhudkl5Z0lnSGFJb0UrYXVFNWxmMVdZUApNNTdLTVhqNjlteW5WMWZDd2ZsdHJ3TXdiWDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTWpRek16Y3pORFF3SGhjTk1qRXdOakl5TURRME9UQTBXaGNOTXpFd05qSXdNRFEwT1RBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTWpRek16Y3pORFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRQkJqNFEza2g5Q3VOTk5RUmdKK1dla05LdHY5UGZHdjJrRSswTTloTlAKdmNTSEpQdE9RaHExRXZhZ0k1YkNaQ2VDdXJYV2swR1RWY0wva0hHSkxpYStvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpEK0JiNHI4d2Nud0VGd2xjZWZPCjJvaWlmZ2N3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpSL3RScStLa2dJcjlFcFlMZktWa3hEbkVmNlBZQ2MKZlp0VW1CQ1d0eGZqQWlBeDUzSm8rVGVWeWhRS285ZXlFWEswanQvYjBUQTBZQzcvSXdPZWc1OXA4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      client-key-data: >-
        ABCDABCDABCD=
contexts: []
preferences: {}
current-context: kanaan
```

**Comment by themooer1** [comment]
This config works for the same cluster (same client key):

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTWpRek16Y3pORFF3SGhjTk1qRXdOakl5TURRME9UQTBXaGNOTXpFd05qSXdNRFEwT1RBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTWpRek16Y3pORFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZWJOMXBYejhVZWR2dzl3cDBPYkRXaHdla2pkQVNoR2gxTk0zSFg5blgKRU9VR0lGRUpnZjYrdXp0RU1MNG1zd3dOaElRdjlIbHJlc3RuMjg0b3dQMXNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUZVT1d1a1RBc3g5S1FBT21Dd052ClJpTkVyVW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVA5cWRmd3I1QmFoQ29RcTVjaEF6bElubldNMitzWlYKMEpTTnc5SGFLMERwQWlBdERHajl3T0xNdkdmaDJwMUZDZCsrKzRCazRheXhmN1I4ZUxOS3ZCWnVhQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://joshua:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJZGhrcXR4eG5JSWN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOakkwTXpNM016UTBNQjRYRFRJeE1EWXlNakEwTkRrd05Gb1hEVEl5TURZeQpNakEwTkRrd05Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOOW5zSWZzNk1UeUhoK08KU05IS2UzOUEwRGFwZTZvNzF2TXNUOVJHeFdJR1hMSDA3d2ZwQ1RPVFBjQkJwRTd2cTE3amk4djFteThUMVhPVQpLTmY3MktpalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUmtQNEZ2aXZ6QnlmQVFYQ1Z4NTg3YWlLSitCekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCOXFWRER1am1heDNMYVFyUDV6aVlaWFV1YjR6cWg4ajFIdXZQTGhudkl5Z0lnSGFJb0UrYXVFNWxmMVdZUApNNTdLTVhqNjlteW5WMWZDd2ZsdHJ3TXdiWDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTWpRek16Y3pORFF3SGhjTk1qRXdOakl5TURRME9UQTBXaGNOTXpFd05qSXdNRFEwT1RBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTWpRek16Y3pORFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRQkJqNFEza2g5Q3VOTk5RUmdKK1dla05LdHY5UGZHdjJrRSswTTloTlAKdmNTSEpQdE9RaHExRXZhZ0k1YkNaQ2VDdXJYV2swR1RWY0wva0hHSkxpYStvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpEK0JiNHI4d2Nud0VGd2xjZWZPCjJvaWlmZ2N3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpSL3RScStLa2dJcjlFcFlMZktWa3hEbkVmNlBZQ2MKZlp0VW1CQ1d0eGZqQWlBeDUzSm8rVGVWeWhRS285ZXlFWEswanQvYjBUQTBZQzcvSXdPZWc1OXA4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: ABCDABCDABCD=
```
