### ISSUE TITLE
Workloads/Overview pane consistently crashes

### ISSUE THREAD

**Issue by AdamKleinStandard** [kontena/lens#3919]
**Describe the bug**
With version 5.x (all installed versions, currently Lens: 5.2.4-latest.20210923.1 / Electron: 12.0.17 / Chrome: 89.0.4389.128 / Node: 14.16.0), on any cluster, the "Workloads/Overview" pane immediately crashes.

**To Reproduce**
1. Go to (any cluster) 'Workloads'
2. Click on 'Overview'
3. See error

**Expected behavior**
I expect to see an overview of the cluster [workloads]([url](url))

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.4-latest.20210923.1
- OS: OSX
- Installation method .dmg

**Logs:**
```
Error stack:

 
TypeError: Cannot read property 'clientWidth' of undefined
    at render (/Users/aklein2/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:1472:12)
    at http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:10151:59
    at trackDerivedFunction (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:2024:18)
    at Reaction.track (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:10149:14)
    at r.makeComponentReactive (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:10164:25)
    at r.target.render (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:10077:34)
    at qi (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535639:188)
    at pi (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535638:173)
    at ck (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535721:427)
    at bk (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535702:347)
    at ak (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535702:278)
    at Tj (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535702:138)
    at Lj (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535695:163)
    at http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535575:115
    at exports.unstable_runWithPriority (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535786:343)
    at gg (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535574:325)
    at jg (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535575:61)
    at ig (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535574:428)
    at Hb (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535744:101)
    at gd (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:535525:352)
    at HTMLDivElement.sentryWrapped (http://161a532d830834091a59f95fcfe31627.localhost:64265/build/Lens.js:696383:23)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    certificate-authority-data: [REDACTED]
    server: "https://10.97.37.7:6443"
  name: "nonprod"
contexts:
- context:
    cluster: "nonprod"
    user: "kube-admin-nonprod"
  name: "nonprod"
current-context: "nonprod"
users:
- name: "kube-admin-nonprod"
  user:
    client-certificate-data: [REDACTED]
    client-key-data: [REDACTED]
```

**Additional context**
