### ISSUE TITLE
error: client-key-data or client-key must be specified for kubernetes-admin to use the clientCert authentication method

### ISSUE THREAD

**Issue by jiker-burce** [kontena/lens#3941]
**Describe the bug**

**To Reproduce**
1.  copy the kube config in the linux operation system which is in the virtual box
2. click "Catalog => clusters => add from kube config
3. paste the content of step 1 here
4. click Add clusters
5. click to open

**Expected behavior**
error: client-key-data or client-key must be specified for kubernetes-admin to use the clientCert authentication method.

proxy exited with code: 1

**Screenshots**
![image](https://user-images.githubusercontent.com/24581223/135717174-317acaaa-451b-47ec-b56b-4c90428d3528.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.5-latest.20211001.2
- OS: Mac 10.15.7 

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
[root@vm210 snapd]# cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3lNREUyTXpBME5sb1hEVE14TURneE9ERTJNekEwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmJMCjlRRzQvOHl4SjBWUjcxeTN4MWRvUkd5N1ZuRGE4Q085MXcrT0RPMGdZNnBJa0lIZDgyUFdVeENQeXVsZ0daamsKRmw5dWdhYXVQMURwZDdEOGdSZzBwVkF2VUFlL25iOXA2UVJDMHUrNUNiLzVGeUk3N1h2b1FzVTdXbVI5OW15MAoyVkhJeGRnV1NOY3lmVjFRVkxmUWZmenVTL2RyVGpIVXF5OFppQWlWOGdZeDNid0thNHVITkVpV0ZBb2VadzBVCi9PMlRHZ0dobmZSTFB3WWxQNmQ5dHVZV0tuQ2twRldqV3BmOUZYZCt0cUppZHJ6dkR3dmc1R3c3YWJTaUFJaDgKbWlzakJwcTFaTDZuLzlqbXZPdGxQWmFMdzdzS0dYNDIyZnlMaFdLbHhmc05ISER0dDVLZlA3UzRzeXFTeVdwcgpzQ1JkWUNFLzQ3dEV3ZWpTMUhVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDYUZpRDVMYzVONmNFQzl0bC9hSnhkb0h0N3FNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRC85amxLNEZRQWRyZEZZU0dHZApqdlpqNXpNbTBFY3hVRk1lSXIra1hDcEx3ZUZJMXdONHEzejErUlZqQUNwYk1lUVF2S0J4dnRackQzVTBkYjBVClpCQzJqbTJVUEc1MVdwY25QVUZmQnRXb0RLcll5eExmcVRRejhqSzBZNUdNOWhlSlo2d1A2VjAyeW5ERURBbFoKL3JFbmsvOENPNEhRVE9WR3ZxVlh6dTM3YnhYOEE2RUNCSUV5bGxPTVh5NFJ4WUNZM3J2NzkweWxCQnRhSEI3TAp4U0RoNldzWGFHeVkwVWhKWWthOG9wby9KRG04UExxOVMvVmgySUNhcXNaTVhBU04wYWsvQ2FOTnpYdHBGa0tjCndFb3d3VDg3LzZnVHpDQXJJMHg0TmFKaTVmakcrR3grdzRsbWRzWGIvbG1saW00V3IwelN5eGQ2RFd4TVJUK0EKVWhZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.56.210:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJSm02a2kwRGVLcjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNE1qQXhOak13TkRaYUZ3MHlNakE0TWpBeE5qTXdORGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTI0MWxmTC9RMHpOb3JWUCsKTXlCdFJ6Q3ZBcGwvNDhSbnRtWlNob1hWOFRLQzR2MDNpVHkyTmQ4ZFc2ZTFLeVpKOEhnZzFWRjliVHhaKzF6Zwp6VlhXUnB6SHllSzk4TzQvMUwrTXUzN09wNjdBbHNiMXp1WE4vU3NvRGhsQ3lvRjRhNlVRQ29yVW1xcDNVODFZCm9vdEVSeGRyQ0FSckQwQWszNjV2L1dKdVNyenN5VExQc21nalYxMUkzZnpQSmNRbVBPZmt1YU1jWVJkR3YxOUoKKy9hTVVxL2dqMnd5ajJvWFpOMTRFVUFJQm1ZQTVXVUxsZmxQM2NSNmNvbldGTTlMU2FGbHlOSlplWHlKYnJnaQpQTjluOTBEKzIzeis1bmFZcG9XclRDcGt2eUZUSTE3RXlCbFY3TTZFUSt0K003NVR4YVNEUmdXUEpiK1FhRjc1Ck52RjE0UUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRbWhZZytTM09UZW5CQXZiWmYyaWNYYUI3ZQo2akFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQmhWTlRSU1IxM08zZU9vMjQzNHhxcDRySUQvUWVOTVo4cjgrCjVNSXF6RmpEejZCL0tBYnNjVXFad2tBV3VZMGJ3djEzb1Q4TFFxaW1PcVcxYUtyZ2xlSXB2NmJ0ZHFCQnRMbmEKK2Q3UDJrVkNlOVo3VjZSUzF3OXRUSzlRWHhRbzk5RC9UMEhDMklCUUt3bGhMRS8yR3VIWWtKanNNZDB3S0k3awpWRmdpQitmcGp6TkJSMzBPTGREblFnMUFSUjhpaHlLaVFMdnQ5NUNLN0dhckxwa1FmSVBHLy9oa20vUWlCODFtCmROelBWMVlxa1dNVmlQcFhnSExIbjVHQnFXNHdXOXhLUFhINTN6dXd2cmhXckdPZUpDNmJsWEc4bEJXaEt0czIKUDNmMzBtZEJHeEVnVnRVbXRveGNNWDZEK3d6YjhzVUdtS1Z5RkRSUkZ3QmdyNnJtZkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMjQxbGZML1Ewek5vclZQK015QnRSekN2QXBsLzQ4Um50bVpTaG9YVjhUS0M0djAzCmlUeTJOZDhkVzZlMUt5Wko4SGdnMVZGOWJUeForMXpnelZYV1Jwekh5ZUs5OE80LzFMK011MzdPcDY3QWxzYjEKenVYTi9Tc29EaGxDeW9GNGE2VVFDb3JVbXFwM1U4MVlvb3RFUnhkckNBUnJEMEFrMzY1di9XSnVTcnpzeVRMUApzbWdqVjExSTNmelBKY1FtUE9ma3VhTWNZUmRHdjE5SisvYU1VcS9najJ3eWoyb1haTjE0RVVBSUJtWUE1V1VMCmxmbFAzY1I2Y29uV0ZNOUxTYUZseU5KWmVYeUpicmdpUE45bjkwRCsyM3orNW5hWXBvV3JUQ3BrdnlGVEkxN0UKeUJsVjdNNkVRK3QrTTc1VHhhU0RSZ1dQSmIrUWFGNzVOdkYxNFFJREFRQUJBb0lCQVFDSDVEalF3aGtLNEdNRwpCVnJ0WWtEQk00emZXd3NoZTB1R1JrY0dKSWlMUmV4bGVyMkpJQjdYc1VXR21ZTTFOZm5GOFZUQk5ETWlEWnpVClRHU0lNM3p4TDlFcFVFS29nWTdZcThiN3RqMUs1SXNueC9ZVkhZQW1GelF2cGNzRmRLV0lXeDVXcUI5M3E5TTMKOTMzSS9kSkEvbW10Q0s4TFBYU1ZUbTdhc3JYNVkxaDBLSTlzalFIWURraEhQNGg0bVBPbEFEWksrUDJIWC9SSgp5MlRoVVM1MW1aM25PUXdRTGVSd0tQa3Nrb2pYVnV3N3BIYytwY1dTb2FJc0RkMzVUMVZuOTlnR0h1eGh3V0l0CjBlT1kxMGZZekxtTGFzTHN4ZkxrRVlqRmxzUGtaNjhBRmNpN0ErMzZxekFpaThvU3dNcGZvKzZJYm9USFoxM2oKdG8vdGowbkJBb0dCQU9DblU2eHpmNkIyTTRlRWFBZ21uZ29mSEVtTEliVTlmZDhZY3l2MXZUQm1XaTFCSFJOVwpHK0ROUDN5dVg2cnk2US9hMm1NRUd0ZGVuMmIyazl0c1g3V3ZBMFJ3M1lueEI4eHBjTnJCZUhSdlViVm0zak1qCitLMnUwKytRQ3d4SVBFRWRSdnZzTnNDeC9td0hUcHNUUVNVTndmalcwWmtKRTBGd25Uc3JJWVExQW9HQkFQb3YKMmJaOHdPTmhnTXR3R1owRDFkVUt3eUR1Q1dPMEhMT014WUNTbDkvT1N6b3QrbUhWem15R25uUUVrUU00ZjFFMApjVDZtdlV4eGQ3SGhTazZHSHZhRk0rMjFBeldRc3gzcGoxNEljcUtNTEE5UlRVc1gvT3crQllOWVhHQlloMlM1CmpFZmh5YnlMS0VlYjRtZkxLOWJLWDlBMDZHWDB6OUdXSENURGNVaDlBb0dBRlFiVVNCSFBZajl0OTBNblVZdjcKd3NyQ3BRZUdzaVg5UUFKVDFVdDgxNmpjeTl1S1V5TCtIUDVZOE55SlM4RE1tNVZLVjNZczVQZVFSOXpRWGZzNAp3aEtOWmJ5Q244U1ZqRVphTDc5bi9NM21nZW9NNWhCNTJCZkM4bXN5L1lWTlRuTGxEL005OUs4ME52eEFHVGVtCkkwZTBYZ3dOTmh1cFY3aW9ucjhjdGZrQ2dZRUFvYnhUVTB5YzZhRzd3RWhzMW51SFBkMWlQYVNFZjJjTmN1bGIKT0g0TUhvdmZSL0kzUGc0WkQwR0xwOWJYNUN3ZTZtRXJvR1BzVmtHNExrOUZXVFFOU2pMY1dodzl3ZUFVV3c4RgpOclhoWGNHZUxoelNDZXlzL2hBdVFqWGFLaEt4SEdWekVYa2VrSHVwZzNsN3lMdW9VSWV0bnd6RS9EeGlLTXlRCnp4ZGw0WVVDZ1lFQXRlZW5kc0lsdDRhclBSMVNwSjJZS1RzcGZvU3JVTG1XN2cwY0hybWdoand6bHdnTWREVTAKMTNycE04Zk5IbVkvK0FNdkIxUEdBMUdndG8ycFhpT3Rub1NaZEE0UDdWd1V6UmcwMHI4dVVXMk9NdWZXZS9NZgpCN0dYWUlkSXFqdXVORUc3R2NCK0wvT01xS2l0S25zT0prbGNCN3ZQMUZmaDh4N3I1MzVEQ1djPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

**Additional context**
```
[root@vm210 snapd]# k get nodes
NAME    STATUS   ROLES                  AGE   VERSION
vm210   Ready    control-plane,master   41d   v1.22.0
vm211   Ready    <none>                 41d   v1.22.0
vm212   Ready    <none>                 41d   v1.22.1
```
