### ISSUE TITLE
Empty current-context not recognized

### ISSUE THREAD

**Issue by iceychris** [kontena/lens#3943]
Hey!

I just ran `kubectl config view --raw --flatten` on my cluster
to export the config for use in Lens:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1
  name: local
contexts:
- context:
    cluster: local
    user: cluster-admin
  name: ""
current-context: ""
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:
    client-certificate-data: ...
    client-key-data: ...
```

I've added this to `$HOME/.kube/config`.

Lens would not recognize the cluster at first.
I then gave the the context a proper name (which previously was `""`):

```yaml
...
contexts:
- context:
    cluster: local
    user: cluster-admin
  name: "my-k8s-cluster"
current-context: "my-k8s-cluster"
...
```

After that change, everything works as expected.

Not sure if this is already fixed in a more recent version of Lens.

**What would you like to be added**:

Either

- having an empty `current-context` (`""`) should just work
- or the user should be prompted to set a proper context name

**Why is this needed**:

Bad UX for users new to Kubernetes or Lens.

**Environment you are Lens application on:**

- Kubernetes distribution: NixOS on-prem
- `kubectl --version`: `v1.19.6-rc0`
- Desktop OS: `Ubuntu 20.04.3`
- Lens Version: `5.2.5.latest-20211001.2` (installed via `.deb` from website)
