### ISSUE TITLE
Add Accessible Namespaces

### ISSUE THREAD

**Issue by ghostzero** [kontena/lens#4002]
**Describe the bug**
Currently i always get the "Add Accessible Namespaces" notification. Because i have a configuration where the service account do not have the permission to get all namespaces, which is intended.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Namespaces'
3. Add acccessible namespaces.
4. Save
5. Use app
6. 'Add Acessible Namespacces' Info appears

**Expected behavior**
As i defined acessible namespaces, the app will not remind me, or i get more details why this error ocurr.

**Screenshots**
![image](https://user-images.githubusercontent.com/6547306/136674662-dd454946-4f64-4bbf-950c-7097f310b16d.png)
![image](https://user-images.githubusercontent.com/6547306/136674793-1fbcac39-054c-4d7e-a948-96e50830a8b4.png)
![image](https://user-images.githubusercontent.com/6547306/136674800-fb1c2e86-0452-48db-9e85-c36764cd7336.png)
![image](https://user-images.githubusercontent.com/6547306/136674803-1f428bef-c32b-4409-9d9e-722cfbf5c842.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.202111001.2
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): Installer via Website

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
clusters:
  - name: "example-app-production"
    cluster:
      server: "server url"

users:
  - name: "example-app-production-user"
    user:
      token: "add user token here"

contexts:
  - name: "example-app-production"
    context:
      user: "example-app-production-user"
      cluster: "example-app-production"

current-context: "example-app-production"
```
