### ISSUE TITLE
Secrets sometimes not obfuscated by default

### ISSUE THREAD

**Issue by jonasdebeukelaer** [kontena/lens#4016]
**Describe the bug**
After entering a secret through lens, and navigating away and back to the contents of the secret, the secret is sometimes not obfuscated/hashed by default.

**To Reproduce**
1. Create a secret with an empty string secret
   ```
   kubectl create secret generic test-secret --from-literal=test=''
   ```
2. Open the secret using Lens and the visiblity icon is not there
3. Even after entering a new value and closing/reopening the secret in lens, the secret is shown as a plain string by default

**Expected behavior**
Any secret value should be hidden before and after a manual update by default even if empty

**Screenshots**
![image](https://user-images.githubusercontent.com/9272376/136965092-2a6deba4-fd03-49c3-ad03-7dfefa904b92.png)
notice no eye icon 
![image](https://user-images.githubusercontent.com/9272376/136965984-b8c115dd-3c59-482c-b11f-06f1bdeff205.png)

**Environment (please complete the following information):**
- Lens Version: `5.2.3-latest.20210921.1`
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): download

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <HIDDEN>
    server: <HIDDEN>
  name: <HIDDEN>
- cluster:
    certificate-authority-data: <HIDDEN>
    server: <HIDDEN>
  name: <HIDDEN>
- cluster:
    certificate-authority-data: <HIDDEN>
    server: <HIDDEN>
  name: gke_<HIDDEN>_europe-west1-b_gitlab-ci-cluster-1
- cluster:
    certificate-authority-data: <HIDDEN>
    server: <HIDDEN>
  name: kubeflow-cluster
contexts:
- context:
    cluster: <HIDDEN>
    user: <HIDDEN>
  name: <HIDDEN>
- context:
    cluster: <HIDDEN>
    user: <HIDDEN>
  name: <HIDDEN>
- context:
    cluster: gke_<HIDDEN>_europe-west1-b_gitlab-ci-cluster-1
    user: gke_<HIDDEN>_europe-west1-b_gitlab-ci-cluster-1
  name: gke_<HIDDEN>_europe-west1-b_gitlab-ci-cluster-1
- context:
    cluster: kubeflow-cluster
    user: clusterUser_ml-traffic4cast_kubeflow-cluster
  name: kubeflow-cluster
current-context: <HIDDEN>
kind: Config
preferences: {}
users:
- name: <HIDDEN>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-2
      - eks
      - get-token
      - --cluster-name
      - dev-1
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev
- name: <HIDDEN>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-2
      - eks
      - get-token
      - --cluster-name
      - prod-1
      command: aws
      env:
      - name: AWS_PROFILE
        value: prod
      provideClusterInfo: false
- name: clusterUser_ml-traffic4cast_kubeflow-cluster
  user:
    client-certificate-data: <HIDDEN>
    client-key-data: <HIDDEN>
    token: <HIDDEN>
- name: gke_<HIDDEN>_europe-west1-b_gitlab-ci-cluster-1
  user:
    auth-provider:
      config:
        access-token: <HIDDEN>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/jonas/thirdparty_repos/gcloud/google-cloud-sdk/bin/gcloud
        expiry: '2021-10-06T14:26:58Z'
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

**Additional context**
