### ISSUE TITLE
Can't delete cluster from kubeconfig if on another partition than the temp directory

### ISSUE THREAD

**Issue by gganssauge** [kontena/lens#4017]
**Describe the bug**
My home directory is on a different partition than the temp directory.
When I try to delete a cluster from the kubeconfig file an error popup appears, saying:

> Cannot remove cluster, failed to process config file. Error: Failed to acquire lock file.
> Error: EXDEV: cross-device link not permitted, rename
> '/tmp/b26b77b25c52bced39a97498a2904206' -> '/home/gotti/.kube/config'

**To Reproduce**
1. Go to 'catalog
2. Click on 'the three vertical dots right to a cluster in kubeconfig'
3. Select 'Delete'
4. In the popup select a different context in 'current-context'
5. Click on button 'Delete Context'
6. see error

**Expected behavior**
I expect the context to be removed from my kubeconfig

**Environment (please complete the following information):**
- Lens Version: 5.2
- OS: [e.g. OSX] Linux Ubuntu-20.04
- Installation method (e.g. snap or AppImage in Linux): snap

**Logs:**
There are no logs specific to this error

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/gotti/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 04 Oct 2021 15:34:38 CEST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
- cluster:
    certificate-authority-data: **removed**
    server: https://dev-test-2110121639-2119080a.hcp.northeurope.azmk8s.io:443
  name: DEV
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 04 Oct 2021 15:34:38 CEST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: DEV
    user: clusterUser_dev-test-2110121639_DEV
  name: DEV
current-context: DEV
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/gotti/.minikube/profiles/minikube/client.crt
    client-key: /home/gotti/.minikube/profiles/minikube/client.key
- name: clusterUser_dev-test-2110121639_DEV
  user:
    client-certificate-data: **removed
    client-key-data: **removed**
    token: **removed**
```

**Additional context**
none
