### ISSUE TITLE
Blank Screen when accessing one (out of three) clusters

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#4018]
I have 3 clusters on Digital Ocean under various accounts.
I have always been able to connect to them with Lens.
About a week ago, I suddenly couldn't connect to one of the clusters.
I've tried deleting and re-adding the config in kubectl, I've tried deleting and re-adding it to Lens.
I just get a blank screen.  kubectl works fine, it's just Lens that isn't showing anything.
Lens has no trouble with the other clusters.  They are all running the same version.

Here's a screenshot of Lens and the terminal I launched it from when I try to connect to the cluster that Lens is having issues with:

![Screenshot from 2021-10-12 09-42-00](https://user-images.githubusercontent.com/158380/136996871-d8276707-7b6f-487b-9f18-234ec49a1431.png)

- Lens Version: 5.2.5
- OS: Linux (Mint)
- Installation method (e.g. snap or AppImage in Linux): AppImage

```
apiVersion: v1                                                                                                          
clusters:                                                                                                               
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo2-aaronkube                                                                                               
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo2-caitkube                                                                                                
- cluster:                                                                                                              
    certificate-authority-data: --redacted--
    server: https://--redacted--.k8s.ondigitalocean.com                                         
  name: do-sfo3-personalkube                                                                                            
contexts:                                                                                                               
- context:                                                                                                              
    cluster: do-sfo2-aaronkube                                                                                          
    user: do-sfo2-aaronkube-admin                                                                                       
  name: do-sfo2-aaronkube                                                                                               
- context:                                                                                                              
    cluster: do-sfo2-caitkube                                                                                           
    user: do-sfo2-caitkube-admin                                                                                        
  name: do-sfo2-caitkube                                                                                                
- context:                                                                                                              
    cluster: do-sfo3-personalkube                                                                                       
    user: do-sfo3-personalkube-admin                                                                                    
  name: do-sfo3-personalkube                                                                                            
current-context: do-sfo2-aaronkube                                                                                      
kind: Config                                                                                                            
preferences: {}                                                                                                         
users:                                                                                                                  
- name: do-sfo2-aaronkube-admin                                                                                         
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=cait                                                                                                  
      - 28472d7b-cac9-4eb7-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                                                         
- name: do-sfo2-caitkube-admin                                                                                          
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=cait                                                                                                  
      - 016d3b15-5806-4f83-8921-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                                                         
- name: do-sfo2-redactedkube-admin                                                                                        
  user:                                                                                                                 
    token: --redacted--
- name: do-sfo3-personalkube-admin                                                                                      
  user:                                                                                                                 
    exec:                                                                                                               
      apiVersion: client.authentication.k8s.io/v1beta1                                                                  
      args:                                                                                                             
      - kubernetes                                                                                                      
      - cluster                                                                                                         
      - kubeconfig                                                                                                      
      - exec-credential                                                                                                 
      - --version=v1beta1                                                                                               
      - --context=personal                                                                                              
      - 6f766a4d-2e46-4ca9-90c0-redacted
      command: doctl                                                                                                    
      env: null                                                                                                         
      provideClusterInfo: false                                                   
```

This is a screenshot of the developer console in Lens when it can't connect:
![Screenshot from 2021-10-12 09-51-15](https://user-images.githubusercontent.com/158380/136997624-eeef82a4-8dff-4ca3-b1e0-2251199a70c5.png)
