### ISSUE TITLE
Clusters undefined after updating to v5

### ISSUE THREAD

**Issue by alondahari** [kontena/lens#4152]
**Describe the bug**
After updating lens to v5.2, I can't click on my clusters, and it says they're undefined.

**To Reproduce**
1. Start lens
2. Click on a cluster

**Expected behavior**
I should be able to connect to a cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/5546798/139082540-9c4b0b8a-ec33-495d-8256-0dd4c29be057.png)

**Environment (please complete the following information):**
- Lens: 5.2.5-latest.20211001.2
- Electron: 12.2.1
- Chrome: 89.0.4389.128
- Node: 14.16.0
- OS: MacOS 11.6
- Installation method (e.g. snap or AppImage in Linux): dmg file

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
How do I do that on mac? I'm not seeing any logs in the command line.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cert>
    server: https://<server-address>.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
- cluster:
    certificate-authority-data: cert
    server: https://<second-server-address>.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
- cluster:
    certificate-authority-data: <cert>
    server: https://<third-server-address>.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
    user: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
  name: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
- context:
    cluster: arn:aws:eks:us-west-2:<aws-account-number2>:cluster/<our-app-name>
    user: arn:aws:eks:us-west-2:<aws-account-number2>:cluster/<our-app-name>
  name: arn:aws:eks:us-west-2:<aws-account-number2>:cluster/<our-app-name>
- context:
    cluster: arn:aws:eks:us-west-2:<aws-account-number3>:cluster/<our-app-name>
    user: arn:aws:eks:us-west-2:<aws-account-number3>:cluster/<our-app-name>
  name: arn:aws:eks:us-west-2:<aws-account-number3>:cluster/<our-app-name>
current-context: arn:aws:eks:us-west-2:<aws-account-number3>:cluster/<our-app-name>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:<aws-account-number>:cluster/<our-app-name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - <our-app-name>
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev
- name: arn:aws:eks:us-west-2:<aws-account-number2>:cluster/<our-app-name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - <our-app-name>
      command: aws
      env:
      - name: AWS_PROFILE
        value: prod
- name: arn:aws:eks:us-west-2:<aws-account-number3>:cluster/<our-app-name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - <our-app-name>
      command: aws
      env:
      - name: AWS_PROFILE
        value: stage
```

**Additional context**
It was working fine before the update, and no other updates were made
