### ISSUE TITLE
Doesn't display externalName for kubernetes Service

### ISSUE THREAD

**Issue by csantanapr** [kontena/lens#4179]
**Describe the bug**
I'm using knative and we create a service of type `ExternalName`, when using `kubectl get svc` the column "External IP" displays the value of `externalName` but in Lens is empty, I expect the value to show up in Lens

**To Reproduce**
0. create a service with the following yaml
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  externalName: kourier-internal.kourier-system.svc.cluster.local
  type: ExternalName
```
1. Go to Network
2. Click on Services
4. See "External IP" empty

**Expected behavior**
To see the value in the column `External IP` same as `kubectl` output

**Screenshots**
![image](https://user-images.githubusercontent.com/1094878/139362672-a1240e38-1301-4f7b-913b-55473cd40c9b.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.5
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Download dmg
