### ISSUE TITLE
Unable to get ingress metrics from prometheus

### ISSUE THREAD

**Issue by nickperkins** [kontena/lens#4348]
**Describe the bug**
I am unable to get ingress metrics within Lens. I have enabled prometheus on our cluster and I can get metrics for other resources. I believe it is because the query 

**Environment (please complete the following information):**
- Lens Version:Lens: 5.2.7-latest.20211110.1
- OS: [e.g. OSX] OSX
- Installation method (e.g. snap or AppImage in Linux): 

**Additional context**
From my investigations, Lens is querying for metrics against the namespace label as shown here: https://github.com/lensapp/lens/blob/c6dce043a7e3311af608566f60268ea1009e0609/src/main/prometheus/stacklight.ts#L141-L150
However in my prometheus data, the `namespace` label is set to the controller namespace. The ingress namespace is in the `exported_namespace` label. Here is an example from my prometheus data:
```
nginx_ingress_controller_request_duration_seconds_sum{container="controller", controller_class="k8s.io/ingress-nginx", controller_namespace="ingress-nginx", controller_pod="ingress-nginx-controller-5755898786-848rw", endpoint="metrics", exported_namespace="app-preproduction", exported_service="preproduction-app-accounts", host="accounts.preproduction.hutly.network", ingress="preproduction-app-accounts", instance="10.21.146.223:10254", job="ingress-nginx-controller-metrics", method="GET", namespace="ingress-nginx", path="/", pod="ingress-nginx-controller-5755898786-848rw", service="ingress-nginx-controller-metrics", status="200"}
```

I'm not sure if this is an issue with my prometheus stack though or a bug in Lens. I am using the kube-prometheus-stack.

**Comment by Nokel81** [comment]
Did you change the labelling rules for `kube-prometheus-stack` or are you using the defaults?

**Comment by nickperkins** [comment]
> Did you change the labelling rules for `kube-prometheus-stack` or are you using the defaults?

Here are the values I'm using:
```
defaultRules:
  rules:
    kubeScheduler: false
grafana:
  enabled: true
alertmanager:
  enabled: false
prometheus:
  ingress:
    enabled: false
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        app.kubernetes.io/part-of: flux
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
      ```
