### ISSUE TITLE
Specific network policy details through an TypeError

### ISSUE THREAD

**Issue by ewuknadierf** [kontena/lens#4520]
**Describe the bug**
Network policy details through an error in a specific network policy.
All my other network policies are working fine, and i can open the details.
Something in this specific network policy seems to be misinterpreted.

**To Reproduce**

0. Deploy Network Policy 'allow-ingress-to-dispatcher' (see below)
1. Go to 'Network Policies'
2. Click on Network Policy 'allow-ingress-to-dispatcher' to open details

**Expected behavior**
Details can be shown.

**Spec of network policy**
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-dispatcher
  namespace: test
  labels:
    app.kubernetes.io/app: dispatcher
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/namespace: test
    helm.toolkit.fluxcd.io/name: test
    helm.toolkit.fluxcd.io/namespace: test
  annotations:
    meta.helm.sh/release-name: dispatcher-test
    meta.helm.sh/release-namespace: test
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/app: dispatcher
  ingress:
    - ports:
        - protocol: TCP
          port: 50013
        - protocol: TCP
          port: 50014
      from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/app
                operator: In
                values:
                  - server
                  - replicator
                  - dispatcher
  policyTypes:
    - Ingress
```

**Environment (please complete the following information):**
- Kubernetes version: v1.21.5
- Lens Version: Lens: 5.3.2-latest.20211201.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): download from github

**Logs:**
```
Component stack:


    at NetworkPolicyDetails (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476066:51)
    at div
    at div
    at div
    at Animate (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:148811:9)
    at drawer_Drawer (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:14247:9)
    at KubeObjectDetails (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:289254:9)
    at ErrorBoundary (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:237949:9)
    at Router (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:79054:30)
    at ClusterFrame (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/chunks/5.js:7946:9)
    at ThemeProvider (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:609860:24)

Error stack:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at NetworkPolicyDetails.renderIPolicySelector (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476086:14)
    at http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476100:22
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.renderNetworkPolicyPeers (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476097:19)
    at http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476133:26
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.render (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:476131:25)
    at allowStateChanges (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:2571:12)
    at http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:11008:59
    at trackDerivedFunction (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:3120:18)
    at Reaction.track (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:3649:18)
    at NetworkPolicyDetails.reactiveRender [as render] (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:11006:14)
    at qi (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:556376:188)
    at pi (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:556375:173)
    at ck (http://a67df8ee09596b0b755ca52ee5f67421.localhost:60821/build/Lens.js:556458:427)
```

**Additional context**
