### ISSUE TITLE
Behind a websocket proxy (Cloudflare access)

### ISSUE THREAD

**Issue by Smana** [kontena/lens#4595]
Hello, I'm trying to use Lens behind a proxy that is configured using Cloudflare Access.
It finally works using [this procedure](https://developers.cloudflare.com/cloudflare-one/tutorials/kubectl) and kubectl is run using

```console
env HTTPS_PROXY=socks5://127.0.0.1:1234 kubectl get po -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-7cc879f8db-9m4m2   0/1     Pending   0          6h51m
kube-system   coredns-7cc879f8db-bprbm   0/1     Pending   0          6h51m
```

Note that I'm running **EKS** clusters and I had to add a few things to the `kubeconfig` to get the authentication working.

```yaml
apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://8A16FE1A1083D7CC91ADC4A2AE466A27.yl4.eu-west-1.eks.amazonaws.com
    name: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
contexts:
  - context:
      cluster: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
      user: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
    name: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
current-context: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:eu-west-1:xxx:cluster/cluster1
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - --region
          - eu-west-1
          - eks
          - get-token
          - --cluster-name
          - cluster1
        command: aws
        env:
          - name: AWS_PROFILE
            value: eu-west-1-prod-sadmin
          - name: HTTPS_PROXY
            value: ""
        provideClusterInfo: false
```

I tried to set the parameter `HTTP_PROXY` to `socks5://127.0.0.1:1234` but that didn't work.

Any help would be welcome :)
