### ISSUE TITLE
Can't connect to cluster behind a corporate proxy

### ISSUE THREAD

**Issue by tetsuhaut** [kontena/lens#4608]
**Describe the bug**
I am behind a corporate proxy that inspects my HTTPS traffic. In my `~/.aws/config` I set  `ca_bundle=<my root CA file>`.
I have to authenticate with `aws-azure-login --mode=gui`.
After that, the `kubectl` command works fine to display pods in any of my clusters. However, Lens won't show them.

**To Reproduce**
1. Authenticate with `aws-azure-login --mode=gui`
2. In Lens, go to Catalog, Categories > Clusters
2.  choose one of the clusters configured in `~/.kube/config` file
3. an error message is displayed: 
`SSL validation failed for https://sts.eu-west-3.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
E1224 10:40:20.691731 14868 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable C:\softs\Amazon\AWSCLIV2\aws.exe failed with exit code 255
getting credentials: exec: executable C:\softs\Amazon\AWSCLIV2\aws.exe failed with exit code 255`

**Expected behavior**
The cluster content appears in Lens

**Environment (please complete the following information):**
- Lens Version: 5.3.3-latest-20211223.1
- OS: Windows 10
- Installation method: Lens installer for windows, "just for me" as I don't have admin rights

**Logs:**
```
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +7ms
info:    ▪ [APP-PATHS]: initializing +0ms
debug:   ▪ [APP-MAIN] initializing remote +5ms
debug:   ▪ [APP-MAIN] configuring packages +0ms
debug:   ▪ [APP-MAIN] initializing ipc main handlers +0ms
debug:   ▪ [APP-MAIN] Lens protocol routing main +1ms

```

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <some base64 encoded key>
    server: <some prod server>
  name: <some prod cluster name>
- cluster:
    certificate-authority-data: <some base64 encoded key>
    server: <some non prod server>
  name: <some non prod cluster name>
contexts:
- context:
    cluster: <some prod cluster name>
    namespace: <some namespace>
    user: live_prod_user
  name: live_prod_profile
- context:
    cluster: <some non prod cluster name>
    namespace: <some namespace>
    user: live_staging_user
  name: live_staging_profile
current-context: live_staging_profile
kind: Config
preferences: {}
users:
- name: live_staging_user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: C:\softs\Amazon\AWSCLIV2\aws.exe
      args:
      - "--region"
      - "eu-west-3"
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "<some non prod cluster name>"
      env:
      - name: AWS_PROFILE
        value: "live_staging"
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: live_prod_user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: C:\softs\Amazon\AWSCLIV2\aws.exe
      args:
      - "--region"
      - "eu-west-3"
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "<some prod cluster name>"
      env:
      - name: AWS_PROFILE
        value: "live_prod"
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
