### ISSUE TITLE
Can't view some NetworkPolicys, throws TypeError

### ISSUE THREAD

**Issue by MarcMielke** [kontena/lens#4677]
Can't view some **NetworkPolicy**s, throws TypeError

**Version**
Lens: 5.3.3-latest.20211223.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0

**OS**
macOS Big Sur 11.4

**Component stack:**
    at NetworkPolicyDetails (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476092:51)
    at div
    at div
    at div
    at Animate (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:148838:9)
    at drawer_Drawer (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:14247:9)
    at KubeObjectDetails (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:289281:9)
    at ErrorBoundary (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:237976:9)
    at Router (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:79057:30)
    at ClusterFrame (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/chunks/5.js:7941:9)
    at ThemeProvider (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:609886:24)

**Error stack:**
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at NetworkPolicyDetails.renderIPolicySelector (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476112:14)
    at http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476125:22
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.renderNetworkPolicyPeers (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476123:19)
    at http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476159:26
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.render (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:476157:25)
    at allowStateChanges (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:2571:12)
    at http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:11008:59
    at trackDerivedFunction (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:3120:18)
    at Reaction.track (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:3649:18)
    at NetworkPolicyDetails.reactiveRender [as render] (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:11006:14)
    at qi (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:556402:188)
    at pi (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:556401:173)
    at ck (http://aa1db0fcc5eb08e750c8d3e60aa45241.localhost:52148/build/Lens.js:556484:427)

**To Reproduce**
I believe this can be reproduced by having a **spec.ingress.[...].from[...].namespaceSelector: {}** declaration, so far that's the only difference compared to other (viewable/editable) policies I could spot at a first quick glance.

Example:
```yaml
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          k8s-app: grafana
    - podSelector:
        matchLabels:
          k8s-app: prometheus
    - podSelector:
        matchLabels:
          k8s-app: ingress
          role: controller
    - namespaceSelector: {}
    ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      k8s-app: prometheus
  policyTypes:
  - Ingress
```
