### ISSUE TITLE
eks cluster logs fail after while, but work without lens

### ISSUE THREAD

**Issue by matti** [kontena/lens#4730]
(with eks ipv6 cluster)

after some time this starts to happen:
![image](https://user-images.githubusercontent.com/3893/150519239-d15be021-fcb3-4d52-bce1-ce50fbcb5bf2.png)

`Failed to load logs: no preferred addresses found; known addresses: []`

but `kubectl logs` works from (normal) terminal (without Lens)

kubeconfig:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXhPVEU0TWpZek4xb1hEVE15TURFeE56RTRNall6TjFvd0ZURVRNQkVHQTFVRQpBeasdfZBUmN6MlM0WlFud1dyNVM3dEVIWS9FL1VadmdNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBSjVRbmdaVkFaL2RnQ2swTFhNMjhxSVlyTGFQNDQ1VFJDYWhasdfm4ybjcxYmlLV0tDcGprR2FiZ1U1MUlxCkZwZUxRd2Q0dzZ5bDdmMFhYaFVRL2UwTGk4WlFRbHdkSW9YWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://02asdfsadfsdfsadfsdaf7.sk1.eu-north-1.eks.amazonaws.com
  name: eka.eu-north-1.eksctl.io
contexts:
- context:
    cluster: eka.eu-north-1.eksctl.io
    user: asdf-1@eka.eu-north-1.eksctl.io
  name: asdf-1@eka.eu-north-1.eksctl.io
current-context: asdf-1@eka.eu-north-1.eksctl.io
kind: Config
preferences: {}
users:
- name: asdf-1@eka.eu-north-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      - eka
      - --region
      - eu-north-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
```
