### ISSUE TITLE
Resource with YAML binary data can't be created

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/lens#4865]
**Describe the bug**
If a resource is created that uses [yaml binary encoding](https://yaml.org/type/binary.html), an error is displayed: `error: error validating "/private/var/folders/_j/ztr5t9y90jq_jpsz1s2ytvk40000gp/T/c2e945a68a4e9610d06d3dc88eb2e662/resource.yaml": error validating data: ValidationError(Pod.spec.containers[0].image): invalid type for io.k8s.api.core.v1.Container.image: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`.

The same resource can be created with `kubectl apply` using Lens terminal.

**To Reproduce**
1. Open a 'Create resource' terminal in Lens
2. Paste the following:
```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: !!binary bmdpbng=
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```

**Expected behavior**
Resource is created.

**Actual behavior**
Error notification is displayed.

**Environment (please complete the following information):**
- Lens Version: v5.4.0-beta.1. (Also broken in Lens: 5.3.3-latest.20211223.1).
- OS: Mac
- Installation method: `make dev`

**Additional context**
I was using a Lens DevCluster.
