### ISSUE TITLE
RBAC not reflected in UI

### ISSUE THREAD

**Issue by cotvictor** [kontena/lens#4922]
**Describe the bug**
We want to introduce role based access to our clusters where we are creating kubeconfigs from a service account. To the service accounts we granted various rights read/write over different resources on namespace level, also on resource on the cluster level. So far so good, when using generated config we have desired outcome when playing with kubectl, but once we use the exact same kubeconfig on Lens, it shows only resources that belongs to the service account namespace (rights on namespaces level) and namespaces(rights on cluster level).
A sample of our rbac looks like this:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qa-lsng
  namespace: qa-lsng
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qa-admin
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["","apps","extensions", "batch", "metrics.k8s.io"]
  resources: ["deployments", "configmaps", "pods", "secrets", "ingresses", "cronjobs", "services", "statefulsets", "pods/log", "events"]
  verbs: ["create", "get", "delete", "list", "update", "edit", "exec"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-ns1
  namespace: qa-ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qa-admin
subjects:
- kind: ServiceAccount
  name: qa-lsng
  namespace: qa-lsng

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-ns2
  namespace: qa-ns2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qa-admin
subjects:
- kind: ServiceAccount
  name: qa-lsng
  namespace: qa-lsng

```

**To Reproduce**
1. Create RBAC structure from above
2. Insert generated kubeconfig in Lens
3. Enjoy

**Expected behavior**
If with generated kubeconfig from above RBAC structure I can have above mentioned rights, why do I miss them in Lens? Am I missing something in the above configurations or is it just a bug in UI?

**Screenshots**
From the last screenshot (cli) it can be seen that I can see resources from another ns rather than `qa-lsng` and also I see clusterscope resources
<img width="1627" alt="Screenshot 2022-02-22 at 22 03 58" src="https://user-images.githubusercontent.com/29955860/155210372-80b98db8-69ed-4102-ad4e-bc20350cddb4.png">
<img width="1076" alt="Screenshot 2022-02-22 at 22 04 21" src="https://user-images.githubusercontent.com/29955860/155210387-b1a0d392-b213-452f-8ba8-66ef6232be2f.png">
<img width="660" alt="Screenshot 2022-02-22 at 22 05 18" src="https://user-images.githubusercontent.com/29955860/155210401-fa642b29-9401-40e4-aefc-0998accb6315.png">

**Environment (please complete the following information):**
- Lens Version:
Lens: 5.3.4-latest.20220120.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0
© 2021 Mirantis, Inc.
- OS: MacOs Monterey v12.0.1
Although the issue might not relay on this specific Lens version or PC OS, because this replicates across my team (various windows/linux machines with different Lens versions).

**Comment by Nokel81** [comment]
What does your kubeconfig look like? Does it have a user setup?

**Comment by cotvictor** [comment]
Below you can find my kubeconfig (with some small edits):
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${cert}
    server: https://aks-cluster-000000.hcp.westeurope.azmk8s.io:443
  name: charisma-online-aks
contexts:
- context:
    cluster: aks
    user: aks-admin-qa-lsng-token-user
    namespace: qa-lsng
  name: qa-lsng
current-context: qa-lsng
kind: Config
preferences: {}
users:
- name: aks-admin-qa-lsng-token-user
  user:
    token: ${token}
```
