### ISSUE TITLE
KubeObjectStore loadAll failures

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4923]
I observed this once on my dev cluster, applying a stress test. Have not been able to reproduce, opening this issue for further investigation.

https://user-images.githubusercontent.com/40840436/155217241-056edb61-9b0e-4128-a691-c58dcfa57c7f.mov

While the application was progressing kube resource item lists started showing no items, or failed to load items. Could only correct by disconnecting/reconnecting the cluster

Stress test:

`kubectl apply -f osm-tile-server.yaml`

This application downloads some files and processes them into a postgres database (using ~40GB storage) then starts an OSM tile server.

```
apiVersion: v1
kind: Service
metadata:
  name: osm-tile-service
spec:
  type: NodePort
  selector:
    app: osm-tile-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osm-tile-server
spec:
  selector:
    matchLabels:
      app: osm-tile-server # has to match .spec.template.metadata.labels
  serviceName: "osm-tile-server"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: osm-tile-server # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: task-pv-container
        image: overv/openstreetmap-tile-server
        args: ["run"]
        env:
          - name: UPDATES
            value: enabled
        ports:
          - containerPort: 80
            name: "osm-tile-server"
        volumeMounts:
          - mountPath: "/var/lib/postgresql/12/main"
            name: task-pv-storage-2
      restartPolicy: Always
      initContainers:
      - name: import-container
        image: overv/openstreetmap-tile-server
        args: ["import"]
        env:
          - name: UPDATES
            value: enabled
          - name: DOWNLOAD_PBF
            value: https://download.geofabrik.de/north-america/canada/ontario-latest.osm.pbf
          - name: DOWNLOAD_POLY
            value: https://download.geofabrik.de/north-america/canada/ontario.poly
        volumeMounts:
          - mountPath: "/var/lib/postgresql/12/main"
            name: task-pv-storage-2
  volumeClaimTemplates:
  - metadata:
      name: task-pv-storage-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "osmoutput"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: osmoutput
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/osmoutputdata"
```
