### ISSUE TITLE
Can't see custom resources in Lens, but kubectl can access them

### ISSUE THREAD

**Issue by IanMoroney** [kontena/lens#4927]
**Describe the bug**
AAD RBAC users who have been given permissions to get,list, and watch some custom resources are able to run kubectl commands to get and describe these resources, but Lens is missing the entire Custom Resources section.

**To Reproduce**
1. Open Lens
2. Click on Hotbar shortcut for a context
3. Scroll down to Access Control
4. Custom Resources are not listed.

**Expected behavior**
To see the list of custom resources.

**Screenshots**
![image](https://user-images.githubusercontent.com/10791260/155353542-7593e3d5-7c0d-4331-adc3-bd5ce170a00e.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.4-latest
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Chocolatey

**Kubeconfig:**
Would prefer not to share the .kube/config but if I have to, I can.

**Additional context**
Running for example a `kubectl get azureidentities --all-namespaces` returns valid data, but CRDs are still not visible in lens.

K8s reader RBAC role which is granted to these users:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader
rules:
- apiGroups: [“*”]
  resources:
    - daemonsets
    - deployments
    - deployments/rollback
    - deployments/scale
    - configmaps
    - cronjobs
    - daemonsets
    - endpoints
    - ingresses
    - jobs
    - networkpolicies
    - pods
    - replicasets
    - replicationcontrollers
    - secrets
    - serviceaccounts
    - services
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups: 
    - cert-manager.io
  resources:
    - certificates
    - certificaterequests
    - issuers
  verbs:
    - get
    - list
    - watch
- apiGroups: 
    - acme.cert-manager.io
  resources:
    - challenges
    - orders
  verbs:
    - get
    - list
    - watch
- apiGroups: 
    - aadpodidentity.k8s.io
  resources: 
    - azureidentitybindings
    - azureidentities
    - azurepodidentityexceptions
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - aadpodidentity.k8s.io
  resources: 
    - azureassignedidentities
  verbs: 
    - get
    - list
    - watch
```

**Comment by Nokel81** [comment]
Thanks for the report. Currently we do not look at the RBAC permissions of specific CRDs, only the ability to list and watch CRDs themselves.

**Comment by IanMoroney** [comment]
Is there a permission scheme to add for that?

**Comment by Nokel81** [comment]
You would need to allow `watch` and `list` for `/apis/apiextensions.k8s.io/v1/customresourcedefinitions`

**Comment by IanMoroney** [comment]
Can confirm this works!

```

- apiGroups: 
    - apiextensions.k8s.io
  resources: 
    - customresourcedefinitions
  verbs: 
    - get
    - list
    - watch
```
Thanks for the assist @Nokel81 !
