### ISSUE TITLE
Proxy cannot connect to rancher cluster

### ISSUE THREAD

**Issue by wastemaster** [kontena/lens#4984]
When trying to connect to a cluster managed by rancher (RKE)
I am getting the following error

proxy.go:170 "You kube context contains a server path /k8s/clusters/gjgjgjgjg, use --append-server-path to automatically append the path to each request"

And then it opens the cluster management interface - but shows now resuources there, because i guess not able to fetch them.

**Screenshots**
![lens-error](https://user-images.githubusercontent.com/969217/157585018-c09a55aa-e452-4c47-b0bb-6e8ed19a3aa1.png)

**Environment:**
- Lens Version: 5.4.1
- OS: Ubuntu 20.02
- Installation method (e.g. snap or AppImage in Linux):
dpkg -i Lens-5.4.1-latest.20220304.1.amd64.deb

**Kubeconfig:**
```
apiVersion: v1
kind: Config
clusters:
  - name: my-cluster
    cluster:
      server: https://rancher.domain.net/k8s/clusters/hjhjhjhjh
      insecure-skip-tls-verify: false
  - name: my-cluster-Ubuntu-2004-node-2
    cluster:
      server: https://10.10.10.1:6443
      certificate-authority-data: >-
        tututututututututututututututututututututututut
      insecure-skip-tls-verify: false
  - name: my-cluster-Ubuntu-2004-node-1
    cluster:
      server: https://10.10.10.2:6443
      certificate-authority-data: >-
        gjgjgjgjgjjgjgjgjgjgjgjgjgjgjgjghghghg
      insecure-skip-tls-verify: false
users:
  - name: my-cluster
    user:
      token: >-
        kubeconfig-user-fgfgfgf:XOXOXOXO
contexts:
  - context:
      cluster: my-cluster
      namespace: my-namespace
      user: my-cluster
    name: my-context
```

Is there any way to configure this --append-server-path flag when connecting to cluster?
