### ISSUE TITLE
CRD array of properties is shown concatenated

### ISSUE THREAD

**Issue by mcarn** [kontena/lens#4997]
**Describe the bug**
When reviewing a networking.istio.io/v1beta1 VirtualService with multiple gateways, the list is being shown concatenated rather than as a list

**To Reproduce**
1. Create a new VirtualService via helm with more than one gateway (array) https://istio.io/latest/docs/concepts/traffic-management/#gateways
2. Go to Custom Resources
3. Go to Networking.istio.io > VirtualService
4. See the slider appearing (see screenshot).

**Expected behavior**
A list of gateways and hosts.

**Screenshots**
The Gateway and Hosts are an array
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: routes
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "localhost"
    - "test"
  gateways:
    - default/gateway
    - mesh
```
![image](https://user-images.githubusercontent.com/28352648/157851296-5c63be4f-e4f7-4a5b-86c7-cc358a119465.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.4-latest.20220120.1
- OS: macOs Monterey 12.2.1
- Installation method (e.g. snap or AppImage in Linux): brew cask

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
No logs.

**Additional context**
The following snippet appears on DevTools, so I assume the value is not being processed.

```html
<div class="DrawerItem">
  <span class="name">Gateways</span>
  <span class="value">default/gatewaymesh</span>
</div>
```
