### ISSUE TITLE
What resources do lens need to get metrics 

### ISSUE THREAD

**Issue by xwzp** [kontena/lens#5046]
I had created a clusterRole with following rules. After that I created service account, clusterRoleBinding, kubeconfig.yaml manually.
```yaml
# ClusterRole.yaml
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - namespaces
      - nodes
      - services/proxy
      - nodes/proxy
      - nodes/metrics
      - pods/proxy
  - verbs:
      - create
      - get
      - update
      - list
      - delete
      - watch
      - patch
    apiGroups:
      - apps
    resources:
      - deployment
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
```
```yaml
# kubeconfig.yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  xxxx
    server: https://xxx:xxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: adam
  name: kubernetes-test@kubernetes
current-context: kubernetes-test@kubernetes
kind: Config
users:
- name: adam
  user:
    token:  xxxx
```
![image](https://user-images.githubusercontent.com/10193482/159121787-57490922-8396-4e08-8882-97f542c34d5d.png)

I added the kubeconfig.yaml to Lens and log in my cluster successfully, but it can't fetch metrics. 
I am wondering if there are some mistake I made and I really don't want login with default amin user. Could someone help, thx！
