### ISSUE TITLE
No metrics on Raspberry Pi OS 64bit

### ISSUE THREAD

**Issue by GiorgioAresu** [kontena/lens#5129]
**Describe the bug**
Memory metrics not showing for Pi 4 nodes on Raspberry Pi OS 64bit. They're showing just fine for an intel NUC with Ubuntu 20.04 LTS.
I can see metrics from node-exporter within grafana, and even lens can see them in the node details.

**To Reproduce**
1. Install prometheus-community's kube-prometheus-stack
2. Click on 'Nodes'
3. See error

**Expected behavior**
Memory should be present for all nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/2900713/160551063-2fd8ea5e-b834-4114-bd8e-2c494cc565ed.png)
![image](https://user-images.githubusercontent.com/2900713/160551068-32707aab-cf6b-430b-a842-85329e320c35.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.3-latest.20220317.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    Γû¬ ≡ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Γû¬ ≡ƒôƒ Protocol client register succeeded Γ£à +3ms
info:    Γû¬ [EXTENSIONS-STORE]: LOADING from  ... +12ms
info:    Γû¬ [EXTENSIONS-STORE]: LOADED from C:\Users\Giorgio\AppData\Roaming\Lens\lens-extensions.json +21ms
info:    Γû¬ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +5ms
info:    Γû¬ [FILESYSTEM-PROVISIONER-STORE]: LOADED from C:\Users\Giorgio\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json +3ms
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: https://10.17.1.24:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: [redacted]
    client-key-data: [redacted]
```

**Additional context**
No errors in developer tools console
