### ISSUE TITLE
Can't use "➕" -> "✏ Create resource" to create secret with empty fields

### ISSUE THREAD

**Issue by Andrei-Paul** [kontena/lens#5228]
**Describe the bug**
Can't use "➕" -> "✏ Create resource" to create secret with empty fields.

**To Reproduce**
1. Click "➕" (New tab)
2. Click "✏ Create resource"
3. Paste the following:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: 
  tls.key: 
```

4. See error:

> error: error validating "C:\\Users\\User\\AppData\\Local\\Temp\\1234567890abcdef1234567890abcdef\\resource.yaml": error validating data: [unknown object type "nil" in Secret.data.tls.crt, unknown object type "nil" in Secret.data.tls.key]; if you choose to ignore these errors, turn validation off with --validate=false

**Expected behavior**

> Secret [secret-tls]() successfully created.

**Environment (please complete the following information):**
- Lens Version: 5.4.5-latest.20220405.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):
Installer, updated plenty of times by now

**Additional context**
Works fine with non-empty fields
