### ISSUE TITLE
Lens does not show as connected under status column. 

### ISSUE THREAD

**Issue by agomez-infoblox** [kontena/lens#5241]
**Describe the bug**
I have lens installed and when I connect to a cluster, I can access the pods and interact with other K8 features, but the app does not show the cluster as connected. This does not allow me to then "disconnect" nor keeps me informed to which clusters I am actually connected to

**To Reproduce**
1. Go to 'Catalog Button'
2. Click on '.Clusters'
3. Connect to a cluster
4. View the cluster status (Connected|Disconnected)
5. See error (which in my case stays disconnected at all times)

**Expected behavior**
I am expecting to see it show connected to the cluster (green light when at the Hotbar)

**Screenshots**
<img width="709" alt="Screen Shot 2022-04-13 at 7 46 12 PM" src="https://user-images.githubusercontent.com/87830311/163287726-5cb9e24b-9c42-48d3-a49e-b890e2351891.png">

**Environment (please complete the following information):**
- Lens Version: 5.4.5-latest.20220405.1
- OS: [e.g. OSX] Monterey 12.3.1
- Installation method Downloaded from Lens website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://someurl.com:3026
  name: gstg-1
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://someurl.com:3026
  name: gstg-a
contexts:
- context:
    cluster: gstg-1
    user: gstg-1-gstg-1
  name: gstg-1-gstg-1
- context:
    cluster: gstg-a
    user: gstg-a-gstg-a
  name: gstg-a-gstg-a
current-context: ""
kind: Config
preferences: {}
users:
- name: gstg-1-gstg-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=gstg-1
      - --teleport-cluster=gstg-1
      - --proxy=someurl.com:3080
      command: /usr/local/bin/tsh
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: gstg-a-gstg-a
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=gstg-a
      - --teleport-cluster=gstg-a
      - --proxy=someurl.com:3080
      command: /usr/local/bin/tsh
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
