### ISSUE TITLE
Lens crashes when showing Cartographer's Workload

### ISSUE THREAD

**Issue by bennesp** [kontena/lens#5314]
**Describe the bug**
Trying to show the list of custom resources "Workload" by cartographer results in Lens crash

**To Reproduce**
1. Install [Cartographer's](https://cartographer.sh/) CRDs
2. Open Lens
3. Go to Custom Resources -> carto.run -> Workload

**Expected behavior**
A list of the available Workloads should be shown

**Screenshots**
<img width="1182" alt="Schermata 2022-05-03 alle 16 09 14" src="https://user-images.githubusercontent.com/5445545/166469113-91de9537-15f3-44e8-b349-fc86d7d6e44a.png">

**Environment (please complete the following information):**
- Lens Version: 5.4.6-latest.20220428.1
- OS: MacOS 12.3.1
- Installation method: brew cask

**Logs:**
No relevant logs are shown in the terminal when the error occurs. Only these are shown in the UI (as per screenshot):
```
Component stack:


    at ObserverComponent (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:100369:23)
    at div
    at wrappedComponent (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:100330:16)
    at div
    at div
    at List (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:453956:30)
    at div
    at AutoSizer (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:455270:5)
    at div
    at virtual_list_VirtualList (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:455429:9)
    at div
    at NonInjectedTable (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:180910:9)
    at Table
    at div
    at ItemListLayoutContent (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:136918:9)
    at div
    at NonInjectedItemListLayout (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:137205:9)
    at ItemListLayout
    at NonInjectedKubeObjectListLayout (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:61334:9)
    at KubeObjectListLayout
    at CrdResources (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:236985:9)
    at Route (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:71492:29)
    at Switch (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:71658:29)
    at ErrorBoundary (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:228295:9)
    at main
    at div
    at wrappedComponent (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:100330:16)
    at CustomResourcesRoute
    at Route (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:71492:29)
    at Switch (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:71658:29)
    at ErrorBoundary (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:228295:9)
    at div
    at div
    at NonInjectedMainLayout (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:296407:9)
    at ErrorBoundary (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:228295:9)
    at Router (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:71157:30)
    at NonInjectedClusterFrame (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/chunks/4.js:4225:9)
    at ThemeProvider (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:592771:24)
```

```
Error stack:

Error: Parse error on line 1:
$.spec.source[[object Object],[obj
--------------^
Expecting 'STAR', 'SCRIPT_EXPRESSION', 'INTEGER', 'ARRAY_SLICE', 'FILTER_EXPRESSION', 'QQ_STRING', 'Q_STRING', got '['
    at Parser.parseError (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:224092:15)
    at Parser.parser.yy.parseError (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:225292:17)
    at Parser.parse (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:224150:22)
    at JSONPath.nodes (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:225146:26)
    at JSONPath.query (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:225122:22)
    at JSONPath.value (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:225091:15)
    at http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:237046:52
    at Array.map (<anonymous>)
    at renderTableContents (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:237045:33)
    at ItemListLayoutContent.getTableRow (http://33de99dfd624bbda32dfc15e02c01203.localhost:63816/build/Lens.js:136932:13)
```

**Additional context:**
You can get the Workload CRD from the "spoiler" below or directly from the official link here: https://github.com/vmware-tanzu/cartographer/releases/latest/download/cartographer.yaml

<details>
  <summary>Expand to see the Workload CRD yaml</summary>
    
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: workloads.carto.run
spec:
  group: carto.run
  names:
    categories:
      - all
    kind: Workload
    listKind: WorkloadList
    plural: workloads
    shortNames:
      - wld
    singular: workload
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.source['git.url','image']
          name: Source
          type: string
        - jsonPath: .status.supplyChainRef.name
          name: SupplyChain
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].reason
          name: Reason
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: 'Spec describes the workload. More info: https://cartographer.sh/docs/latest/reference/workload/#workload'
              properties:
                build:
                  description: Build configuration, for the build resources in the supply chain
                  properties:
                    env:
                      description: Env is an array of environment variables to propagate to build resources in the supply chain. See https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
                      items:
                        description: EnvVar represents an environment variable present in a Container.
                        properties:
                          name:
                            description: Name of the environment variable. Must be a C_IDENTIFIER.
                            type: string
                          value:
                            description: 'Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".'
                            type: string
                          valueFrom:
                            description: Source for the environment variable's value. Cannot be used if value is not empty.
                            properties:
                              configMapKeyRef:
                                description: Selects a key of a ConfigMap.
                                properties:
                                  key:
                                    description: The key to select.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the ConfigMap or its key must be defined
                                    type: boolean
                                required:
                                  - key
                                type: object
                              fieldRef:
                                description: 'Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[''<KEY>'']`, `metadata.annotations[''<KEY>'']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.'
                                properties:
                                  apiVersion:
                                    description: Version of the schema the FieldPath is written in terms of, defaults to "v1".
                                    type: string
                                  fieldPath:
                                    description: Path of the field to select in the specified API version.
                                    type: string
                                required:
                                  - fieldPath
                                type: object
                              resourceFieldRef:
                                description: 'Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.'
                                properties:
                                  containerName:
                                    description: 'Container name: required for volumes, optional for env vars'
                                    type: string
                                  divisor:
                                    anyOf:
                                      - type: integer
                                      - type: string
                                    description: Specifies the output format of the exposed resources, defaults to "1"
                                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                    x-kubernetes-int-or-string: true
                                  resource:
                                    description: 'Required: resource to select'
                                    type: string
                                required:
                                  - resource
                                type: object
                              secretKeyRef:
                                description: Selects a key of a secret in the pod's namespace
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its key must be defined
                                    type: boolean
                                required:
                                  - key
                                type: object
                            type: object
                        required:
                          - name
                        type: object
                      type: array
                  type: object
                env:
                  description: Environment variables to be passed to the main container running the application. See https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
                  items:
                    description: EnvVar represents an environment variable present in a Container.
                    properties:
                      name:
                        description: Name of the environment variable. Must be a C_IDENTIFIER.
                        type: string
                      value:
                        description: 'Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".'
                        type: string
                      valueFrom:
                        description: Source for the environment variable's value. Cannot be used if value is not empty.
                        properties:
                          configMapKeyRef:
                            description: Selects a key of a ConfigMap.
                            properties:
                              key:
                                description: The key to select.
                                type: string
                              name:
                                description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                                type: string
                              optional:
                                description: Specify whether the ConfigMap or its key must be defined
                                type: boolean
                            required:
                              - key
                            type: object
                          fieldRef:
                            description: 'Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[''<KEY>'']`, `metadata.annotations[''<KEY>'']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.'
                            properties:
                              apiVersion:
                                description: Version of the schema the FieldPath is written in terms of, defaults to "v1".
                                type: string
                              fieldPath:
                                description: Path of the field to select in the specified API version.
                                type: string
                            required:
                              - fieldPath
                            type: object
                          resourceFieldRef:
                            description: 'Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.'
                            properties:
                              containerName:
                                description: 'Container name: required for volumes, optional for env vars'
                                type: string
                              divisor:
                                anyOf:
                                  - type: integer
                                  - type: string
                                description: Specifies the output format of the exposed resources, defaults to "1"
                                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                x-kubernetes-int-or-string: true
                              resource:
                                description: 'Required: resource to select'
                                type: string
                            required:
                              - resource
                            type: object
                          secretKeyRef:
                            description: Selects a key of a secret in the pod's namespace
                            properties:
                              key:
                                description: The key of the secret to select from.  Must be a valid secret key.
                                type: string
                              name:
                                description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                                type: string
                              optional:
                                description: Specify whether the Secret or its key must be defined
                                type: boolean
                            required:
                              - key
                            type: object
                        type: object
                    required:
                      - name
                    type: object
                  type: array
                image:
                  description: Image refers to a pre-built image in a registry. It is an alternative to specifying the location of source code for the workload. Specify one of `spec.source` or `spec.image`.
                  type: string
                params:
                  description: 'Additional parameters. See: https://cartographer.sh/docs/latest/architecture/#parameter-hierarchy'
                  items:
                    properties:
                      name:
                        description: Name of the parameter. Should match a blueprint or template parameter name.
                        type: string
                      value:
                        description: Value of the parameter.
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                      - name
                      - value
                    type: object
                  type: array
                resources:
                  description: Resource constraints for the application. See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      description: 'Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      description: 'Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                      type: object
                  type: object
                serviceAccountName:
                  description: "ServiceAccountName refers to the Service account with permissions to create resources submitted by the supply chain. \n If not set, Cartographer will use serviceAccountName from supply chain. \n If that is also not set, Cartographer will use the default service account in the workload's namespace."
                  type: string
                serviceClaims:
                  description: ServiceClaims to be bound through ServiceBindings.
                  items:
                    properties:
                      name:
                        type: string
                      ref:
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                        required:
                          - apiVersion
                          - kind
                          - name
                        type: object
                    required:
                      - name
                    type: object
                  type: array
                source:
                  description: The location of the source code for the workload. Specify one of `spec.source` or `spec.image`
                  properties:
                    git:
                      description: Source code location in a git repository.
                      properties:
                        ref:
                          properties:
                            branch:
                              type: string
                            commit:
                              type: string
                            tag:
                              type: string
                          type: object
                        url:
                          type: string
                      type: object
                    image:
                      description: OCI Image in a repository, containing the source code to be used throughout the supply chain.
                      type: string
                    subPath:
                      description: Subpath inside the Git repository or Image to treat as the root of the application. Defaults to the root if left empty.
                      type: string
                  type: object
              type: object
            status:
              description: 'Status conforms to the Kubernetes conventions: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties'
              properties:
                conditions:
                  description: 'Conditions describing this resource''s reconcile state. The top level condition is of type `Ready`, and follows these Kubernetes conventions: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties'
                  items:
                    description: "Condition contains details for one aspect of the current state of this API Resource. --- This struct is intended for direct use as an array at the field path .status.conditions.  For example, type FooStatus struct{ // Represents the observations of a foo's current state. // Known .status.conditions.type are: \"Available\", \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge // +listType=map // +listMapKey=type Conditions []metav1.Condition `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                    properties:
                      lastTransitionTime:
                        description: lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                        format: date-time
                        type: string
                      message:
                        description: message is a human readable message indicating details about the transition. This may be an empty string.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: status of the condition, one of True, False, Unknown.
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                        type: string
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase. --- Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be useful (see .node.status.conditions), the ability to deconflict is important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                observedGeneration:
                  description: ObservedGeneration refers to the metadata.Generation of the spec that resulted in the current `status`.
                  format: int64
                  type: integer
                resources:
                  description: Resources contain references to the objects created by the Supply Chain and the templates used to create them. It also contains Inputs and Outputs that were passed between the templates as the Supply Chain was processed.
                  items:
                    properties:
                      inputs:
                        description: Inputs are references to resources that were used to template the object in StampedRef
                        items:
                          properties:
                            name:
                              description: Name is the name of the resource in the blueprint whose output the resource consumes as an input
                              type: string
                          required:
                            - name
                          type: object
                        type: array
                      name:
                        description: Name is the name of the resource in the blueprint
                        type: string
                      outputs:
                        description: Outputs are values from the object in StampedRef that can be consumed by other resources
                        items:
                          properties:
                            digest:
                              description: Digest is a sha256 of the full value of the output
                              type: string
                            lastTransitionTime:
                              description: LastTransitionTime is a timestamp of the last time the value changed
                              format: date-time
                              type: string
                            name:
                              description: Name is the output type generated from the resource [url, revision, image or config]
                              type: string
                            preview:
                              description: Preview is a preview of the value of the output
                              type: string
                          required:
                            - digest
                            - lastTransitionTime
                            - name
                            - preview
                          type: object
                        type: array
                      stampedRef:
                        description: StampedRef is a reference to the object that was created by the resource
                        properties:
                          apiVersion:
                            description: API version of the referent.
                            type: string
                          fieldPath:
                            description: 'If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: "spec.containers{name}" (where "name" refers to the name of the container that triggered the event) or if no container name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future.'
                            type: string
                          kind:
                            description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                            type: string
                          namespace:
                            description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                            type: string
                          resourceVersion:
                            description: 'Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                            type: string
                          uid:
                            description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                            type: string
                        type: object
                      templateRef:
                        description: TemplateRef is a reference to the template used to create the object in StampedRef
                        properties:
                          apiVersion:
                            description: API version of the referent.
                            type: string
                          fieldPath:
                            description: 'If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: "spec.containers{name}" (where "name" refers to the name of the container that triggered the event) or if no container name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future.'
                            type: string
                          kind:
                            description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                            type: string
                          namespace:
                            description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                            type: string
                          resourceVersion:
                            description: 'Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                            type: string
                          uid:
                            description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                            type: string
                        type: object
                    required:
                      - name
                    type: object
                  type: array
                supplyChainRef:
                  description: SupplyChainRef is the Supply Chain resource that was used when this status was set.
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
  
</details>
