### ISSUE TITLE
Help adding a remote cluster (minikube)

### ISSUE THREAD

**Issue by esparig** [kontena/lens#5385]
Hello everyone, I have a remote minikube, and I follow this tutorial to be able to access it from local: 
https://faun.pub/accessing-a-remote-minikube-from-a-local-computer-fd6180dd66dd

I can access the Kubernes api using curl http://minikube:password@ip:port, and kubectl from terminal works just fine.
However, I can't get Lens working. It seems it doesn't support the use of user/password, if I remove it, it works, but I cannot leave the server unprotected.

I have Lens 5.4.6, but I also tried with 4.2.x.

Please, what could I do?

**Comment by Nokel81** [comment]
How does the kubeconfig look so that `kubectl` can use it?

**Comment by Nokel81** [comment]
Would a dev cluster help with your use case?

**Comment by esparig** [comment]
Here is my kubeconfig (password/ip has been removed):

```
apiVersion: v1
clusters:
- cluster:
    extensions:
    - extension:
        last-update: Wed, 11 May 2022 11:58:40 UTC
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: http://minikube:<password>@<ip>:8080
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 11 May 2022 11:58:40 UTC
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
```

I'm not sure what you mean by dev cluster.
