### ISSUE TITLE
Not able to see pods info for a k3s cluster created by multipass

### ISSUE THREAD

**Issue by hongbo-miao** [kontena/lens#5393]
**Describe the bug**

**To Reproduce**

Follow https://jyeee.medium.com/kubernetes-on-your-macos-laptop-with-multipass-k3s-and-rancher-2-4-6e9cbf013f58 to create a k3s cluster by multipass

```sh
multipass launch --name west-master
multipass exec k3s -- bash -c "curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE="644" sh -"
K3S_IP=$(multipass info k3s | grep IPv4 | awk '{print $2}')
multipass exec k3s sudo cat /etc/rancher/k3s/k3s.yaml > west-master-k3s.yaml
sed -i '' "s/127.0.0.1/${K3S_IP}/" west-master-k3s.yaml
export KUBECONFIG=${PWD}/west-master-k3s.yaml
```

At this point, you should be able to see all pods info by

```sh
kubectl get pods --all-namespaces

NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-58fb86bdfd-d9nrv   1/1     Running     0          3h27m
kube-system   metrics-server-6d684c7b5-8wzzq            1/1     Running     0          3h27m
kube-system   helm-install-traefik-gz7tb                0/1     Completed   0          3h27m
kube-system   svclb-traefik-4klm9                       2/2     Running     0          3h26m
kube-system   coredns-6c6bb68b64-66qw5                  1/1     Running     0          3h27m
kube-system   traefik-7b8b884c8-xlxdc                   1/1     Running     0          3h26m
```

Also, you have a **west-master-k3s.yaml** kubeconfig file which looks like 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://192.168.64.18:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```

**Expected behavior**

I imported the above **k3s.yaml** kubeconfig file, however, it only shows the cluster info, but the rest of pods, services, deployments, etc. are all empty.

**Screenshots**

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/3375461/168451535-5f138132-7cfc-4cc6-9bf0-5bb8f706a005.png">
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/3375461/168451584-1a71bac7-8fde-4a4e-ba6b-35a9966b8cf1.png">

**Environment (please complete the following information):**
- Lens Version: 5.4.6-latest.20220428.1
- OS: macOS 12.3.1
- Installation method (e.g. snap or AppImage in Linux):
