### ISSUE TITLE
Lens metrics not showing after k8s migration

### ISSUE THREAD

**Issue by imageschool** [kontena/lens#5410]
**Describe the bug**
Problem: Lens metrics not showing after k8s migration

Context:
I have recently migrated master node from on-prem to EC2 by using old master's etcd snapshot following below tutorial on RKE2.
- [Restoring a Snapshot to New Nodes](https://docs.rke2.io/backup_restore/#restoring-a-snapshot-to-new-nodes)

Seems like the overall cluster information is migrated & restored properly, however Lens Metrics are not showing!

I have tried followings
- Disabling & Enabling *prometheus Extensions - Lens Metrics - PROMETHEUS*
- Installing kube-prometheus-stack manually via helm chart

Please let me know how I can debug & fix this issue!

Thanks in advance!

**To Reproduce**

Migrate K8s master node using etcd snapshot & see metrics on Lens UI

**Expected behavior**
Metrics should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/29969006/168979282-53441554-0664-48d7-9daf-5b8e686c463d.png)
![image](https://user-images.githubusercontent.com/29969006/168979302-45fa5f21-0d0a-489e-93ea-0643364426c6.png)

**Environment (please complete the following information):**
- Lens Version: 
Lens: 5.4.6-latest.20220428.1
- OS: [e.g. OSX]
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Installation method (e.g. snap or AppImage in Linux):
Lens desktop

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *******
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: *******
    client-key-data: *******
```

**Additional context**
