### ISSUE TITLE
Pod Environment not accurate when using `envFrom` with `prefix`

### ISSUE THREAD

**Issue by Northburns** [kontena/lens#5425]
**Describe the bug**
I have a deployment with `env` and `envFrom` fields, the latter also has `prefix` specified. When examining the resulting pod in Lens, the Environment heading doesn't include these prefixes. [Link to the Kubernetes API on "EnvFromSource v1 core"](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#envfromsource-v1-core) for reference.

**To Reproduce**

Deploy the following two resources. My actual image is a Spring service, but I abridged the issue into this:

```yaml
apiVersion: v1
data:
  DATABASE: default
  HOST: localhost
  PORT: "5432"
kind: ConfigMap
metadata:
  name: rest-api-ds-6ttfh4mbk5
  namespace: foobar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rest-api
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(DS_HOST):$(DS_PORT)/$(DS_DATABASE)
        - name: SPRING_DATASOURCE_USERNAME
          value: $(DS_SECRET_username)
        - name: SPRING_DATASOURCE_PASSWORD
          value: $(DS_SECRET_password)
        envFrom:
        - configMapRef:
            name: rest-api-ds-6ttfh4mbk5
          prefix: DS_
        image: nginx:stable
        name: restapi
```

In Lens, open the resulting Pod, and examine the container's Environment header. It shows:

```txt
SPRING_DATASOURCE_PASSWORD: $(DS_SECRET_password)
SPRING_DATASOURCE_URL: jdbc:postgresql://$(DS_HOST):$(DS_PORT)/$(DS_DATABASE)
SPRING_DATASOURCE_USERNAME: $(DS_SECRET_username)
DATABASE: default
HOST: localhost
PORT: 5432
```

**Expected behavior**
The last three should be:

```txt
DS_DATABASE: default
DS_HOST: localhost
DS_PORT: 5432
```

I am not sure if the first three should be like this. I think it might be nice, but I can also understand if not.

```txt
SPRING_DATASOURCE_PASSWORD: $(DS_SECRET_password)
SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/default
SPRING_DATASOURCE_USERNAME: $(DS_SECRET_username)
```

I copied these values from the running container with clicking "Pod Shell" in the Pod pane, and running `env|sort`.

**Screenshots**
N/A

**Environment (please complete the following information):**
- Lens Version: 5.4.6
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): the default Windows installer

**Logs:**
N/A AFAIK

**Kubeconfig:**
N/A AFAIK

**Additional context**
None..
