### ISSUE TITLE
K8s cluster connectivity issue

### ISSUE THREAD

**Issue by kyle-bober** [kontena/lens#5440]
**Describe the bug**
Attempting to connect to K8s clusters in Lens. Worked fine until this morning and now when I attempt to connect to any of the clusters defined in the kubeconfig it fails to connect with the following errors (note the same kubeconfig works fine with 'kubectl' and vscode k8s extension):

could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

E0524 17:11:48.238040 95142 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable /usr/local/bin/aws-iam-authenticator failed with exit code 1

getting credentials: exec: executable /usr/local/bin/aws-iam-authenticator failed with exit code 1

**To Reproduce**
Verified that the Kubeconfig Syncs is using the correct Kubeconfig
Attempt to connect to cluster and get presented with the following:

could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

E0524 17:11:48.238040 95142 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable /usr/local/bin/aws-iam-authenticator failed with exit code 1

getting credentials: exec: executable /usr/local/bin/aws-iam-authenticator failed with exit code 1

**Expected behavior**
Successfully connect to the cluster as usual

**Environment (please complete the following information):**
- Lens Version: 5.4.6-latest.20220428.1
- OS: macOS Big Sur - Version: 11.6.5 (20G527)
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    extensions:
    - extension:
        manager:
          namespace: ambassador
      name: telepresence.io
    server: https://api.dev.net
  name: dev
contexts:
- context:
    cluster: dev
    namespace: default
    user: dev-user
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: dev-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - dev..net
      command: /usr/local/bin/aws-iam-authenticator
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
Note: the same kubeconfig works fine with 'kubectl' and vscode k8s extension
