### ISSUE TITLE
Lens 5.5.0 can't login with kubeconfig render by Rancher

### ISSUE THREAD

**Issue by ghost** [kontena/lens#5455]
**Describe the bug**

Login kubeconfig render by Rancher display error **`Invalid Credentail`** , and log  404 

**Environment (please complete the following information):**
- Lens Version: 5.5.0
- OS: Linux
- Installation method:  AppImage in Linux

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
StatusCodeError: 404 - {"paths":["/apis","/apis/","/apis/apiextensions.k8s.io","/apis/apiextensions.k8s.io/v1","/apis/apiextensions.k8s.io/v1beta1","/healthz","/healthz/etcd","/healthz/log","/healthz/ping","/healthz/poststarthook/crd-informer-synced","/healthz/poststarthook/generic-apiserver-start-informers","/healthz/poststarthook/priority-and-fairness-config-consumer","/healthz/poststarthook/priority-and-fairness-filter","/healthz/poststarthook/start-apiextensions-controllers","/healthz/poststarthook/start-apiextensions-informers","/livez","/livez/etcd","/livez/log","/livez/ping","/livez/poststarthook/crd-informer-synced","/livez/poststarthook/generic-apiserver-start-informers","/livez/poststarthook/priority-and-fairness-config-consumer","/livez/poststarthook/priority-and-fairness-filter","/livez/poststarthook/start-apiextensions-controllers","/livez/poststarthook/start-apiextensions-informers","/metrics","/openapi/v2","/readyz","/readyz/etcd","/readyz/informer-sync","/readyz/log","/readyz/ping","/readyz/poststarthook/crd-informer-synced","/readyz/poststarthook/generic-apiserver-start-informers","/readyz/poststarthook/priority-and-fairness-config-consumer","/readyz/poststarthook/priority-and-fairness-filter","/readyz/poststarthook/start-apiextensions-controllers","/readyz/poststarthook/start-apiextensions-informers","/readyz/shutdown","/version"]}
```

**Kubeconfig:**
Example config render by Rancher
```
apiVersion: v1
kind: Config
clusters:
- name: "global"
  cluster:
    server: "https://xxx.xxxx/k8s/clusters/c-jdxrh"

users:
- name: "global"
  user:
    token: "kubeconfig-user-zzzzz:t6vbvmdq9drzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"


contexts:
- name: "global"
  context:
    user: "global"
    cluster: "global"

current-context: "global"

```

**Comment by mrnonz** [comment]
Same as on macOS

**Comment by mrnonz** [comment]
Interim solution is back to use v5.4.6 instead.

Download https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1.dmg  and manual install by replace current version

**Comment by JuanRamino** [comment]
Same on windows.
Is there any place where download old binaries?

Thanks

**Comment by incubator4** [comment]
> https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1.dmg

Same issue and thanks for download url. Lens do not provide package in github release since version 3 or 4. 
There is no good plan to rollback to old version when bugs are found in the new version

**Comment by mrnonz** [comment]
> 

@JuanRamino For Windows let's try to link https://api.k8slens.dev/binaries/Lens%20Setup%205.4.6-latest.20220428.1.exe

**Comment by mrnonz** [comment]
And for Apple Silicon (ARM) try this link https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1-arm64.dmg

**Comment by incubator4** [comment]
I think the problem might cause by "paths" always check from root, but rancher cluster has proxy

**Comment by alanbchristie** [comment]
Just to confirm - this is my situation in #5460

My redacted config looks like this...

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://example.com
  name: xch
contexts:
- context:
    cluster: xch
    namespace: blah
    user: xch
  name: xch
current-context: xch
kind: Config
preferences: {}
users:
- name: xch
  user:
    token: kubeconfig-user-00000.c-00000:000000000000000000000
```

**Comment by mattn9x** [comment]
> > https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1.dmg
> 
> Same issue and thanks for download url. Lens do not provide package in github release since version 3 or 4. There is no good plan to rollback to old version when bugs are found in the new version

Thank you @incubator4 
I don't understand why Lens doesn't provide the old version so that users can come back.. Version 5.5.0 has a lot of bugs, specifically not working with rancher render kubeconfig

**Comment by glermaidt** [comment]
I can confirm that version 5.5.1-latest.20220526.1, while attempting to connect to a Rancher-created k8s cluster, this bug is present.  Same symptoms,errors.

**Comment by incubator4** [comment]
> > > https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1.dmg
> > 
> > 
> > Same issue and thanks for download url. Lens do not provide package in github release since version 3 or 4. There is no good plan to rollback to old version when bugs are found in the new version
> 
> Thank you @incubator4 I don't understand why Lens doesn't provide the old version so that users can come back.. Version 5.5.0 has a lot of bugs, specifically not working with rancher render kubeconfig

Maybe it just like a health check, a service without health check still runs, but a wrong setting might casue failure

**Comment by Nokel81** [comment]
Do you need a `certificate-authority-data` field in your `cluster` declaration in your `kubeconfig`?

**Comment by danielfree** [comment]
Confirmed same issue with latest version on mac os (m1) 5.5.2-latest.20220530.1

> Do you need a `certificate-authority-data` field in your `cluster` declaration in your `kubeconfig`?

No, we have multiple eks-based k8s and rke-based k8s all managed by rancher, all of them cannot connect.

Downgrade to https://api.k8slens.dev/binaries/Lens-5.4.6-latest.20220428.1-arm64.dmg fixed the problem for all clusters.

**Comment by vflaux** [comment]
With server: "https://xxx.xxxx/k8s/clusters/c-jdxrh", the requests are actually send to "https://xxx.xxxx/k8s/clusters/c-jdxrh/k8s/clusters/c-jdxrh". The path part of the server URL is duplicated.
So instead of querying "https://xxx.xxxx/k8s/clusters/c-jdxrh/version", it queries "https://xxx.xxxx/k8s/clusters/c-jdxrh/k8s/clusters/c-jdxrh/version"

**Comment by Nokel81** [comment]
@vflaux Thanks for that.

**Comment by Nokel81** [comment]
@vflaux How did you verify that? I have set up a local rancher setup and it doesn't seem like Lens is duplicating the server pathname.

**Comment by maxisam** [comment]
> insecure-skip-tls-verify: true

I got this error with this flag: 

failed to initialize proxyspecifying a root certificates file with the insecure flag is not allowed

**Comment by Nokel81** [comment]
@maxisam Do you need that flag?

**Comment by maxisam** [comment]
> alanbchristie

I added it based on [alanbchristie](https://github.com/alanbchristie)'s suggestion. Just trying to say that doesn't work for me.

**Comment by alanbchristie** [comment]
Yes, our cluster's "on prem" and currently has no certificate. So 'skip verify' is of use to us.

No problems connecting to any clusters with **k9s** btw.

**Comment by vflaux** [comment]
> @vflaux How did you verify that? I have set up a local rancher setup and it doesn't seem like Lens is duplicating the server pathname.

I'm not actually using rancher. I connect to eks clusters through a custom proxy (same code base as kubectl proxy).

I can reproduce the issue with kubectl proxy:

With a working context, run `kubectl proxy --api-prefix=/remote -v9` and import this kubeconfig in kubelens:
```
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8001/remote
  name: remote
contexts:
- context:
    cluster: remote
    user: user
  name: remote
current-context: remote
kind: Config
preferences: {}
users:
- name: user
```

You will get an "Invalid credentials" when connecting.
In the kubectl proxy logs you get: 
```
I0601 23:55:11.666753  368459 proxy_server.go:91] /remote/version matched ^.*
[...]
I0601 23:53:11.524546  368380 round_trippers.go:454] GET https://xxx.xxx/remote/version 404 Not Found in 27 milliseconds
```
It should be `https://xxx.xxx/version` instead of `https://xxx.xxx/remote/version`
If you run `kube proxy` without `--api-prefix` you can see more clearly in the logs that the pathname requested by kubelens is duplicated:
```
I0601 23:53:41.502589  368380 proxy_server.go:91] /remote/remote/version matched ^.*
[...]
I0601 23:53:41.529433  368380 round_trippers.go:454] GET https://xxx.xxx/remote/remote/version 404 Not Found in 26 milliseconds
```

Then if you run `kubectl proxy --api-prefix=/remote/remote` you will be able to connect to the cluster.
