### ISSUE TITLE
Suddenly no resources menu showing up after connecting to a cluster, just a black page

### ISSUE THREAD

**Issue by vovtz** [kontena/lens#5512]
**Describe the bug**
Suddenly a cluster I previously frequently interacted with through Lens, became inaccessible; at least GUI-wise.

Lens successfully connects, but the left side menu with resources is not shown for this cluster, so I cannot do anything (not choose between e.g. “Pods”, “Namespaces”, “Services”, etc.).

The console log reveals a lot of HTTP status 500 responses from the backend:

>BrowserConsole.js:47 [KUBE-API] watch (customresourcedefinition-7538) error response /apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=1488403 {status: 500}

From `kubectl` I am still able to see these resources on that same cluster, though.

BTW, a colleague on Windows has exactly the same problem, so not OS-related.

**To Reproduce**
1. Go to the particular cluster in the sidebar

**Expected behavior**
The menu of resources on the left side (next to the sidebar with cluster icons) should appear. (Or at least a clear error message that I can investigate further or act upon.)

**Screenshots**
![image](https://user-images.githubusercontent.com/1536228/171127894-7bd9a269-6158-4f3c-8db2-29dd6207bf8d.png)
![image](https://user-images.githubusercontent.com/1536228/171127978-2a444a41-67ef-4fc5-871e-cd6dcef19294.png)

**Environment (please complete the following information):**
- Lens Version: 5.5.1-latest.20220526.1
- OS: macOS, 10.15.7 (19H1922)
- Installation method (e.g. snap or AppImage in Linux): download (almost sure)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
/Applications/Lens.app/Contents/MacOS/Lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +2ms
info:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +17ms
info:    ▪ [EXTENSIONS-STORE]: LOADED from /Users/vovtz/Library/Application Support/Lens/lens-extensions.json +7ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +8ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/vovtz/Library/Application Support/Lens/lens-filesystem-provisioner-store.json +3ms
info:    ▪ 🚀 Starting Lens from "/Applications/Lens.app/Contents/MacOS/Lens" +8ms
info:    ▪ 🐚 Syncing shell environment +0ms
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```

apiVersion: v1
kind: Config
clusters:
- name: kube-test.internal.degiro.eu
  cluster:
    certificate-authority-data: LS…Cg==
    server: https://1.2.3.4:6443
contexts:
- name: default-context
  context:
    cluster: kube-test.internal.degiro.eu
    namespace: default
    user: rigid-admin
current-context: default-context
users:
- name: rigid-admin
  user:
    token: ey…1A
```

**Additional context**
