### ISSUE TITLE
Namespace error when upgrading a helm chart 

### ISSUE THREAD

**Issue by Startouf** [kontena/lens#5767]
**Describe the bug**
I am trying to upgrade a helm chart "cert-manager" that I had added to the namespace "cert-manager" from the UI

I get the following error message

> the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.

**To Reproduce**
1. Go to Lens > Helm > Releases
2. Click on a release, the upgrade
3. Select a higher version

**Expected behavior**
The helm chart should be upgraded in its namespace

**Screenshots**
<img width="1363" alt="Screenshot 2022-07-01 at 12 01 15" src="https://user-images.githubusercontent.com/7388889/176873247-33e7bc2a-1dcb-4e67-b510-cbb70bcb590f.png">

**Environment (please complete the following information):**
- Lens Version: Lens: 5.5.4-latest.20220609.2
- OS: macOs 12.3.1 (21E258)
- Installation method (e.g. snap or AppImage in Linux): manual download

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
cyrilduchon-doris@Cyril-DD-MacbookPro staging % cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX==
    server: https://XXX.yl4.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
- cluster:
    certificate-authority-data: XXX==
    server: https://XXX.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-production
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
    user: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
- context:
    cluster: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
    user: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
  name: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
current-context: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:xxx:cluster/mjg-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - mjg-dev
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:eu-central-1:xxx:cluster/mjg-production
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - mjg-production
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
