### ISSUE TITLE
pod shell is using current-context from .kube/config

### ISSUE THREAD

**Issue by jeremie-seguin** [kontena/lens#5783]
**Describe the bug**
When using open shell from a pod detail view, the shell is using my current-context from .kube/config instead of the cluster selected in lens.
If a pod with the same name in the same namespace exist in the cluster from  current-context, a shell will open on this pod. If not, the new shell is closed. 

**To Reproduce**
open lens 
open cluster A in lens
change the current-context with kubectx to cluster B
open a pod shell from a pod detail view in lens 

**Expected behavior**
Lens should in my opinion disregard my current-context and always use the selected cluster. 
my use case is the following: 
I have a staging cluster and a production cluster (same namespaces, same pod name), if my context is set to production and I open a shell from lens in staging, I end up on my production pod without knowing it.  

**Environment (please complete the following information):**
- Lens Version:
Lens: 5.5.4-latest.20220609.2
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0

- OS: macOS 12.4

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: --
    server: --
  name: production
- cluster:
    certificate-authority-data: --
    server: --
  name: staging
contexts:
- context:
    cluster: production
    user: production
  name: production
- context:
    cluster: staging
    user: staging
  name: staging
current-context: production
kind: Config
preferences: {}
users:
- name: production
  user:
    auth-provider:
      config:
        --
      name: gcp
- name: staging
  user:
    auth-provider:
      config:
        --
      name: gcp

```
