### ISSUE TITLE
Add VictoriaMetrics support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [kontena/lens#5837]
**What would you like to be added**:

Add prometheus endpoint as url: https://github.com/lensapp/lens/issues/337
![image](https://user-images.githubusercontent.com/46970457/179200288-604662cc-f6bd-4485-9ffe-af1c9453a40c.png)
![image](https://user-images.githubusercontent.com/46970457/179200298-596a7c53-3690-452c-8de7-29bc5c0019f8.png)
It has to be `/select/0/prometheus/api/v1/query_range?...` to work with Victoria Metrics

**Why is this needed**:
VictoriaMetrics has custom path for prometheus api

**Environment you are Lens application on:**
More dedtails: https://github.com/lensapp/lens/issues/337#issuecomment-1173153850

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by valyala** [comment]
The temporary workaround is to run VictoriaMetrics behind an http proxy such as nginx or [vmauth](https://docs.victoriametrics.com/vmauth.html),  which would route incoming requests from `/api/v1/*` to `/select/0/prometheus/api/v1/*` according to [url paths in VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format)

**Comment by b-a-t** [comment]
I was trying to look into the code to make OpenLens to work with my VM cluster, but out of a sudden it works out of the box O_O

@sergeyshaykhullin can you give a try the recent version? I have `OpenLens: 6.0.0-latest.1659305606594` to be exact and:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/1394818/195880039-4d26f4f1-09d8-4fee-8d1d-f1430779e2fc.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1394818/195879889-6027722b-235f-4291-8086-8c0a28b70899.png">

**Comment by sergeyshaykhullin** [comment]
I will try, i am using Helm/Helm 14 setup

**Comment by akaillidan** [comment]
little hack, how to connect to external cluster VM.
i use vmauth on my cluster, so i need nginx basic auth. 

So I create simple deployment and service nginx.

default.conf
```nginx
server {
  listen 80;

  set_real_ip_from 172.10.0.0/16;

  location / {
        proxy_ssl_server_name   on;
        proxy_ssl_name          $proxy_host;
        proxy_set_header        Host  vmselect.domain.com;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass              https://vmselect.domain.com/select/0/prometheus/;
        proxy_read_timeout      90;
        proxy_set_header        Authorization "Basic bG9naW46UGFzc3dvcmQK";
       # proxy_redirect          https://vmagent.domain.com/ https://vmselect.domain.com/select/0/prometheus/;
  }

  location /healthz {
        access_log off;
        return 200;
  }

}
```

deploy.yaml
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CI_PROJECT_NAME
  labels:
    app: CI_PROJECT_NAME
spec:
  selector:
    matchLabels:
      app: CI_PROJECT_NAME
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: CI_PROJECT_NAME
    spec:
      containers:
      - name: CI_PROJECT_NAME
        image: CI_IMAGE_REPOSITORY
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 2
      imagePullSecrets:
      - name: CI_GITHUB_REGISTRY
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: CI_PROJECT_NAME
  name: CI_PROJECT_NAME
spec:
  ports:
  - name: CI_PROJECT_NAME
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: CI_PROJECT_NAME
  sessionAffinity: None
  type: ClusterIP
```

> bG9naW46UGFzc3dvcmQK - base64 (`echo -n "login:Password" | base64`)


then we can connect with option `Helm` and for example `prometheus/vmselect-nginx-proxy:80`

**Comment by partymaker-py** [comment]
@akaillidan you saved me a few hours. Thanks a lot!

**Comment by perfectra1n** [comment]
Just adding my 2c here, when using VMsingle, you just need to specify the following:
![image](https://github.com/lensapp/lens/assets/2390633/3c292f9b-4e58-47c9-b45a-9403ee1303d3)

```yaml
monitoring/vmsingle-victoria-metrics-single-server:8428
<vmsingle_namespace>/<vmsingle_service>:8428
```

**Comment by vainkop** [comment]
None of this works with VM cluster. 
@valyala do by any chance you have any workaround for VM cluster?

**Comment by valyala** [comment]
@vainkop , you can use the following [vmauth](https://docs.victoriametrics.com/vmauth/) config for proxying `/api/v1/*` requests to [tenant](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy) `0` at vmselect according to [url format in VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#url-format):

```yaml
unauthorized_user:
  url_map:
  - src_paths: ["/api/v1/.+]
    url_prefix:
    - http://vmselect-1:8481/select/0/prometheus/
    - http://vmselect-2:8481/select/0/prometheus/
```

See more details [here](https://docs.victoriametrics.com/vmauth/#use-cases).

**Comment by roberto-iannone-riatlas** [comment]
Try to use **vm/vm-select:8481//select/0/prometheus/** it works for me

**Comment by vainkop** [comment]
> Try to use **vm/vm-select:8481//select/0/prometheus/** it works for me

The `//` in your `vm/vm-select:8481//select/0/prometheus/` is a typo?
Are you using VM cluster, not VM single?

**Comment by vainkop** [comment]
> @vainkop , you can use the following [vmauth](https://docs.victoriametrics.com/vmauth/) config for proxying `/api/v1/*` requests to [tenant](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy) `0` at vmselect according to [url format in VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#url-format):
> 
> ```yaml
> unauthorized_user:
>   url_map:
>   - src_paths: ["/api/v1/.+]
>     url_prefix:
>     - http://vmselect-1:8481/select/0/prometheus/
>     - http://vmselect-2:8481/select/0/prometheus/
> ```
> 
> See more details [here](https://docs.victoriametrics.com/vmauth/#use-cases).

I will try that. It's weird that smth like that is needed while it works for VM single without a need for any proxy & I have only 1 tenant anyways.

Also why do I need to specify 2 vmselect if I have a single k8s service which has 2 endpoints? Shouldn't I specify just the k8s service?

Btw I'm using the following helm chart (but for v1.97): 
https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-k8s-stack-0.18.12/charts/victoria-metrics-k8s-stack/values.yaml
```
vmcluster:
  enabled: true
  annotations: {}

  spec:
    retentionPeriod: "14"
    replicationFactor: 2

    vmstorage:
      image:
        tag: v1.97.1-cluster
      replicaCount: 2
      storageDataPath: "/vm-data"

      extraArgs:
        dedup.minScrapeInterval: "10s"

      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 200Gi

      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
        limits:
          cpu: "4"
          memory: "4Gi"

    vmselect:
      image:
        tag: v1.97.1-cluster

      replicaCount: 2
      cacheMountPath: "/select-cache"

      extraArgs:
        dedup.minScrapeInterval: "10s"

      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi

      resources:
        requests:
          cpu: "1"
          memory: "500Mi"
        limits:
          cpu: "1"
          memory: "1Gi"

    vminsert:
      image:
        tag: v1.97.1-cluster
      replicaCount: 2

      extraArgs:
        maxLabelsPerTimeseries: "50"

      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
```
It seems that I need to use a separate chart to install VM auth though, while it would be logical to be able to enable it in this one...

**Comment by vainkop** [comment]
> > @vainkop , you can use the following [vmauth](https://docs.victoriametrics.com/vmauth/) config for proxying `/api/v1/*` requests to [tenant](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy) `0` at vmselect according to [url format in VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#url-format):
> > ```yaml
> > unauthorized_user:
> >   url_map:
> >   - src_paths: ["/api/v1/.+]
> >     url_prefix:
> >     - http://vmselect-1:8481/select/0/prometheus/
> >     - http://vmselect-2:8481/select/0/prometheus/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See more details [here](https://docs.victoriametrics.com/vmauth/#use-cases).

That helped, thank you @valyala !

I've installed VM auth using [this](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-auth) chart 0.4.7
+
```
config:
  unauthorized_user:
    url_map:
    - src_paths:
      - "/api/v1/.+"
      url_prefix:
      - "http://vmselect-vm:8481/select/0/prometheus/"
```
& in Lens:
`Prometheus Operator`
&
`monitoring/vm-auth:8427`
![image](https://github.com/lensapp/lens/assets/28118190/850f4a3d-5fc1-45ce-8630-943e9eafb840)

Also I've upgraded VictoriaMetrics cluster to 1.99
![image](https://github.com/lensapp/lens/assets/28118190/bf86a5ba-2128-435e-93c0-ab7134a96019)

**Comment by roberto-iannone-riatlas** [comment]
> > Try to use **vm/vm-select:8481//select/0/prometheus/** it works for me
> 
> The `//` in your `vm/vm-select:8481//select/0/prometheus/` is a typo? Are you using VM cluster, not VM single?

No it is not a typo .. it is a trick ;) ... I'm using VM cluster and it works fine .. the double '/' act as an escape allowing lens to make the correct query

**Comment by genki** [comment]
I had tried using vmsingle but no request comes from the Lens even if set the service address to `default/vmsingle-victoria-metrics-single-server:8428/prometheus`. I am using Lens: 2024.7.161041-latest.
The latest version omited this feature?

**Comment by fatsolko** [comment]
> > > Try to use **vm/vm-select:8481//select/0/prometheus/** it works for me
> > 
> > 
> > The `//` in your `vm/vm-select:8481//select/0/prometheus/` is a typo? Are you using VM cluster, not VM single?
> 
> No it is not a typo .. it is a trick ;) ... I'm using VM cluster and it works fine .. the double '/' act as an escape allowing lens to make the correct query

Thank you very much! It helps

**Comment by vadim-a-nesterov** [comment]
+100
just please add under pop-down the type Victoria Metrics and a new field URL

**Comment by vadim-a-nesterov** [comment]
+100
just please add in settings under Metrics
Metric source - Victoria Metrics
 and new field URL

OR 

Metric source - Prometheus
Prometheus - Victoria Metrics 
 and new field URL

**Comment by ClementGautier** [comment]
> > The `//` in your `vm/vm-select:8481//select/0/prometheus/` is a typo? Are you using VM cluster, not VM single?
> 
> No it is not a typo .. it is a trick ;) ... I'm using VM cluster and it works fine .. the double '/' act as an escape allowing lens to make the correct query

-> This workaround doesn't work anymore (Version `Lens: 2024.11.261604-latest`). Any idea how to make this work again?

**Comment by micw** [comment]
I made it work by deploying victoria-metrics-auth along with victoria-metrics-k8s-stack (because there's no way to set labels on the vmauth service created by victoria-metrics-k8s-stack.

Here are my values I used for victoria-metrics-auth:

```
service:
  extraLabels:
      operated-prometheus: "true"
      self-monitor: "true"
config:
  unauthorized_user:
    url_map:
    - src_paths: ["/api/v1/.+"]
      url_prefix:
      - http://vmsingle-victoriametrics:8429/prometheus/
```

The labels are required to make Lens' auto-detection work. The config maps directly to my vmsingle instance. Works well with Lens.

Edit: created a feature request on vm charts to get rid of this extra deployment.
