### ISSUE TITLE
Can't connect to clusters (with OIDC)

### ISSUE THREAD

**Issue by emmedema** [kontena/lens#5976]
**Describe the bug**

I am trying to connect to my company's Kubernetes clusters from my work laptop. All works fine via command line (`kubectl ...`) and via `k9s`, but I cannot get Lens to work.

When I try to connect to any of my configured clusters, I get the errors I describe below:
* either the `kubectl` executable is not found
* or some plugins are not found (`oidc-login`)

I also tried to specify the path of `kubectl` explicitly in Settings: `/usr/bin/kubectl`, but that made no difference.

I am not sure what exactly the problem could be, but it almost looks like something related to loading the shell profile is a bit broken, because, as I mentioned, everything works via Command Line (and k9s launched via command line). 

Also, I see this at the start of my logs:
```
error:   ▪ shellEnv: Error: Resolving shell environment is taking very long. Please review your shell configuration.
```

**To Reproduce**
I am not sure how to make this reproducible to someone else, but for me, it happens every single time I try to connect to a cluster.

**Expected behavior**
I would expect to be able to connect to the cluster fine, given that:
* I can user `kubectl` via CLI and it works perfectly fine
* I can use `k9s` and it works perfectly fine

**Environment (please complete the following information):**
- Lens Version: latest 6.0.0-latest.20220728.2, but it was happening in all 5.x I tried
- OS: Ubuntu 20.04 
- Installation method: downloaded the `.deb` from the webpage
- I use ZSH (with Oh-My-Zsh)
- I tried to execute the `lens` executable both from command line (both from `bash` or `zsh`) and from the window manager

**Logs:**
This is the error I can see in the log:
```
error:   ▪ [CLUSTER]: Failed to connect to "citi": StatusCodeError: 500 - "getting credentials: exec: executable kubectl not found\n\nIt looks like you are trying to use a client-go credential plugin that is not installed.\n\nTo learn more about this feature, consult the documentation available at:\n      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins\n"
```

**Kubeconfig:**
```
- name: cel-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=....
      - --oidc-client-id=cel-1
      - --oidc-client-secret=.....
      - --oidc-extra-scope=email
      - --oidc-extra-scope=groups
      - --listen-address=127.0.0.1:18000
      command: kubectl
      env: []
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
I also tried to change the `kubeconfig` to use `command: /usr/bin/kubectl`, and the error message change to:

```
error:   ▪ [CLUSTER]: Failed to connect to "develop": StatusCodeError: 500 - "getting credentials: exec: executable /usr/bin/kubectl failed with exit code 1\n" +71ms
```

And it looks like this in the UI:
![error](https://user-images.githubusercontent.com/3448206/182621744-6fcdc1db-7318-411e-adc4-39664b5b9a1f.png)
