### ISSUE TITLE
Error connecting to cluster

### ISSUE THREAD

**Issue by PBonnema** [kontena/lens#6027]
**Describe the bug**
I have several contexts defined. Connecting to one of them gives the following:

```
Component stack:
    at wrappedComponent (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:10507:16)
    at div
    at Logs (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/chunks/5.js:7280:9)
    at div
    at div
    at Dock (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/chunks/5.js:7712:9)
    at div
    at div
    at MainLayout (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:286661:9)
    at ErrorBoundary (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:238009:9)
    at Router (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:79008:30)
    at ClusterFrame (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/chunks/5.js:7940:9)
    at ThemeProvider (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:609896:24)
Error stack:

TypeError: Cannot create a KubeObject from undefined
    at new KubeObject (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:32700:19)
    at new WorkloadKubeObject (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:124916:1)
    at new Pod (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:154152:9)
    at http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/chunks/5.js:7212:17
    at http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:10507:49
    at http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:10471:25
    at trackDerivedFunction (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:3120:18)
    at Reaction.track (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:3649:18)
    at useObserver (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:10469:14)
    at wrappedComponent (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:10507:16)
    at Ch (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556484:137)
    at li (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556507:154)
    at ki (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556505:169)
    at ii (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556504:178)
    at ck (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556601:126)
    at bk (http://7200cf4aaac788486beee2509b726a3a.localhost:59560/build/Lens.js:556577:347)
```

I each context points to a different cluster except for 3. These 3 use the same cluster, but a different default namespace. 2 of the 3 can connect. The last one gives the above error. Restarting Lens doesn't help. All clusters are managed clusters at my company. I'm reading all context info from ~/.kube/config. The only settings I changed in Lens itself is that I gave the contexts a custom name. Connecting to the same context using other tools such as Kubenav works.

**To Reproduce**
1. Add the contexts to ~/.kube/config
2. Connect to the euwest-aks-one-dev context
3. The error appears

Obviously, the above means no one, outside of my organization, will be able to reproduce this error....

**Expected behavior**
I wanted to see the cluster details like the running pods.

**Screenshots**
![image](https://user-images.githubusercontent.com/3737630/184313071-de76b54d-e483-49bf-b51d-35814df01881.png)

**Environment (please complete the following information):**
- Lens Version:
![image](https://user-images.githubusercontent.com/3737630/184313099-5a34af42-32c2-4a1b-b982-5dba0261a4bf.png)

- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): downloaded .exe (got it from someone in the organization as I cannot download .exes directly due to company policy)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
C:\Program Files\Lens>
info:    Γû¬ ≡ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Γû¬ ≡ƒôƒ Protocol client register succeeded Γ£à +1ms
info:    Γû¬ [APP-PATHS]: initializing +1ms
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxx
    server: https://eu41d-one-xxxxxxx.hcp.westeurope.azmk8s.io:443
  name: euwest-aks-one-dev
- cluster:
    certificate-authority-data: xxxxxxxx
    server: https://eu41p-one-xxxxxxx.hcp.westeurope.azmk8s.io:443
  name: euwest-aks-one-prod
- cluster:
    certificate-authority-data: xxxxxxxx
    server: https://eu41t-one-xxxxxx.hcp.westeurope.azmk8s.io:443
  name: euwest-aks-one-test
- cluster:
    certificate-authority-data: xxxxxxxx
    server: https://eu41p-onesim-xxxxxx.hcp.westeurope.azmk8s.io:443
  name: euwest-aks-onesim-prod
- cluster:
    certificate-authority: C:\Users\XPETB\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Tue, 09 Aug 2022 14:17:29 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://127.0.0.1:61672
  name: minikube
contexts:
- context:
    cluster: euwest-aks-one-dev
    namespace: ssoc
    user: xpetb@xxxxx.com
  name: euwest-aks-one-dev
- context:
    cluster: euwest-aks-one-prod
    namespace: ssoc
    user: xpetb@xxxxxx.com
  name: euwest-aks-one-prod
- context:
    cluster: euwest-aks-one-dev
    namespace: ssocpoc
    user: xpetb@xxxxxx.com
  name: euwest-aks-one-ssocpoc
- context:
    cluster: euwest-aks-one-dev
    namespace: ssocred
    user: xpetb@xxxxx.com
  name: euwest-aks-one-ssocred
- context:
    cluster: euwest-aks-one-test
    namespace: ssoc
    user: xpetb@xxxxx.com
  name: euwest-aks-one-test
- context:
    cluster: euwest-aks-onesim-prod
    namespace: ssoc
    user: xpetb@xxxxx.com
  name: euwest-aks-onesim-prod
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 09 Aug 2022 14:17:29 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: ssoc
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: clusterUser_ssocpoc-rg_aks-ssocpoc
  user:
    client-certificate-data: xxxxxxxx
    client-key-data: xxxxxxx
    token: xxxxxxx
- name: minikube
  user:
    client-certificate: C:\Users\XPETB\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\XPETB\.minikube\profiles\minikube\client.key
- name: xpetb@xxxxxx.com
  user:
    auth-provider:
      config:
        access-token: xxxxxxx
        apiserver-id: 9588c574-feb3-457c-a69b-78ae4504fa2f
        client-id: c3e99fbd-e77b-407a-a4e4-93110c07e399
        config-mode: "0"
        environment: AzurePublicCloud
        expires-in: "4817"
        expires-on: "1660294318"
        refresh-token: xxxxxx
        tenant-id: 48794f31-2f6d-4909-8b2f-53b64c7f3199
      name: azure

```

**Additional context**
Renaming the euwest-aks-one-dev context in the kube config file and restarting lens seems to fix it. Renaming it back to the original name breaks it again.
