### ISSUE TITLE
Not able to import cluster in Lens

### ISSUE THREAD

**Issue by Ankur012** [kontena/lens#6061]
I have 4 clusters in the config file and when I am trying to add in the lens, it shows a notification "Selected item has been added to kubeconfig sync ". After that no cluster was added in the lens, So i am not able to use Lens. 

Not sure what additional info I can put here, Let me know if I missed some info I will share the required info.

**Screenshots**
<img width="1262" alt="Screenshot 2022-08-19 at 2 05 31 PM" src="https://user-images.githubusercontent.com/12594345/185582631-5d2b8c56-0f49-48de-843e-e3ebd4e70197.png">

**Environment (please complete the following information):**
- Lens Version: 6.0.1-latest.20220810.2
- OS:  OSX 
- Installation method : AppImage

**Kubeconfig:**
```
apiVersion: v1
kind: Config
clusters:
  - name: arn:aws:eks:us-west-2:12345678:cluster/dev-ekscluster
    cluster:
      server: https://0000000000000.sk1.us-west-2.eks.amazonaws.com
      certificate-authority-data: >-
        <dbakdbakjsdbjkbdajkbdakjsdbkjdbjkgreuwirgewurq>
      insecure-skip-tls-verify: false
  - name: arn:aws:eks:us-west-2:12345678:cluster/qa-ekscluster
    cluster:
      server: https://0000000000000.us-west-2.eks.amazonaws.com
      certificate-authority-data: >-
        <dbakdbakjsdbjkbdajkbdakjsdbkjdbjkgreuwirgewurq>
      insecure-skip-tls-verify: false
  - name: arn:aws:eks:us-west-2:12345678:cluster/sbx-ekscluster
    cluster:
      server: https://0000000000000.us-west-2.eks.amazonaws.com
      certificate-authority-data: >-
        <dbakdbakjsdbjkbdajkbdakjsdbkjdbjkgreuwirgewurq>
      insecure-skip-tls-verify: false
  - name: arn:aws:eks:us-west-2:12345678:cluster/prd-ekscluster
    cluster:
      server: https://0000000000000.us-west-2.eks.amazonaws.com
      certificate-authority-data: >-
        <dbakdbakjsdbjkbdajkbdakjsdbkjdbjkgreuwirgewurq>
      insecure-skip-tls-verify: false
users:
  - name: arn:aws:eks:us-west-2:12345678:cluster/dev-ekscluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - '--region'
          - us-west-2
          - eks
          - get-token
          - '--cluster-name'
          - dev-ekscluster
        command: aws
        env:
          - name: AWS_PROFILE
            value: dev
  - name: arn:aws:eks:us-west-2:12345678:cluster/qa-ekscluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - '--region'
          - us-west-2
          - eks
          - get-token
          - '--cluster-name'
          - qa-ekscluster
        command: aws
        env:
          - name: AWS_PROFILE
            value: qa
  - name: arn:aws:eks:us-west-2:12345678:cluster/sbx-ekscluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - '--region'
          - us-west-2
          - eks
          - get-token
          - '--cluster-name'
          - sbx-ekscluster
        command: aws
        env:
          - name: AWS_PROFILE
            value: sbx
  - name: arn:aws:eks:us-west-2:12345678:cluster/prd-ekscluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - '--region'
          - us-west-2
          - eks
          - get-token
          - '--cluster-name'
          - prd-ekscluster
        command: aws
        env:
          - name: AWS_PROFILE
            value: prod
contexts: []
preferences: {}
current-context: arn:aws:eks:us-west-2:12345678:cluster/prd-ekscluster
```
