### ISSUE TITLE
Incorrect path resolution in Windows Lens when using kubeconfig under WSL

### ISSUE THREAD

**Issue by asampal** [kontena/lens#6106]
**Describe the bug**
When the Windows desktop Lens is pointed to a kubeconfig under WSL (v2 in my case), the determination of the client cert file path is done incorrectly, resulting in a non-existent path.

**To Reproduce**
1. Install the Windows desktop version of Lens
2. Install Docker, minikube, kubectl under WSL
3. In Lens, sync the .kube folder under WSL (using the Windows path to it), e.g. `\\wsl.localhost\Ubuntu\home\<wlsuser>\.kube`
4. Attempt to open the minikube cluster
5. See error `F0825 13:18:21.639940 4840 main.go:74] failed to initialize kubeconfiginvalid configuration: [unable to read client-cert \\wsl.localhost\Ubuntu\home\<wsluser>\.kube\home\<wsluser>\.minikube\profiles\minikube\client.crt for minikube due to open \\wsl.localhost\Ubuntu\home\<wsluser>\.kube\home\<wsluser>\.minikube\profiles\minikube\client.crt: The system cannot find the path specified., unable to read client-key`

**Expected behavior**
The cluster should open in Lens

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.0.1
- OS: Windows 11 Pro

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/<wsluser>/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 19 Aug 2022 16:39:08 EDT
        provider: minikube.sigs.k8s.io
        version: v1.26.0
      name: cluster_info
    server: https://127.0.0.1:49154
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 19 Aug 2022 16:39:08 EDT
        provider: minikube.sigs.k8s.io
        version: v1.26.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/<wsluser>/.minikube/profiles/minikube/client.crt
    client-key: /home/<wsluser>/.minikube/profiles/minikube/client.key

```

**Additional context**
You can see that the problem here is the incorrect handling of the paths that are involved. We have a Windows path (to where the kubeconfig is found), and a Linux absolute path to the client cert in the kubeconfig. The resolved path to the client cert is assumed to be the absolute path to the kubeconfig directory concatenated with what is assumed to be a relative path to the client cert.

What should happen here is that if kubeconfig is determined to be under WSL, then the client cert path specified there should be converted to a Windows path using something like `wslpath` to obtain, in my case `\\wsl.localhost\Ubuntu\home\<wlsuser>\.minikube\profiles\minikube\client.crt` (and this should not be appended to anything).
