### ISSUE TITLE
Lens not displaying multiple metrics values on HPA correctly

### ISSUE THREAD

**Issue by ben5556** [kontena/lens#6110]
**Describe the bug**
Lens not displaying multiple metrics values on HPA correctly. Showing same values for both metrics

**To Reproduce**
1. Configure multiple metrics on HPA. My config as below

```
metrics:
  - type: External
    external:
      metric:
        name: app_horizon_current_workload
        selector:
          matchLabels:
            queue: "feed-check"
      target:
        type: Value
        value: 50k
  - type: External
    external:
      metric:
        name: app_horizon_current_workload
        selector:
          matchLabels:
            queue: "parser"
      target:
        type: Value
        value: 200k
```
        
2. Go to Lens > EKS cluster > Config > HPA
3. Check values reported for both metrics

**Expected behavior**
Both metrics show their respective correct values.

**Actual behavior**
Both metrics showing same values. The value shown is for one of the metrics.

**Screenshots**
<img width="695" alt="image" src="https://user-images.githubusercontent.com/39107453/186823960-0f124f26-cd3c-4b66-beac-59c5af6ad21c.png">

**Environment (please complete the following information):**
- Lens Version: 6.0.1-latest.20220810.2
- OS: macOS Catalina 10.15.7
