### ISSUE TITLE
6.0.2 not grabbing prometheus operator metrics

### ISSUE THREAD

**Issue by evanrich** [kontena/lens#6222]
**Describe the bug**
I know this is a bug that comes up a lot because I find numerous results in google for it for past versions.

Fresh install of 6.0.2, pointing at a 1.25.0 microk8s cluster (3 nodes) running the kube-prometheus-stack helm chart ( v 39.11).  All pods up and running, prometheus is accessabile via service IP  (x.x.x.x:9090), and prometheus-operated service is running as well.  Lens will not show any cluster metrics.  
![image](https://user-images.githubusercontent.com/518320/189426233-5185d245-9d91-4900-b3e4-8f3dbf2811b7.png)

I've tried manually setting the metrics service and port as follows:
![image](https://user-images.githubusercontent.com/518320/189426350-9651b053-0ccd-44d2-9453-24c3d8cf65e5.png)
but no change.

**To Reproduce**
1.) Add cluster
2.) configure metric endpoint by hand (auto doesnt work)
3.)...
4.) profit

**Expected behavior**
Metrics show up

**Screenshots**
I see additional weirdness like this:
![image](https://user-images.githubusercontent.com/518320/189427332-e40337d0-fc72-403c-a327-eaf26ed71fe3.png)
yet I'm fully able to look at pods, logs, namespaces, restart pods, view secrets, etc.

**Environment (please complete the following information):**
- Lens Version: 6.0.2
- OS: windows 11 for lens, ubuntu 22.04.1 for nodes
- Installation method (e.g. snap or AppImage in Linux): Install from exe.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: supsdlfkajs;dflkasjdf;laksdjf;alsdkjfa;sldkfjaslkdjfhasdlkjfhasdlkjfahsdlkfjahsdlfkjashdflkajsdhflaksdjhfasldkjfhasdlkjfhasdlkfjahsdlfkjashdflkajsdhflaksjdhfaskljdfhasdlkjfhasldkfjhas
    server: https://192.168.5.2:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: ItsAT0K3nBabY
```

kubeconfig pulled from my admin user that has full access to all resources in the cluster.

Thanks!
