### ISSUE TITLE
kube-prometheus-stack integration after updating version 40.X

### ISSUE THREAD

**Issue by cduv** [kontena/lens#6282]
**Describe the bug**
After updating kube-prometheus stack from version 39.x to version 40.x the cpu values are not drawn on lens capacity graphs.

**To Reproduce**
1. Prepare a k8s and install kube-prometheus-stack using helm  version 39.X
2. Apply lens configuration following https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md#kube-prometheus
3. Update kube-prometheus stack helm chart to last version and update k8s cluster to version 40.X.
4. Apply the CRDs updated in the helm chart update 39.X to 40.X https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-39x-to-40x
5. Go to cluster view to see the missing cpu values (see screenshots)

**Expected behavior**
See the cpu values

**Screenshots**
After upgrading kube-prometheus-stack to 40.X:
![image](https://user-images.githubusercontent.com/16380/191363438-f5581e95-75fc-4e74-b331-7259b0703439.png)

Previously using a cluster with kube-prometheus-stack 39.x:
![image](https://user-images.githubusercontent.com/16380/191363570-c7f0bb82-29c6-4597-9c3e-e7dfe8ec3825.png)

**Environment (please complete the following information):**
- Lens Version:2022.9.201328-latest
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Mac download and installer
- Kubernetes 1.23.9 (both clusters)
- EKS

**Logs:**

**Kubeconfig:**

**Additional context**
There is an information in the kube-prometheus-stack about changes in labels https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-39x-to-40x

>Starting from prometheus-node-exporter version 4.0.0, the node exporter chart is using the [Kubernetes recommended labels]>>(https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). Therefore you have to delete the daemonset before you upgrade.

Maybe this is related to the problem. Do we have to change the configuration? 

Thanks for the help

Genís

**Comment by cduv** [comment]
The problem seems to be solved by doing:

1) Updating to the last version of kube-prometheus-stack

2) Changing the configuration to:

```
kubelet:
  serviceMonitor:
    metricRelabelings:
    - action: replace
      sourceLabels:
      - node
      targetLabel: app.kubernetes.io/instance

nodeExporter:
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: app.kubernetes.io/instance
```
But I tested this configuration days ago without success, and  I think that the key has been the update of the helm chart today.

3) Also updated lens to the last version

Now I can see:

![image](https://user-images.githubusercontent.com/16380/193424856-44ceca91-9fee-4a1f-b96d-deb6352047bd.png)
![image](https://user-images.githubusercontent.com/16380/193424880-beb3c82f-c640-40fb-8c9d-94556a3aea2a.png)

Looks solved, but I'm not sure what made it work. Can someone confirm the same result.

Thanks
