### ISSUE TITLE
Unable to login to the cluster

### ISSUE THREAD

**Issue by arnabnandy1706** [kontena/lens#6323]
I am trying to connect to the EKS cluster and it gives an error **Unknown Error Occurred**.
Even though I am able to connect to the cluster using `kubectl` command.

**Screenshots**
<img width="721" alt="Screenshot 2022-10-05 at 11 33 08" src="https://user-images.githubusercontent.com/38555334/194029672-bc252214-d92a-4635-b66d-4cbe612e5ee5.png">

**Environment (please complete the following information):**
- Lens Version: 2022.9.280635-latest
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Downloading .dmg file

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiB*****************mlZZ2NkNUZab3dRVklEcEhjS04KQjI4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://DRT128738723897GFHHGHA.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
    user: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
  name: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
current-context: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:9238743893982107:cluster/cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - cluster-name
      command: aws
```
