### ISSUE TITLE
insecure-skip-tls-verify is supposed to be allowed but it isn't

### ISSUE THREAD

**Issue by scaleoutsean** [kontena/lens#6383]
**Describe the bug**

Comment in issue [#52](https://github.com/lensapp/lens/issues/52#issuecomment-549517684) indicates that `insecure-skip-tls-verify: true` is supported but that doesn't seem to be the case.

**To Reproduce**

1. Add a config file from remote k3s cluster, change 127.0.0.1:6443 to external IP
2. Click to connect
3. Observe X.509 error
4. Enable `insecure-skip-tls-verify: true`, observe `insecure flag is not allowed` error

**Expected behavior**

Lens connects to cluster.

**Screenshots**

![image](https://user-images.githubusercontent.com/16622642/194804015-e7e631b6-b931-44bd-b838-26bf95605447.png)

**Environment:**

- Lens Version: 2022.9.280365
- OS: Mint 20.3 
- Installation method: .deb

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

- Without TLS verify disabled:

```
E1010 13:38:09.003819 1439937 proxy_server.go:147] Error while proxying request: x509: certificate signed by unknown authority

x509: certificate signed by unknown authority

Unknown error has occurred
```

- With TLS verify disabled:

```
F1010 13:39:12.595629 1440064 main.go:82] failed to initialize proxyspecifying a root certificates file with the insecure flag is not allowed

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1140 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2d2a1a0, 0x3, 0x0, 0xc0001a5420, 0x1, {0x225cb7d, 0x20}, 0xc000078c00, 0x0)
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1088 +0x66f
k8s.io/klog/v2.(*loggingT).printDepth(0xc00050e001, 0x0, 0x0, {0x0, 0x0}, 0x0, {0xc0007867c0, 0x2, 0x2})
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:735 +0x1ae
k8s.io/klog/v2.(*loggingT).print(...)
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:717
k8s.io/klog/v2.Fatal(...)
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1622
main.main()
/home/runner/work/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x7cc

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1283 +0x6a
created by k8s.io/klog/v2.init.0
/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:420 +0xfb

goroutine 10 [syscall]:
os/signal.signal_recv()
/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
/opt/hostedtoolcache/go/1.17.8/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
/opt/hostedtoolcache/go/1.17.8/x64/src/os/signal/signal.go:151 +0x2c

proxy exited with code: 255
```

**Kubeconfig:**

```sh
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    certificate-authority-data: LS...0K
    server: https://192.168.1.74:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS...==
    client-key-data: L...=

```

**Comment by Nokel81** [comment]
Does this work with `kubectl` because we are using the same client-go library that `kubectl` is using?

As the error states, using the `insecure-skip-tls-verify` flag is only allowed when you don't also provide a root certificate.

**Comment by Nokel81** [comment]
If you remove the certificate it should work

**Comment by Nokel81** [comment]
Removing the certificate is the correct thing to do. This requirement come from client-go itself. If you need to use the flag with kubectl then having the certificate in your kubeconfig is useless anyway.

**Comment by qdrddr** [comment]
@Nokel81 

If I keep my certificate like this:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://so-m001:6443"
    insecure-skip-tls-verify: true
    certificate-authority-data: "LS0...S0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-s452j:x6xv5pjdhdhs9dl"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
```

and trying to connect, getting this error message:
```
F1031 13:55:14.417449 7987 main.go:82] failed to initialize proxyspecifying a root certificates file with the insecure flag is not allowed

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1140 +0x8c
k8s.io/klog/v2.(*loggingT).output(0x106b88900, 0x3, 0x0, 0x140002217a0, 0x1, {0x106438af9?, 0x20?}, 0x14000100480?, 0x0)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1088 +0x5f4
k8s.io/klog/v2.(*loggingT).printDepth(0x0?, 0x0?, 0x0, {0x0, 0x0}, 0x0?, {0x140005364a0, 0x2, 0x2})
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:735 +0x15c
k8s.io/klog/v2.(*loggingT).print(...)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:717
k8s.io/klog/v2.Fatal(...)
/Users/runner/go/pkg/mod/k8s.io/klog/v2@v2.40.1/klog.go:1622
main.main()
/Users/runner/work/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x760
```

When I remove my certificate, like this:

```yaml
apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://so-m001:6443"
    insecure-skip-tls-verify: true

users:
- name: "local"
  user:
    token: "kubeconfig-user-s452j:x6xv5pjdhdhs9dl"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
```

I'm getting another error:

```
local
Starting connection ...

Authentication proxy started

Refreshing connection status ...

Failed to get /version for clusterId=cf131b51a2ec2f23a5f9303832a7ce9b: Unauthorized

Failed to get /version for clusterId=cf131b51a2ec2f23a5f9303832a7ce9b: Unauthorized
```

**Comment by sribaral** [comment]
> Does this work with `kubectl` because we are using the same client-go library that `kubectl` is using?
> 
> As the error states, using the `insecure-skip-tls-verify` flag is only allowed when you don't also provide a root certificate.
**Added sample for help**

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    # certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURNMk9USTVOVFl3SGhjTk1qTXhNakkzTVRZd01qTTJXaGNOTXpNeE1qSTBNVFl3TWpNMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURNMk9USTVOVFl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVTV5NEtlQ3RaQnpnblAzOU1xc3czMFNtanJtRHJHVlRmU20zU2hFS1IKd2pIMSs5Q0FvczZ0OTgxUEtBMXJJdDd1cGlocWdwazBsZHN2L3dRTGNhdjhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVVSOUw2N0thd3htSmVCSU9FZUdHCmVpbEVrdHN3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnZFM5d3lWYVRLeGVoMEhIVitCMUpNeHl4TnFVTzB4azAKRElYYzBydTZRMDRDSUVVQTk0d0YxdE5JQ3NFMjhoWElTRVBjbHl1OElQRHY1T3N0WmZQY1hlWTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.6.30:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJSRINKANTADQVRlZ0F3SUJBZ0lJZnV0R1hFUk1HaTB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekF6TmpreU9UVTJNQjRYRFRJek1USXlOekUyTURJek5sb1hEVEkwTVRJeQpOakUyTURJek5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGdW1sZlJmdDR1Wmg0REoKMFlWNXVaRFhYcXdRZHZCa0Z4ZWVvNjZ3SzhhajQ0V1lLZzFTb4bm8rdTJySDk5NXV0a3FCV25qTHkrZmJvOQppRm9ReWZlalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUjgzYkFKeXllZG90Wlprejg0SFI5V016Z01DakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCOUpVQXMzUjBGS292V08zL0hydXVXTGRQaTNRWnB6eXlONHFYdU1jRzBsUUlnUm95Q3oxMlgxUCtmMzZzLwo2QXV5T3YwQ0ZTSGhDUE04Y3ZCMzFkZ0xZNWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTURNMk9USTVOVFl3SGhjTk1qTXhNakkzTVRZd01qTTJXaGNOTXpNeE1qSTBNVFl3TWpNMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTURNMk9USTVOVFl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFROWNqMElQRmpHOUo4S1pZUVlFcmREZmE5RkdPSnNjM0FlOUNyVVFmcU8Kby9Ka00zNWt2UFE2dzcrd1oxeFpuL3NEQnkrMnJCb2E2TGJIUXFDMmxhcmFvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWZOMndDY3NubmFMV1daTS9PQjBmClZqTTREQW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnUW5kaGE5Z3FQUzFveEovTG9ZRTNZWjEzY1FobDgwRkQKOUpoZzdpOFM4eG9DSVFEa2lUV0xTQ1JxZ1ZEaEVwdVEzREl4VVVkN0VCWFMyckxnTDNNaVZISmdnUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQKANTAWQVRFIEtFWSRI0tLS0tCk1IY0NBUUVFSVA2K0FRcFNNdFh5U0JrSzdxTFRMQXNPMWxsZkdORkRYKzdOakFFbkh0dGZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVzZhVjlGKzNpNW1IZ01uUmhYbTVrTmRlckJCMjhHUVhGNTZqcnJBcnhxUGpoWmdxRFZLVgpIeWVqNjdhc2YzM202MlNvRmFlTXZMNTl1ajJJV2hESjl3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

```
