### ISSUE TITLE
Lens not working correctly when kubelogin auth is used

### ISSUE THREAD

**Issue by aleexx17** [kontena/lens#6427]
**Describe the bug**
We have AKS Kubernetes Clusters to authenticate we now use the azure kubelogin (https://github.com/Azure/kubelogin) since the azure auth plugin is deprecated in the versions v.1.22+ 
I've noticed, that in Lens I can only connect to the clusters when I'm using the azure auth plugin. As soon as I use kubelogin I get the follwing error: 

```bash
getting credentials: exec: executable kubelogin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

I also tried to set the absoloute path for the kubelogin command, but I get the same error. 

```bash
getting credentials: exec: executable /home/linuxbrew/.linuxbrew/opt/kubelogin/bin/kubelogin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

But I am able to connect to my cluster via kubectl.

**To Reproduce**
1. Open Lens
2. Click on the cluster with the kubelogin auth and try to connect

**Expected behavior**
I'm able to connect to the cluster and authenticate with kubelogin. 

**Environment (please complete the following information):**
- Lens Version: 6.1.12
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): .exe installation

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: mycacertificate
    server: https://my-aks-cluster:443
  name: my-aks-cluster
contexts:
- context:
    cluster: my-aks-cluster
    user: clusterUser_my-aks-cluster
  name: my-aks-cluster
current-context: my-aks-cluster
kind: Config
preferences: {}
users:
- name: clusterUser_mgb-my-aks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - my-server-id
      - --client-id
      - my-client-id
      - --tenant-id
      - my-tenant-id
      - --login
      - devicecode
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
