### ISSUE TITLE
Unable to connect to my K8s Cluster w/ latest Arm MACOS version

### ISSUE THREAD

**Issue by tsteinholz** [kontena/lens#6492]
**Describe the bug**

After updating the following error message pops up on attempting to connect to an EKS cluster `E1031 20:32:13.743311 23106 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found`. Also worth noting that the aws executable is in my path, but not sure why it would be using it to connect to my cluster.

**To Reproduce**
1. Update to latest version on Mac OSX

**Expected behavior**

Connect to the cluster

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 2022.10.311317-latest
- OS: OSX 12.6 
- Installation method (e.g. snap or AppImage in Linux): Mac Install, in app update

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
E1031 20:32:13.743311 23106 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.

I am able to connect fine via any other connection mechanism using my kube config.

**Additional context**
Same issue was reported here in #5676, however, this solution is not applicable to me as my aws executable is in my PATH.

```
# aws version
aws-cli/2.7.31 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off
```

**Comment by kjwierenga** [comment]
I'm being held back by the same issue. Is there a way to downgrade Lens?

**Comment by kjwierenga** [comment]
> I'm being held back by the same issue. Is there a way to downgrade Lens?

Managed to fix this by changing `apiVersion` from `v1alpha1` to `v1beta1` in my kube config.

```yaml
users:
  - name: arn:aws:eks:eu-west-1:**account*number**:cluster/**my*cluster*name**
    user:
        exec:
            apiVersion: client.authentication.k8s.io/v1beta1 # was `v1alpha1
            args:
              - --region
              - eu-west-1
              - eks
              - get-token
              - --cluster-name
              - production
            command: aws
```
