### ISSUE TITLE
apiVersion PodDisruptionBudget is incorrect

### ISSUE THREAD

**Issue by ismailyenigul** [kontena/lens#6503]
**Describe the bug**

Deployed PodDisruptionBudget as apiVersion: policy/v1  but when I try to edit this resource, Lens IDE shows it as  `apiVersion: policy/v1beta1`
What I see with kubectl
```
kubectl get poddisruptionbudgets.policy -n cluster-autoscaler eks-ca-aws-cluster-autoscaler -o yaml     
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    meta.helm.sh/release-name: eks-ca
    meta.helm.sh/release-namespace: cluster-autoscaler
  creationTimestamp: "2022-11-02T11:43:19Z"

```

**To Reproduce**

Deploy a PodDisruptionBudget with apiVersion: v1
Edit it on Lens IDE

**Expected behavior**
It should display as v1 not v1beta

**Screenshots**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/2566232/199500068-d944b80a-4488-4570-8888-5f8e2fc1d234.png">

**Environment (please complete the following information):**
- Lens Version:  Lens: 2022.10.311317-latest

- OS: MacOS
