### ISSUE TITLE
Metrics not available on k3s

### ISSUE THREAD

**Issue by praetorianer777** [kontena/lens#6520]
**Describe the bug**
Hello! I installed k3s on 2 machines, one master one worker. When Using auto-detect I don't get metrics at all. So I deinstalled the shipped metrics server and used the lens metric stack.
Now I see metrics for pods and nodes (except storage), but no metrics for the cluster itself.
The cluster runs for several hours.

**To Reproduce**
1. Install k3s on Ubuntu 20, one worker one master
2. remove shipped metrics server
3. install lens metric stack

**Expected behavior**
See storage and cluster metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/6584303/200116384-cf7b3889-1bcd-4b87-a8d8-6fc8f3390973.png)
![image](https://user-images.githubusercontent.com/6584303/200116413-6e347310-b1ca-416a-bbb9-ce69d09122b9.png)
![image](https://user-images.githubusercontent.com/6584303/200116446-dc2b7721-3b61-4606-8657-24ac0475a618.png)

**Environment (please complete the following information):**
- Lens Version: 2022.11.41813-latest (Version 6)
- OS: Windows 10

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://kubemain:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: 
    client-key-data: 
```
