### ISSUE TITLE
Unable to connect to Azure Kubernetes Cluster - devicelogin is not supported if interactiveMode is 'never'

### ISSUE THREAD

**Issue by mgvinuesa** [kontena/lens#6586]
**Describe the bug**
It is not possible to connect from Lens to Azure Kubernetes Cluster

**To Reproduce**
From command line it is possible to do with the following commands

az login --use-device 
az account set --subscription <subId>  
az aks get-credentials --resource-group  <resource group> --name <resource name>  
kubectl ...

**Expected behavior**
Interact with the cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/11572462/202124206-869b7b33-d327-44ba-9e55-81edd5d193a9.png)

**Environment (please complete the following information):**
- Lens Version: 
![image](https://user-images.githubusercontent.com/11572462/202125567-970d5a95-8dfa-4b45-b248-64c59589fc57.png)

- OS: [e.g. OSX] Windows 12
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [CLUSTER]: refresh {"accessible":false,"disconnected":false,"id":"3bf40ecd91d16eaaf6ddb05088190c3a","name":"<name>","online":false,"ready":false}
error: [CLUSTER]: Failed to connect to "<name>": StatusCodeError: 500 - "getting credentials: exec: executable kubelogin failed with exit code 1\n"```
```
**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <DATA>
    server: <URL>
  name: <CLUSTER NAME>
contexts:
- context:
    cluster: <CLUSTER NAME>
    user: <CLUSTER USER>
  name: <CLUSTER NAME>
current-context: <CLUSTER NAME>
kind: Config
preferences: {}
users:
- name: <CLUSTER USER>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <SERVER ID>
      - --client-id
      - <CLIENT ID>
      - --tenant-id
      - <TENANT ID>
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false
```

**Additional context**
