### ISSUE TITLE
App crash at /persistent-volumes

### ISSUE THREAD

**Issue by adacaccia** [kontena/lens#6688]
**Describe the bug**
The app crashes as soon as I click on any PersistenVolume

**To Reproduce**
1. Go to 'PersistentVolumes'
2. Click on 'any resource form the right panel'
3. See error

**Expected behavior**
A pop-up panel should appear as always when clicking single resources, giving details of it

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.x but seen already on 5.x
  - Lens: 2022.11.251411-latest
     Extension API: 6.2.3
     Electron: 19.1.7
     Chrome: 102.0.5005.167
     Node: 16.14.2
- OS: MacOS Monterey 12.5.1 on Apple M1 chip
- Installation method: Mirantis website
  
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```

Component stack:

    at PersistentVolumeDetails (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:606232:31)
    at div
    at div
    at div
    at NonInjectedAnimate (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:579561:13)
    at NonInjectedDrawer (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:598974:9)
    at NonInjectedKubeObjectDetails (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:610953:9)
    at ObserverComponent (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:239517:23)
    at ErrorBoundary (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:599444:9)
    at observerComponent (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:239469:16)
    at ThemeProvider (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:124175:24)
    at Router (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:456492:30)


Error stack:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at PersistentVolumeDetails.render (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:606262:24)
    at allowStateChanges (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:241802:12)
    at http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:240004:77
    at trackDerivedFunction (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:242388:18)
    at Reaction.track (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:242960:18)
    at PersistentVolumeDetails.reactiveRender [as render] (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:240000:14)
    at target.render (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:239900:17)
    at qi (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:455040:188)
    at pi (http://037cf7e083bef50a5aa3d008c5626570.localhost:49153/build/Lens.js?606c2c3e9dee3e88406c:455039:173)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***
    server: https://***:6443
  name: cluster-devops
contexts:
- context:
    cluster: cluster-devops
    user: user-cxyvt3tlhcq
  name: atena-devops
current-context: atena-logs
kind: Config
preferences: {}
users:
- name: user-cxyvt3tlhcq
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - ce
      - cluster
      - generate-token
      - --cluster-id
      - ocid1.cluster.oc1.eu-frankfurt-1.***
      - --region
      - eu-frankfurt-1
      command: oci
      env: []
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**
We run fully managed Kubernetes clusters on OCI with Oracle Kubernetes Engine (OKE), that's why the "oci" command line tool is used to get a token form OCI at each user interaction.
