### ISSUE TITLE
Unknown error has occurred

### ISSUE THREAD

**Issue by jwcesign** [kontena/lens#6710]
**Describe the bug**
Could not connect to aws eks

**To Reproduce**
```sh
cesign@jw [21时05分48秒] [~/git]
-> % kubectl get pods -A
NAMESPACE      NAME                                               READY   STATUS    RESTARTS   AGE
akuity         akuity-agent-7fd4f5c9c6-jkc47                      0/1     Pending   0          30h
akuity         akuity-agent-7fd4f5c9c6-z8csf                      0/1     Pending   0          3h43m
akuity         argocd-application-controller-6566bf97b4-pjjqn     0/2     Pending   0          3h43m
akuity         argocd-notifications-controller-7c595ffb5d-tx29n   0/1     Pending   0          3h43m
akuity         argocd-redis-5db44cd76f-glpff                      0/1     Pending   0          3h43m
akuity         argocd-repo-server-5547c98fb-qpnrc                 0/1     Pending   0          30h
akuity         argocd-repo-server-5547c98fb-rj8w9                 0/1     Pending   0          3h43m
bookinfo       productpage-v1-74fdfbd7c7-lzpjn                    0/2     Pending   0          30h
bookinfo       ratings-v1-b74b895c5-6s6xh                         0/2     Pending   0          30h
bookinfo       reviews-v1-68b4dcbdb9-9t5s2                        0/2     Pending   0          33h
bookinfo       reviews-v2-565bcd7987-5mhtt                        0/2     Pending   0          30h
bookinfo       reviews-v3-d88774f9c-8j4dk                         0/2     Pending   0          30h
castai-agent   castai-agent-7cbc97dbf4-wpl5z                      0/1     Pending   0          3h43m
castai-agent   castai-agent-cpvpa-848995b6b-vbw7j                 0/1     Pending   0          3h43m
gmaestro       granulate-maestro-579f9b4ffc-ffbcd                 0/2     Pending   0          30h
grafana        grafana-566b5775db-87ngb                           0/1     Pending   0          33h
istio-system   istio-egressgateway-59d4c446df-7h879               0/1     Pending   0          30h
```
But Lens show `Unknown error has occurred`

**Expected behavior**
Connect to the clusters

**Screenshots**
![image](https://user-images.githubusercontent.com/19745536/206187517-5b376fd1-988b-495b-b5a2-5a626752965b.png)

**Environment (please complete the following information):**
- Lens Version: https://downloads.k8slens.dev/ide/Lens-2022.12.11410-latest.dmg
- OS: OSX
- Installation method (): as show before

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
No logs.
cesign@jw [20时57分41秒] [~/git]
-> % DEBUG=true /Applications/Lens.app/Contents/MacOS/Lens
cesign@jw [20时57分44秒] [~/git]
-> % DEBUG=true /Applications/Lens.app/Contents/MacOS/Lens
cesign@jw [21时01分05秒] [~/git]
-> % DEBUG=true /Applications/Lens.app/Contents/MacOS/Lens
cesign@jw [21时01分10秒] [~/git]
-> % DEBUG=true /Applications/Lens.app/Contents/MacOS/Lens
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://xxx.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
    user: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
  name: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
current-context: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:xxx:cluster/multi-tenancy-with-teams
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - multi-tenancy-with-teams
      command: aws
```

**Additional context**
