### ISSUE TITLE
Secrets not visible in navigation

### ISSUE THREAD

**Issue by erikverheij** [kontena/lens#6732]
**Describe the bug**
I have access to all the secrets of several namespaces in our cluster. However, the item "Secrets" is not available under "Config" in the navigation. 

After changing my permissions to view all secrets in all namespaces the item becomes visible. Maybe Lens is looking for secrets in the default namespace when determining whether to show the item in the navigation?

![image](https://user-images.githubusercontent.com/3001961/207012814-99082adb-948d-4734-add0-7b01e7727280.png)

**To Reproduce**
1. Create a k8s user that has access to all secrets in a specific namespace
2. Create a secret in this namespace
3. Verify with `kubectl` you can list the secrets (`kubectl get secret -n your-namespace`)
4. Open or restart Lens
5. Navigate to "Config"
6. "Secrets" should be visible, but isn't.

**Expected behavior**
"Secrets" should be available in the Navigation under Config.

**Environment:**
- Lens Version: 2022.12.11410-latest
- OS: Windows 11 Pro
- Installation method (e.g. snap or AppImage in Linux): .exe file.

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxx
    server: xxxxx
  name: xxxxx
contexts:
- context:
    cluster: xxxxx
    user: xxxxx
  name: xxxxx
current-context: xxxxx
kind: Config
preferences: {}
users:
- name: xxxxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - xxxxx
      command: aws
      env:
      - name: AWS_PROFILE
        value: xxxxx

```
