### ISSUE TITLE
Incorrect apiVersion ( autoscaling/v2beta1) in hpa edit screen for hpa autoscaling/v2

### ISSUE THREAD

**Issue by armujahid** [kontena/lens#6827]
**Describe the bug**
Lens is showing incorrect apiVersion ( autoscaling/v2beta1) in hpa edit screen for hpa autoscaling/v2

**To Reproduce**
1. Create an hpa using this manifest
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pause
spec:
  minReplicas: 2
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pause
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

```
2. open HPA screen and edit that HPA
![image](https://user-images.githubusercontent.com/3725386/209339542-c36b9d19-e0bb-454c-ae9c-71db4a1c35ec.png)
3. You can see that it is showing incorrect apiVersion
Note that `k get hpa/pause -o yaml` shows correct api version
![image](https://user-images.githubusercontent.com/3725386/209339684-99fddd94-9c76-4a61-b65c-44d711562fa0.png)

**Expected behavior**
Lens should show `autoscaling/v2` apiVersion

**Screenshots**
Already added above

**Environment (please complete the following information):**
- Lens Version: 2022.12.221341-latest
![image](https://user-images.githubusercontent.com/3725386/209338980-3d598e30-0a78-46f3-b2af-c0fec56e7518.png)

- OS: Ubuntu 22.04.1 LTS
- Installation method (e.g. snap or AppImage in Linux): deb

**Logs:**
N/A

**Kubeconfig:**
N/A

**Additional context**
N/A
