### ISSUE TITLE
Terminal tab top and left padding missing

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#6839]
**Describe the bug**
In recent versions of Lens (6.2.5 or newer), the terminal tab has lost its top/left padding. It works fine but looks weird compared to before.

**To Reproduce**
1. Open a cluster in Lens.
2. Click on the '+' to open a new tab.
3. Choose 'Terminal session'.

**Expected behavior**
The terminal tab should retain its padding as it did in versions 6.2.4 or earlier.

**Screenshots**
<details>
<summary>6.2.4</summary>
<img src="https://user-images.githubusercontent.com/3536482/209837707-4a91677c-3d4a-4232-a0a2-6c1551bb6717.png" /> 
</details>
<details>
<summary>6.2.5/6.3.0</summary>
<img src="https://user-images.githubusercontent.com/3536482/209837625-3282b64b-a11b-4f39-adff-07556b37543a.png" />
</details>

**Environment (please complete the following information):**
- Lens Version: 6.2.5, 6.3.0
- OS: macOS
- Installation method: OpenLens ZIP/DMG, local build from source

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ┏ [UNIX-SHELL-ENV]: running against /usr/local/bin/zsh +8s
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/Applications/OpenLens.app/Contents/MacOS/OpenLens' -p '"3e18676e961e478fbe3a7ff31b2ecd17" + JSON.stringify(process.env) + "3e18676e961e478fbe3a7ff31b2ecd17"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
info:    ▪ [SHELL-SESSION]: PTY for 0fb2af8cda520fcc4f17c10113398dd1:57c58712-16f1-4e86-a557-286a3229cf90 is started with PID=77138 +688ms
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
```
