### ISSUE TITLE
catalog to import proxy-url from kubeconfig

### ISSUE THREAD

**Issue by gberche-orange** [kontena/lens#6861]
**What would you like to be added**:

Given a kubeconfig with a  `proxy-url` field as documented into https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy
When using the catalog to browser clusters and connecting to a cluster
Then the cluster has automatically its proxy settings filled in

**Why is this needed**:

Currently, users have to manually edit the proxy settings, even if the information is in the ~/.kube/config file

![image](https://user-images.githubusercontent.com/4748380/210339996-5ea41844-f910-42a7-a61f-f665368c330f.png)
![image](https://user-images.githubusercontent.com/4748380/210340026-139b9120-e98e-431e-9c89-f7d9bae31a18.png)

```yaml
apiVersion: v1
kind: Config

clusters:
- cluster:
    proxy-url: http://proxy.example.org:3128
    server: https://k8s.example.org/k8s/clusters/c-xxyyzz
  name: development

users:
- name: developer

contexts:
- context:
  name: development
```

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>
