### ISSUE TITLE
Error upon connecting to cluster on Windows

### ISSUE THREAD

**Issue by dcole-gsn** [kontena/lens#6866]
**Describe the bug**
When attempting to connect to a cluster on Windows require the following error message

F0103 14:46:21.817744 53236 main.go:82] failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2dfff40, 0x3, 0x0, 0xc000212af0, 0x1, {0x25c5de7, 0x20}, 0x2e00e20, 0x0)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
k8s.io/klog/v2.(*loggingT).printDepth(0x2dfff40, 0x0, 0x0, {0x0, 0x0}, 0x0, {0xc00013a2c0, 0x2, 0x2})
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1c7
k8s.io/klog/v2.(*loggingT).print(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:1490
main.main()
D:/a/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x725

goroutine 36 [syscall]:
os/signal.signal_recv()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal.go:151 +0x2c

proxy exited with code: 255

**To Reproduce**
1. Connect to added cluster.

**Expected behavior**
Be able to connect to configured cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/22635392/210383535-2e785173-9833-4ef5-84e4-70650e30e4dd.png)

**Environment (please complete the following information):**
- Lens Version:
- OS: [Windows]
- Installation method (e.g. snap or AppImage in Linux): Used installer from OpenLens, also built myself.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
F0103 14:46:21.817744 53236 main.go:82] failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2dfff40, 0x3, 0x0, 0xc000212af0, 0x1, {0x25c5de7, 0x20}, 0x2e00e20, 0x0)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
k8s.io/klog/v2.(*loggingT).printDepth(0x2dfff40, 0x0, 0x0, {0x0, 0x0}, 0x0, {0xc00013a2c0, 0x2, 0x2})
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1c7
k8s.io/klog/v2.(*loggingT).print(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:1490
main.main()
D:/a/lens-k8s-proxy/lens-k8s-proxy/main.go:82 +0x725

goroutine 36 [syscall]:
os/signal.signal_recv()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
C:/hostedtoolcache/windows/go/1.17.13/x64/src/os/signal/signal.go:151 +0x2c

proxy exited with code: 255
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
  name: arn:aws:eks:us-east-1:xxxxxxxxx:cluster/seam-eks-development
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxx:cluster/seam-eks-development
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:xxxxxxxxx:cluster/seam-eks-development
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - seam-eks-development
      command: aws
      env:
      - name: AWS_PROFILE
        value: saml
      provideClusterInfo: false
```

**Additional context**
