### ISSUE TITLE
No details for successfully connected cluster

### ISSUE THREAD

**Issue by TaraBrownSmith** [kontena/lens#6929]
I'm new to OpenLens, having previously used LENS. I installed with scoop. The install appears to be successful however, once connected to my cluster, there are no details. Nodes are displayed and status is "Ready." I'm seeing no details for Workloads, Config, Network, Storage, Namespaces, etc. What configuration options should I review? Thanks in advance for your assistance.

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Overview'

**Expected behavior**
I expect to see Pods (122), Deployments (96), etc., nonzero.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
OpenLens: 6.3.0
Extension API: 6.3.0
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2

- OS: [e.g. OSX]
Windows 10 Enterprise

- Installation method (e.g. snap or AppImage in Linux):
scoop bucket add extras
scoop install openlens

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
https://pastebin.com/bMEfauSQ
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://sastsb-bv1-aks-35e2991b.hcp.eastus.azmk8s.io:443
  name: sastsb-bv1-aks-35e2991b.hcp.eastus.azmk8s.io
contexts:
- context:
    cluster: sastsb-bv1-aks-35e2991b.hcp.eastus.azmk8s.io
    namespace: d59189
    user: d59189
  name: d59189@sastsb-bv1-aks-35e2991b.hcp.eastus.azmk8s.io/d59189
current-context: d59189@sastsb-bv1-aks-35e2991b.hcp.eastus.azmk8s.io/d59189
kind: Config
preferences: {}
users:
- name: d59189
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**Additional context**
