### ISSUE TITLE
Blank Screen when I try to connect to a aks cluster

### ISSUE THREAD

**Issue by djarami726** [kontena/lens#6940]
**Describe the bug**
Blank Screen when I try to connect to a aks cluster

**To Reproduce**
1. Start openlens, goto clusters
2. Double click on a cluster
3. Blank screen
4. Go back to clusters and it shows as connected.

**Expected behavior**
Should open up the cluster and show all the info about the cluster and also be able to select options from menu

**Screenshots**
![image](https://user-images.githubusercontent.com/107571134/212427315-93763b87-b662-4bab-9e1b-ee9ccc1cb7a3.png)
List of clusters

![image](https://user-images.githubusercontent.com/107571134/212946124-7f1fe512-3c18-4806-abae-798d2349b29f.png)

Blank screen

**Environment (please complete the following information):**
- Lens Version: 6.3.0 and 6.4.0-alpha.2
- OS: [e.g. OSX] Windows 11
- Installation method (e.g. snap or AppImage in Linux): 
downloaded exe from the tags page

**Logs:**
No logs generated on the command line on windows.

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.

I obfuscated with xxxxx the certificate and also the server names.   Problem happens still happens even with one aks config

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    server: https://app-xxxxxxxx-dev-aks-1-16ba61c2.hcp.eastus.azmk8s.io:443
  name: app-xxxxxxxx-dev-aks-1
contexts:
- context:
    cluster: app-xxxxxxxx-dev-aks-1
    user: clusterUser_app-xxxxxxxx-dev-eastus_app-xxxxxxxx-dev-aks-1
  name: app-xxxxxxxx-dev-aks-1
current-context: app-xxxxxxxx-dev-aks-1
kind: Config
preferences: {}
users:
- name: clusterUser_app-xxxxxxxx-dev-eastus_app-xxxxxxxx-dev-aks-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 6dae42f8-4368-4678-94ff-888888888888
      - --client-id
      - 80faf920-1908-4b52-b5ef-888888888888
      - --tenant-id
      - bc877e61-f6cf-4461-accd-888888888888
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false

```

**Additional context**
