### ISSUE TITLE
can't add eks to Lens 

### ISSUE THREAD

**Issue by Haliltarik** [kontena/lens#6961]
![Capture](https://user-images.githubusercontent.com/49556634/212906035-94e17736-ed8e-475b-8988-14c0cb4be438.PNG)

I'm facing a problem whith Lens access to eks around 2 months ago. I think I tried a lot of solutions but nothing is working for me.

I'm accessing to eks fine on wsl Ubuntu with AWS credentials.

I Installed the last version of Lens put the kubeconfig file to add eks clusters change the terminal to "wsl.exe" on Lens.

I can do do "kubectl get node" through wsl on powershell 

PS C:\Users\Tarik\AppData\Local\Programs\Lens> wsl kubectl get nodes
NAME                                           STATUS   ROLES    AGE   VERSION
******************.compute.internal   Ready    <none>    6d   v1.22.9-eks-********
******************.compute.internal   Ready    <none>    8d   v1.22.9-eks-********
******************.compute.internal   Ready    <none>    3d   v1.22.9-eks-********

**Environment:**
Windows 10
WSL Ubuntu 20.04.5 
Lens 6.2.6

My kubeconfig :
```
- name: arn:aws:eks:eu-west-1:****************:cluster/test-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - test-eks
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

And I have this error "Unknown error has occurred" :

![Capture](https://user-images.githubusercontent.com/49556634/212902216-a4ef2545-66be-4701-9166-18f4445e9c2a.PNG)

Logs from lens.log
```
error: [CLUSTER]: Failed to connect to "dmpa-noprod/indus": StatusCodeError: 401 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
debug: Unknown error has occurred {"isError":true,"meta":{"accessible":false,"disconnected":false,"id":"82128060e6d597b391a3c7b2565e7748","name":"dev/test-eks","online":false,"ready":false}}
```

Have you faced this issue before? how did you solve it ? Thanks in advance for your help.
