### ISSUE TITLE
OpenLens: Don't get information after connect the cluster

### ISSUE THREAD

**Issue by parraletz** [kontena/lens#7016]
**Describe the bug**
 Don't get information after connect the cluster
**To Reproduce**
1. Go to cluster list
2. Click on whatever cluster
3. wait while connect to the cluster 

**Expected behavior**

See cluster information

**Screenshots**
<img width="1552" alt="Screenshot 2023-01-26 at 6 45 15" src="https://user-images.githubusercontent.com/1150748/214838804-33e688f5-43a6-479d-89d5-69b6d6eb9cd7.png">

**Environment (please complete the following information):**
- Lens Version:
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): brew

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: asdsadadsadasdasdsadasdsdsadsd
    server: https://asdasdasdsadsadsasdasd.gr7.-------------.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:054188234334:cluster/sigurd
contexts:
- context:
    cluster: arn:aws:eks:-------:99999999999:cluster/sigurd
    user: arn:aws:eks:-------:99999999999:cluster/sigurd
  name: arn:aws:eks:-------:99999999999:cluster/sigurd
current-context: arn:aws:eks:-------:99999999999:cluster/sigurd
kind: Config
preferences: {}
users:
- name:  arn:aws:eks:-------:99999999999:cluster/sigurd
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - sigurd
      command: aws
      env:
      - name: AWS_PROFILE
        value: 
```

```
your kubeconfig here
```

**Additional context**
After reload the Custer information is getting.
