### ISSUE TITLE
logTabStore.createPodTab don't display properly after all log tabs closed, until application reload

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#7071]
**Describe the bug**
When extensions open a tab with `logTabStore.createPodTab`, the tab panel opens but none of the UI elements or output is displayed.

If the tab is kept open and the application is then reloaded, the tab contents display properly. Opening _additional_ log tabs in this state (after reload) also display properly. However, if _all_ of the open log tabs (which are displayed properly) are closed, opening a new log tab shows the same issue again as before until application reload.

Note that application reload does _not_ fix the issue if no log tabs are open.

**To Reproduce**
1. Install an extension that creates tabs in `logTabStore`, such as https://github.com/alebcay/openlens-node-pod-menu.
2. Open at least one logs tab. They should all be missing text/buttons/etc (see first screenshot).
3. Reload the application (<kbd>⌘</kbd>+<kbd>R</kbd> on macOS).
4. All logs tabs that were previously opened should now be displaying as expected (see second screenshot).
5. Open at least one additional logs tab. They should all be displaying as expected.
6. Close all logs tabs that are opened (shell/terminal tabs can be kept open).
7. Open at least one logs tab. They should all be missing text/buttons/etc again.

**Expected behavior**
Logs tabs should be displayed correctly without requiring an application reload (and without possibly going into a bad state again if all log tabs are closed).

**Screenshots**

Before application reload:

![Screen Shot 2023-01-31 at 6 15 04 PM](https://user-images.githubusercontent.com/3536482/215905736-56c935e9-217a-471d-9fe7-b3ef662c3865.png)

After application reload:

![Screen Shot 2023-01-31 at 6 15 32 PM](https://user-images.githubusercontent.com/3536482/215905762-5b2a5a64-bb91-40cb-a24e-ef66ede14e41.png)

**Environment (please complete the following information):**
- Lens Version: 6.4.0-beta.10 and built from f445bd4eb982bb6683407e20b29858ece97a9f49
- OS: macOS and Debian Bullseye
- Installation method (e.g. snap or AppImage in Linux): Built from source

**Logs:**
No logs are printed in the terminal when trying to open a logs tab. The following output is logged in the developer tools console:

```
[KUBE-API] watch (pod-6) started /api/v1/pods?watch=1&resourceVersion=10003
[STORAGE-HELPER]: saving /Users/caleb/Library/Application Support/OpenLens/lens-local-storage/4bbbaf0671fe16f535b16ee54a970150.json
```

**Kubeconfig:**

Note that this error has been observed by more than one person in more than one environment. The kubeconfig for one environment is provided here:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://127.0.0.1:6443
  name: default
- cluster:
    certificate-authority: /Users/caleb/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://localhost:56111
  name: minikube
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: redacted
    client-key-data: redacted
- name: minikube
  user:
    client-certificate: /Users/caleb/.minikube/profiles/minikube/client.crt
    client-key: /Users/caleb/.minikube/profiles/minikube/client.key
```

**Additional context**
Original issue raised at https://github.com/alebcay/openlens-node-pod-menu/issues/15.
