### ISSUE TITLE
App.Preferences.getKubectlPath() call from extension fails with uncaught error

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#7076]
**Describe the bug**
The following error message is encountered in the developer log when an extension tries to call `App.Preferences.getKubectlPath()` (`import { Common } from "@k8slens/extensions"; const { App } = Common;`):

```
Uncaught (in promise) Error: Tried to get DI container using legacy globals where there is no containers available.
```

Full trace provided in the log below.

**To Reproduce**
1. Install an extension that calls `App.Preferences.getKubectlPath()`, such as https://github.com/alebcay/openlens-node-pod-menu.
2. Perform any action that calls `App.Preferences.getKubectlPath()`.
3. The action will fail and the aforementioned error is logged.

**Expected behavior**
The path to Lens' `kubectl`, as defined in preferences, should be returned.

**Screenshots**

![image](https://user-images.githubusercontent.com/3536482/215924250-c19391a8-320b-44b6-8624-b862c2ded742.png)

**Environment (please complete the following information):**
- Lens Version: https://github.com/lensapp/lens/commit/f445bd4eb982bb6683407e20b29858ece97a9f49
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): Built from source

**Logs:**

Developer tools console logs:

```
Uncaught (in promise) Error: Tried to get DI container using legacy globals where there is no containers available.
    at legacy_global_di_for_extension_api_getLegacyGlobalDiForExtensionApi (common.js:295:1)
    at Object.get (common.js:2384:1)
    at Object.getKubectlPath (common.js:3422:1)
    at PodShellMenu.execShell (/Users/caleb/.k8slens/extensions/alebcay--openlens-node-pod-menu/dist/renderer.js:282:45)
    at /Users/caleb/.k8slens/extensions/alebcay--openlens-node-pod-menu/dist/renderer.js:318:96
    at common.js:3643:1
    at MenuItem.onClick (renderer.js:421789:1)
    at Object.Rb (renderer.js:264187:315)
    at Xb (renderer.js:264187:468)
    at Yb (renderer.js:264188:32)
```

No additional logs/errors are produced in the terminal when running the binary directly from the command line.

**Kubeconfig:**

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://127.0.0.1:6443
  name: default
- cluster:
    certificate-authority: /Users/caleb/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://localhost:56111/
  name: minikube
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: redacted
    client-key-data: redacted
- name: minikube
  user:
    client-certificate: /Users/caleb/.minikube/profiles/minikube/client.crt
    client-key: /Users/caleb/.minikube/profiles/minikube/client.key
```

**Additional context**
I have also tried manually setting a path to `kubectl` in the preferences (rather than automatically letting Lens download/manage the binary) and also entirely deleting the `~/Library/Application Support/OpenLens` and `~/.k8slens` folders but the issue persists.
