### ISSUE TITLE
HPA doesn't render on Kubernetes 1.25

### ISSUE THREAD

**Issue by dgershman** [kontena/lens#7134]
**Describe the bug**
When pointed to a Kubernetes 1.25 cluster receiving the error message:

```
Failed to load /apis/autoscaling/v2beta1/horizontalpodautoscalers: the server could not find the requested resource
```

**To Reproduce**
1. Go to Lens
2. Click on 'HPA'
3. See error

**Expected behavior**
Lens should display the available configured HPAs.

**Screenshots**
![Screen Shot 2023-02-09 at 12 47 50 PM](https://user-images.githubusercontent.com/1850811/217902745-08733eee-9b96-43e7-ab40-d6295fe30f7c.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 2023.1.110749-latest
- OS: MacOS 12.6.1
- Installation method (e.g. snap or AppImage in Linux): DMG Installation

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>:6443
  name: k3d-k3s-default
contexts:
- context:
    cluster: k3d-k3s-default
    user: admin@k3d-k3s-default
  name: k3d-k3s-default
current-context: k3d-k3s-default
kind: Config
preferences: {}
users:
- name: admin@k3d-k3s-default
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
```

**Additional context**
Likely related to https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
