### ISSUE TITLE
App crash on LENS /extension/aquasecurity--trivy-operator-lens-extension/vulnerabilityreports

### ISSUE THREAD

**Issue by mjasinskiuneedit** [kontena/lens#7364]
On first TAB VulnerabilityReports

```
Error stack:
TypeError: e.getImageRef is not a function
    at d.render (/Users/mateuszjasinski/.k8slens/extensions/aquasecurity--trivy-operator-lens-extension/dist/renderer.js:1:20572)
    at qi (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566552:188)
    at pi (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566551:173)
    at ck (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566634:427)
    at bk (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566615:347)
    at ak (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566615:278)
    at Tj (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566615:138)
    at Lj (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566608:163)
    at https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:566488:115
    at exports.unstable_runWithPriority (https://d59425e1be660b64edbcc0d8aaf4035f.lens.app:50318/build/lens.js?27361ea8c984dddf9250:591052:343) 
``` 

**To Reproduce**
1. Click on any position in list.
2. See error

**Expected behavior**
See some information not ERROR.

**Environment (please complete the following information):**
- Lens Version: Lens: 2023.3.100736-latest
- OS:OSX 13.2.1
- Installation method: HELM

**Logs:**

```
status.reason":"Error","status.message":"2023-03-16T12:05:10.774Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (xxxxxx): Cannot connect to the Docker daemon at unix:///var/run/docker.sock.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/name: trivy-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: trivy-operator
        app.kubernetes.io/name: trivy-operator
    spec:
      containers:
        - name: trivy-operator
          image: ghcr.io/aquasecurity/trivy-operator:0.12.1-ubi8
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 9090
              protocol: TCP
          env:
            - name: OPERATOR_NAMESPACE
              value: trivy
            - name: OPERATOR_TARGET_NAMESPACES
            - name: OPERATOR_EXCLUDE_NAMESPACES
            - name: OPERATOR_TARGET_WORKLOADS
              value: >-
                pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
            - name: OPERATOR_SERVICE_ACCOUNT
              value: trivy-operator
            - name: OPERATOR_LOG_DEV_MODE
              value: 'false'
            - name: OPERATOR_SCAN_JOB_TTL
            - name: OPERATOR_SCAN_JOB_TIMEOUT
              value: 5m
            - name: OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
              value: '10'
            - name: OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT
              value: '1'
            - name: OPERATOR_SCAN_JOB_RETRY_AFTER
              value: 30s
            - name: OPERATOR_BATCH_DELETE_LIMIT
              value: '10'
            - name: OPERATOR_BATCH_DELETE_DELAY
              value: 10s
            - name: OPERATOR_METRICS_BIND_ADDRESS
              value: ':8080'
            - name: OPERATOR_METRICS_FINDINGS_ENABLED
              value: 'true'
            - name: OPERATOR_METRICS_VULN_ID_ENABLED
              value: 'false'
            - name: OPERATOR_HEALTH_PROBE_BIND_ADDRESS
              value: ':9090'
            - name: OPERATOR_VULNERABILITY_SCANNER_ENABLED
              value: 'true'
            - name: OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
              value: 'true'
            - name: OPERATOR_SCANNER_REPORT_TTL
              value: 24h
            - name: OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED
              value: 'true'
            - name: OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED
              value: 'true'
            - name: OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED
              value: 'true'
            - name: OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
              value: 'true'
            - name: OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED
              value: 'true'
            - name: OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED
              value: 'false'
            - name: OPERATOR_WEBHOOK_BROADCAST_URL
            - name: OPERATOR_WEBHOOK_BROADCAST_TIMEOUT
              value: 30s
            - name: OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES
              value: '{}'
            - name: OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS
              value: 'true'
            - name: OPERATOR_BUILT_IN_TRIVY_SERVER
              value: 'false'
            - name: TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION
              value: 10h
            - name: OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT
              value: 'false'
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz/
              port: probes
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz/
              port: probes
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: trivy-operator
      serviceAccount: trivy-operator
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

```

**Additional context**
