### ISSUE TITLE
Error while connecting to cluster

### ISSUE THREAD

**Issue by tautvydasbujauskas** [kontena/lens#7428]
**Describe the bug**
O noticed that on some of my clusters I get error 
```
E0329 14:53:13.515135 12560 proxy_server.go:147] Error while proxying request: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
***I can access cluster with sake kubeconfig cia kubectl***

Worth to mention:
- I have to clusters from same client, one is erroring while connecting another don't
- kubeconfig files have not been changed when error occurred.
- I updated config files wiht aws cli command, but no results.
**To Reproduce**
1. Connect to server 
2. Recieve error.

**Expected behavior**
Lens should connect to cluster, but it don't.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
E0329 14:53:13.515135 12560 proxy_server.go:147] Error while proxying request: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: certinBase64
    server: https://aws-api.com
  name: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
contexts:
- context:
    cluster: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
    user: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
  name: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
current-context: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:XXXXXXXXXXXXX:cluster/prod-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - prod-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: XXXXXXXXXX

```

**Additional context**
