### ISSUE TITLE
unknown command "oidc-login" for "kubectl"

### ISSUE THREAD

**Issue by carlmolemans** [kontena/lens#7520]
After updating OpenLens to the latest version (6.4.14) I suddenly received the following error: 

```
error: unknown command "oidc-login" for "kubectl"

E0406 09:17:28.083686 3456 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubectl failed with exit code 1

Failed to get /version for clusterId=3446ca6...def1865c: Internal Server Error
```

From what I've read online it appears that the update resulted in kubectl not finding kubelogin anymore? 
How can I fix this? I'm currently working on a Windows 10 machine

Configuration being used: 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0...
    client-key-data: LS0...
```

Cluster configuration:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0..
    server: https://cchip-k8s-qa.localhost:6443/
    # insecure-skip-tls-verify: true
  name: cchip-k8s-qa.locahost
contexts:
- context:
    cluster: cchip-k8s-qa.localhost
    user: oidc
  name: cc-hip-qa
current-context: cc-hip-qa
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://login.microsoftonline.com/<uuid>/v2.0
      - --oidc-client-id=<other-uuid>
      env: null
```
