### ISSUE TITLE
Metrics dashboard not working with kube-prometheus-stack

### ISSUE THREAD

**Issue by jeffersonnlucas** [kontena/lens#7667]
**Describe the bug**
Dashboard infinite load metrics but not showing

![image](https://user-images.githubusercontent.com/14850889/235820611-e3b51b1c-b2bb-4764-acf6-2c3af4f1c9f8.png)

**To Reproduce**
1. Create EKS Cluster
2. Add repository https://github.com/prometheus-community/helm-charts
3. Add custons on values https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md
4. Install Helm Chart kube-prometheus-stack version 45.24.0 

**Expected behavior**
![image](https://user-images.githubusercontent.com/14850889/235820906-a950e855-4ba2-4758-84b6-5c92501a0bd4.png)

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2023.4.141316-latest
- OS: [e.g. OSX] Windows 10
- Installation method (e.g. snap or AppImage in Linux):

**Comment by jeffersonnlucas** [comment]
Kubernetes version 1.24

**Comment by SB-MFJ** [comment]
Same here. Added these but I get nothing:
```yaml
kubelet:
  serviceMonitor:
    metricRelabelings:
    - action: replace
      sourceLabels:
      - node
      targetLabel: instance
prometheus-node-exporter:
  prometheus:
    monitor:
      metricRelabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels: 
        - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node
 ```
![image](https://github.com/lensapp/lens/assets/111309643/650366c4-6695-48fb-bc4a-059db4f16f5c)
![image](https://github.com/lensapp/lens/assets/111309643/ba3a8fd7-0fb9-4f15-ab3c-afdebaba01d4)
![image](https://github.com/lensapp/lens/assets/111309643/b77654eb-6b1d-4631-8efe-36848766a509)
![image](https://github.com/lensapp/lens/assets/111309643/9362b5ea-4a2f-4028-942b-f4c4a86aa7ae)

Server Version: v1.26.2-eks-a59e1f0
