### ISSUE TITLE
Not enough rights to delete pod

### ISSUE THREAD

**Issue by ahton005** [kontena/lens#7839]
**Describe the bug**
I can't delete pod. He writes that he is not right enough. It worked until the last update. If you delete via kubectl, then everything is ok.

1. Go to Pods submenu in the Workloads
2. Click on pod
3. Click Recycle bin.
4. Press button "Remove"
5. See error

![image](https://github.com/lensapp/lens/assets/98280033/78713358-540b-4f88-9d85-d1f5ff02ba3b)

**Environment (please complete the following information):**
- Lens Version: latest
- OS: Win10

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxxxxxxxxx
    server: https://t2ru-ds-test-k8s-master-01:6443
  name: k8s.test
contexts:
- context:
    cluster: k8s.test
    namespace: default
    user: azyablov-default-k8s.test
  name: azyablov-default-k8s.test
current-context: azyablov-default-k8s.test
kind: Config
preferences: {}
users:
- name: azyablov-default-k8s.test
  user:
    token:xxxxxxxxxxxxxxxxxxxxxxxx
```
