### ISSUE TITLE
Workloads is only showing the overview after the upgrade

### ISSUE THREAD

**Issue by joelgriffiths** [kontena/lens#7849]
**Describe the bug**
Workloads is only showing the overview after the upgrade

**To Reproduce**
I just upgraded, and checked several environments. Only Overview is showing up in workloads. I am using 1.21.6 for the server (I know, it's a bit old). Network appears to be missing things as well. The only thing that looks complete is Custom Resources.

Using admin.conf for all environments.

**Expected behavior**
See the components.

**Screenshots**
![Screen Shot 2023-06-15 at 1 10 03 PM](https://github.com/lensapp/lens/assets/4323417/b6d9780f-4983-454c-bbdb-ae2cd58b2b77)

**Environment (please complete the following information):**
- Lens Version: 2023.5.310801-latest
- OS: Mac OS 12.5.1
- Installation method (e.g. snap or AppImage in Linux): It's been a long time. I assume it was Brew.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: stuff==
    server: https://kube-vip.dev.mydomain.com:6443
  name: k8s-homelab
contexts:
- context:
    cluster: k8s-homelab
    namespace: special
    user: kubernetes-admin
  name: kubernetes-admin@k8s-homelab
current-context: kubernetes-admin@k8s-homelab
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: stuff==
    client-key-data: stuff=
your kubeconfig here
```

**Additional context**
I don't know what to make of this. Lens is completely useless to me at the moment.

**Comment by Nokel81** [comment]
@joelgriffiths Would you be able to try the following command and report the result

```
kubectl create -f - -o yaml << EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectRulesReview
spec:
  namespace: default
EOF
```

**Comment by joelgriffiths** [comment]
I did this with one of the devs. It gave me this, but I am definitely running as the cluster-admin.

```
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectRulesReview
metadata:
  creationTimestamp: null
spec: {}
status:
  incomplete: false
  nonResourceRules:
  - nonResourceURLs:
    - /healthz
    - /livez
    - /readyz
    - /version
    - /version/
    verbs:
    - get
  - nonResourceURLs:
    - /api
    - /api/*
    - /apis
    - /apis/*
    - /healthz
    - /livez
    - /openapi
    - /openapi/*
    - /readyz
    - /version
    - /version/
    verbs:
    - get
  resourceRules:
  - apiGroups:
    - authorization.k8s.io
    resources:
    - selfsubjectaccessreviews
    - selfsubjectrulesreviews
    verbs:
    - create
```
