### ISSUE TITLE
Connection to cluster never happens in lens version v2023.5.310801-latest (5/31/2023)

### ISSUE THREAD

**Issue by gsRatti1** [kontena/lens#7853]
**Describe the bug**
Clicking on a cluster from the list of cluster, simply causes the screen to be stuck with "Connecting ......."  message.
Kubectl commands work fine from terminal

**To Reproduce**
1. Download and install latest version of lens v2023.5.310801-latest (5/31/2023)
2. Add a new cluster
3. Try connecting to the cluster by clicking on it

**Expected behavior**
Cluster view should load

**Screenshots**
![image](https://github.com/lensapp/lens/assets/41041792/5c5b663c-260b-472e-a08e-88417a2b0221)

**Environment (please complete the following information):**
- Lens Version: v2023.5.310801-latest (5/31/2023)
- OS: Windows 10
- Installation method: 64 bit exe for windows

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQUwvMWFTYkRCV2RXVDVuSGNsa0VzbmN3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpJd09ETXhNVGd3TXpFMldoZ1BNakExTWpBNE16RXhPREV6TVRaYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCjBVaUJ6MHE4Nmc4OGZHaVc2UEQ0Z085Y0IrbXlrb1c5ZC9FZC9OSitJbVMzSFNDdFlpbkxoczlVbzExU2ZIeWgKNDJKSVExUWZnaVBoeldOUS9JUFVMZ25wbER1OGxTc3dVaUhlaitiSk4xcXRiV0VuVVl4aU1wdGp0OUovTDQrTApyTitocGs1Z3lRMllQQ0txV1FBSithdk5mQTU0bmZ0aENEVklzK2dhdGlXdndCTWZkQUlMcERFL2FHSHNqOXJ2CmgwaDc4YUlDZFo0bGJxMTFhbm9UMi9pSExIaUZpM2F3dU1RVVprN01pdmZlazlTUDFna1RrRjJQQWRpWTJwN3kKaUhHNklrTDFlR0JjN0VQRDlSMDY4ZHNRdU1CZHRuY2lXWU54dDZ5aGxGUDFFaFl5czdieWp3UmNrUEhYY3Erago2eE1PM1VRTkpTcDFOc0hweSswZWtyM3AxZ2ZreVZmWkt0MUNtdkJnQUFWV3lkdWZsS3YvelpjYmxhMVE1bnBJCkJHVUFOQ2VYMW9Wcy9KOTdrUEFYSXhkaUlicTlBekRnZmN6dE4wNmZYcE9SckNUMEV3QUR2V1lYbkh2djNVRk4KSG9aa01KWkRvZ1N4bzJNK1VyZkc2WFBHWG1RM2pSMVhqaU1ubzRKVm9yY3pYT3NDaE5Qd0dvTTZTai9oeVlUQwpZRGpNQzRmM1lSejNQazdLcXBJODZSdzlodHlWZkNjOTljUU1uWnY0emE2Z2cvZVdHYXVQeUJRaHo0dlU1TXRZCm83NCtzMlJTNU42d0tuY1BRQVFtdzhDRW1wRkRGaE1wT2dTUnlyakRqcFlVWXYxejZpWWwvbUFuN3I1L3ZYeUcKNDN2K2l4QlNqdFZYVW1sS1ZIamFMdXdvVDNXL0hCVnVLbTE2N2l1YWhzMENBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTG4xTkxMMXJJeU91YUI0CkF5ZCtieldGaFZvMk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ3g0c0pJQXltbXUwZ0Zpb2M3NmJ1YWtwZngKcmovNDNtMGd5VVFZZWdrOUxiK2hiTUFYYVJ3bmQ3QWhkS2NORUVtc1lqZUduNkVmZXIwalFwRDdrNER1QW13cQpZMW55VTNIanp0T0NMTDBqMUVQNmdYb0k4KzhJRVBUN0lZTFZramxMQjF6SHlzOE1aMG1ma2grd2oraVpiZHJSCm1VeWZta1BTMkdUd1NSaUR5MXEybVQvUGhlaFRLQm1YbTBkWWhnbFhkV3ZaSEREQkdTbTZSRVk4V1BYWUFsZDIKRlNDUVJ5RXF6Y2xVbjlxcTNoY3VQSTZUSGNtN0NxUWFuRS8zWDZCVTROdG1YdUdMcSs5RXU4YUx6Zk9NVjV5cApnTk9YTG1ydlQrZnlyTmV1a3l5MnJ3dmlHMzBlU0l5VXVMUVN3UXBJWHB3YWlzZUMzYUsyTFlyeG5FZkhrcG1SCjFXVGtGT1Q4TGFkYzdPS3BqNnluc1FuWTNvZ29QZmtCUlNxZzBxc0NwYkY5c0k2VStpUS9namM3N0hxSENpTTAKZWVZZFozUkdTZ1lhM2FjcEdUU3BtbFB3MVI2UWU0cmhrMkc4d0NmYW5IcjQ3Wmt6YzR6YTJnUjRCVEhZQkpEQwpVeENuR25oWGxSenZrd1A1dURXVkdvQU9MeFJXTkJQRjhYUEpMdWxPa3dlWnpKVlRYb0dRVGRyQ2FZenBjbEJ6CkIzQ2lMYTAwWTd5bVhxazV3RFVNNzc4VWRHYnltY2FIY2lCSVRHdy85cUUwdGNKUU1jb2FxalN4NlF3QWhZNTQKNTdYK1pQRitDM1lZOWN0UW1wdlYrUVJtSkVqQzAxL1pSU1EyVXFaR2Mxd2lpSHlnRXlFQUV6MGVzZkF1NFQxYgp6bGhZM0FUbkJuNEZWQ2RVZFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://ba-ondemand-app-we-b-aks-71c9c699.hcp.westeurope.azmk8s.io:443
  name: ba-ondemand-app-we-b-aks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQU5mWkNmNEUxa3Y4NCszQkZESGxtRk13RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpNd01qSTNNVEV5TkRNeldoZ1BNakExTXpBeU1qY3hNVE0wTXpOYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCm40WUZFRkhXejQrSEE1LzI0NGo5bGRGMlo5MUM3UlpvR1IyTUEwaTNBZE15cnRVTlNlQkJvUUdTOUNWU3p0QUEKeTZDTjk5SE9BZjBsaU81UVZvVWhDQmxJYzJtQk9sdzNXSURPWmhzb3Y0TnBCYk1DWkpKbFA2T1V3UUFLc0lLWAo5cTlpcjJVZGZzMkcrMzRsT2lwN2p1bEYyVjNUeUZHUVJFanRQbnBUSGpoVTQ1eDBUNWIxUHhkaUlJWHplTFBnCnU2WW1TRUN0czk3NW1MTi9ldVBRTXBWYyt3RTRGZ29ISEQ0SWpqczRhQ0RraHBpOWR6TmhCejZwclBGK3lZUUEKYjhXRmFVVzNPM3V4SEJYVytUeDZWVUNUMTJNNDdvVTRSM1lBQ0hVV3ZyN295VGJRQlNlWEFFT2ZBclJ5UU5KNwpnNllvMDhVZlNVTlBqd0ZGVkRPdnFmWEtrVm9sWXpXMlNFZzkyRCsrK1Z0MUFPL05DSEpjR1pPYmNHR0lGTkh4ClBVT2gydTJlQXFaN2tZN2hlN2RZMlBRcjBtRlg2d1hXYW9oNW1LWTZJbW92aVZScUdDZC84RUVabnoxeE9FVnUKUDZWYmhGeUZGL0Zza3ZKZkxVdW5TaHBoa1NKb21wYUhWKzVTUkozVDVqcTJzbTRUaFErUlhJU2U3MzhFbC9QZApSZmRuUE9lMTJDZzIrWE42T0cvbkJzRzExemFSMFpzR0ZzM2s3ZXFiZmY3bFRoN3RwZFVjSVo0REhQMFY0bmptClMxZUhJcjNYcGZ5Zi8vanJrRlcrbnVZOVo0TUxscG83SFdBS2Z5ZS9pNTRxWGJFR08xTTM0M2Vxazd3d0pKRjkKdDdTdTR2Um56cFhYQWIyQUxZRDRKVXUvRVNXOEhQMlYrbDZITnNnK1dPY0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTzdOYURuK2UvZnkyMEM5CmNzY0R0NkEvTFhxbk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQmJ5UTlwa3hCNmM5QVpMejdZVUlLN3BDZ2UKRUUwd3BDcG9sTHk1alk3WndiRGoxekV5V1VScGVpMy9QaFZwY28vQ1VDRk9LWTlMbkpnbHFabjQ5ZFhMb3ZJWApsWXhXNndTRno1UStTdFdWT0NVUHBQUGZScnZ6U1BaZWU0d1pwNFFVdmp2RmtWY1EydHplRUt6WnJvTXd5dURMCldvYU1KOHdZL2NsalpEZlYvYitLa3dXSTQzTUk5VjdxR25yYVZmeHVrc0xiRXkxcU1ob1dnN2xDMWFRN2tGOEcKZWxuOEI0Sjl0ZXZPMW9XM1N6UzMzYzE1YmlCVlBNa3cxY3FVa3FhQytteUw3eFVIMXhNN1hYQTI4RVpSRmVjMwpnQ0xPalYxU2pyblQzS1hnVzFuSXp4Ylp3Z3lXTk14NkdxbEtQd0NMN2JxL2JGa0FuK1o3UnUwaEhCTEd0MHBKClJPYUJ2N2ZJSDB6K2lQd0xXZDkrYnR1eDFmT0cwdjZKcDlUVTFxQ2xXRVlJNEx3dHJ4NHA2VzJGVms5RElTWmcKY1JlaGxKMzVEcFNSZlRHTjBpSk9raVZ0TWlhd0VoKzJoam9rMkl6eE9YRHF2NmRiL2R0bjUyZEVxYmRNZ3h6Uwo1MTFnTEtVK215aC9VS0xMWkh0VkcxMDhBL2xVMWZmWVZjeHYzMUp2KzFuano4Z05PMTFnYU5aSFBSZUJkVkw1ClEvUUZkRkpOUnNkQ0FIYXp2andGL2tJTXMvU0dIcFVGeFUvalF0WHJibGdVNTc4ZUdEL0dlNDgzcG1zSnFZMmIKUUNlOTF6SUFrSDh3R1RjQStwSStXL0Vkelk5WnRHc05LU3haV2pnb1Mza0hVQ2JhN015dlZUdEZ1YkdienFHYQpUeG80WFg1dzh1WlQ4NitUcHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://ba-prdsec-app-ne-g-aks-7145a110.hcp.northeurope.azmk8s.io:443
  name: ba-prdsec-app-ne-g-aks
contexts:
- context:
    cluster: ba-ondemand-app-we-b-aks
    user: clusterUser_ba-ondemand-app-we-rg_ba-ondemand-app-we-b-aks
  name: ba-ondemand-app-we-b-aks
- context:
    cluster: ba-prdsec-app-ne-g-aks
    user: clusterUser_ba-prdsec-app-ne-rg_ba-prdsec-app-ne-g-aks
  name: ba-prdsec-app-ne-g-aks
current-context: ba-ondemand-app-we-b-aks
kind: Config
preferences: {}
users:
- name: clusterUser_ba-ondemand-app-we-rg_ba-ondemand-app-we-b-aks
  user:
    auth-provider:
      config:
        access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiI2ZGFlNDJmOC00MzY4LTQ2NzgtOTRmZi0zOTYwZTI4ZTM2MzAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kODM1M2QyYS1iMTUzLTRkMTctODgyNy05MDJjNTFmNzIzNTcvIiwiaWF0IjoxNjg3MTc1OTUwLCJuYmYiOjE2ODcxNzU5NTAsImV4cCI6MTY4NzE3OTg3MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQXRYNGtHRXcyaS9sRC94bzl5aFdNZytqdVRGU1BCQnNqTGVyYVFZSFRmUVhXYUtkTERxSHMyQnMxaldwRmZmdzFWTlpJbitzUEVycXA2b2doWnB1eDE3dEphV2d4ME1QU0lJdmNzYStjWTlzPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiI4MGZhZjkyMC0xOTA4LTRiNTItYjVlZi1hOGU3YmVkZmM2N2EiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IlJhdHRpIiwiZ2l2ZW5fbmFtZSI6Ikd1cmRlZXAiLCJncm91cHMiOlsiZDM4MzVkMDYtNmZjNi00NGQwLTg1NWYtNGJmMTQ2NmJjM2NkIiwiYmQ3YTE2MTQtZGE5NC00NDI5LTk1MzEtODQyODM5NzE4MDhiIiwiYTNmOTdhMWYtYjYxYS00MmJmLTk0N2YtNGNjOGI5YTRjODQ3IiwiZTdlYzA4MjItMTYwZS00OTdkLWFlYWItM2Y2MTZlMzFkYjlkIiwiYTAyOTgzMmYtZTg2Zi00ZTZlLWFiYmYtNmFmY2ZlYzVjNzc4IiwiOGZlMzFhMzAtYzc3ZC00YmIzLWI1OWUtYzI4ZTg3ZTM1ZmM4IiwiMmVjZGY1MzQtODhiNC00ZjM2LWIyMTItYzI2OTMyYmZlNDNiIiwiNWYyY2UwM2MtZjU3Yy00NDgxLWEyM2YtZWRhODUyMjAwM2EwIiwiOWNhZWQ1NDItYjA4Mi00MmIzLTgzYzgtZGZmYTU4MmVhNWNiIiwiODRiOTBhNGItYmQ3NS00NWVmLThkNjEtNjZmYzE2ZDczMWIxIiwiMmJjMGM4NGQtYjBkOS00MTE4LTkwOTUtMDRmYzlkOGIwYmM4IiwiMDlhYjBhNTItM2UzYi00ZjQzLTlmMGEtNzg1MGE3ODMzYWNmIiwiYTVmZTZkNTYtZDdkYi00ZTAxLWJkZmEtZGE4MjMxZTkyYjJjIiwiZGZlMjZlNWItMWU3OS00YjA1LWEyM2MtN2MyZmY4MzgzOTFhIiwiMTMyYzU1NWMtZGExYy00OGViLWE5N2MtZGI3MWEzYTM5MTVkIiwiZjg5N2E0NWYtYzRiMi00MGY5LTg2MDEtMDkyZjZkNjVjMzE0IiwiNWZlNDRlNzMtZThiMy00MGJiLTlkMDQtYmRlMzhiOGRhNjBiIiwiOWU2NDZkNzMtZjRiZS00MjQ3LWE2MmUtMzliZTQ3ZjBhNDM4IiwiYzlhNDk3NzQtNTdmNS00YTg1LTg0Y2YtNTU2YWU0NWJkMjA2IiwiZWZiZTk4NzUtZWY1MC00YTJhLWFiMDAtYTFiMGQyMmE1ZGZiIiwiMDgzMzJmNzYtZTFkYS00MWQyLWI5M2UtZWU5M2Q3ODA3MWY3IiwiMmNkMjI3N2MtNzU0OC00ODVlLThmNGItZjU2MzQ5Y2M1NGRhIiwiM2VjNDFjN2QtNWIyMS00MjMxLTk2NWMtOGNkZWU4NjhlYjAzIiwiNGI5NDUwOTMtY2I1Ni00ZmUyLWEwZjktODNmZDczNzJhNDBiIiwiMTc3NjEwOWYtZjRlMi00MmY3LTg0ZjUtODcwODY3ZjdiZTMzIiwiMTE1YTYxYTQtMjk5Yi00MTgzLWE4MGQtYTUyMmIyNmI3ODFkIiwiNjk3NGY4YTgtZGVlZS00MGZkLThjNmItN2U0NDE3MTM2MmUwIiwiMWE5NDZiYWEtYzA0Ni00NmQyLTllMGYtY2QyMGEyYjhhNmRkIiwiNGFmMWZiYzItZWZjNy00YzM4LWFkZDUtZDMzNzg1OGNiMTk1IiwiOTk5NGIxYzctODM3MS00ZTE5LTlkZjctYTAwMTM0MGIzMGY4IiwiNWRjNDhjY2EtNGExOS00OTA5LTllMDUtN2U1NDQyZWRhOGRiIiwiN2Y4YzQyY2ItZWVmYy00OGIzLTgyOWQtODFkMTA1MTFhODMwIiwiNzE2OTZkY2MtNzMwZS00M2FjLTgyMWEtMTFjZjFlOGQ1ZTU2IiwiNjVhNGYzZDMtODk2Ny00MmEzLTk1MzgtNWUwZDVmMTgxZjAxIiwiZjI3ZGIyZDQtZDQ3NS00NjZmLTgwZmUtYjEwMjdlMGIzNzFmIiwiZmE0ZTMzZDUtZWQ0Zi00YWZjLWExZjctODRiYjJjZmViNjYxIiwiOGNhMmU5ZDUtYjBjNS00YzU3LThjZGItYTA4ZTI4YTM2YTMzIiwiYjBkNmJlZDgtOGQwMC00NWVhLWE2MGYtOGY1YzkyNjU4Yjc3IiwiMzFiYzdmZGUtMzQ0OC00NTViLWEzMjYtMDBmYmQ1OTk5YTFiIiwiN2ZkNDcwZTItYTRiNi00ZGI1LWE2ZWMtZmU5MzhjNWM3NDY3IiwiMjk0MmQ5ZTItZWQwOC00YmQxLWIzMWUtYThiMzE1MzMyYmQ3IiwiNjBjNDMyZTctNDdkZS00MjIyLTg4OGItY2UxY2JjODMyOTdlIiwiMDJiODAwZjAtNjcwMC00ZjhjLWJiZjQtYTIyZGY5Nzg0MzEzIiwiMWZhZDM1ZjgtY2ZiZS00N2UyLWI1ZjktODk5Mjg4ODYxN2QyIiwiOTY3ODRmYjItM2ZjZi00ODE5LWJjZDQtMWYxMTY5NzFjYzg1IiwiOGUwMjU1ZmEtN2MzNi00NGM5LTg4ZmItNTVjM2E3NmE0ZDk3IiwiZjMwZDk2NzMtNmM1MC00MTA5LWFlNzItZmJkNTYzMjQzNTUyIiwiNmZjNTYzYTQtYzRjNy00YWM3LWJkMTYtODlmZDc5NmZhNTUyIiwiM2YwMGUyMGEtM2JkMC00MDYyLTliZjQtNDFmZmRlMTczMTRjIiwiOTNlZWNkNjMtODU3Yi00YzViLTg2ZjQtZjY3MGZhZTZiZTEwIiwiNWZiMzg1MjItMDYzOC00MTQ0LTkyNGMtNjRkNjNjMGU5NDllIiwiN2I5YWI2NzctMDBhYy00YjQxLWFlNmQtMTk1NjZkY2Q5YWI3IiwiMjQwZDJmZTktNTEyMC00ZDhiLThiOTAtMWRlODNkMTRiYTM3IiwiZDBjYTdlYzUtMGRhYy00NGZiLTlkYjQtNjBmNDk4ZTUxNGIzIiwiNWQ4NTY3NDQtZTc0OS00ZmIyLThmMTEtMDA4NjNhMThkZDE4IiwiOGUzNDY4NTktZjgyOS00N2VkLWJiZTItZWU1N2QwMTg3MTM0IiwiYzY4YjVhMGYtZjgwNS00NjAwLWE5MmQtZDQ2OGY1YTUzNmE3IiwiYjhiNWRkMGEtZDliYS00ZGMwLTgzNTUtMWRjYWM2OTJkOTE1IiwiMTg0MWI3MzAtODE1MC00NjU4LTkwZWUtNGU3Y2YxZWVlNGNlIiwiN2Q1OWE1YTEtMTdkYy00YTgxLWE3NTgtM2ExYTgyYjQ3Y2MxIiwiYWM4ZDhjZjYtMTJiNC00ZWQzLTg2YTgtZTFkM2UwZWY1MzA0IiwiOWMwN2NmYWEtOTY2NC00ZDFkLTk2OTMtNjY2OGI4YmFkODNmIiwiZTE0ZTVkMzUtNjUwNy00YjZjLTgwM2YtOTU1MjE4NTEyNTYwIiwiMjQ4MTQ0ZjktOTgxMC00NDJkLTg4MjMtYmI5MGVkNjMzNDY4IiwiOTdhYjQ2NWYtMmUzMy00YjI3LThmNTktMzNkN2FmZTYxNjRkIiwiNzQ0ZDc2YmEtMGU0MC00NGYwLTk2MGQtMTc3MGZhZTE5MjUwIiwiMjA5ODg5NzktYTI4YS00MDBmLWEwZTAtNThjNWU1ZWQwZjI5Il0sImlwYWRkciI6IjI0MDU6MjAxOmFjMDU6OTkyOTo4MTZlOjU1NTg6NTVmYTpiYTciLCJuYW1lIjoiR3VyZGVlcCBSYXR0aSIsIm9pZCI6ImMyODUwZWU0LTVmMTUtNDI2Zi05ZTM4LWNjZDE2ZjA2ODBmNiIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0zMDg1NDMxNjgzLTEyNDc1Mzg3NDItMTg2NDc0MDcwOC0xNDA5NSIsInB1aWQiOiIxMDAzN0ZGRUFDM0E1RkIzIiwicmgiOiIwLkFRc0FLajAxMkZPeEYwMklKNUFzVWZjalZfaENybTFvUTNoR2xQODVZT0tPTmpBTEFCMC4iLCJzY3AiOiJ1c2VyLnJlYWQiLCJzdWIiOiJDVzc5TjJsUnVLN2NYOUdydXRiNDQtUFRzRjltWWVrSzQwMkx4QkRid3FjIiwidGlkIjoiZDgzNTNkMmEtYjE1My00ZDE3LTg4MjctOTAyYzUxZjcyMzU3IiwidW5pcXVlX25hbWUiOiJndXJkZWVwLnJhdHRpQHVpcGF0aC5jb20iLCJ1cG4iOiJndXJkZWVwLnJhdHRpQHVpcGF0aC5jb20iLCJ1dGkiOiJ4c3k5VXlyX0VFVzUzcDdxOXlvZ0FBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXX0.SiLg9UmpqFRqehjzGQdmPBmBfjOlEQ5rM5tMz5S2yK2XJcpvrB4OAmzCUvSemUENc3WwQ5A6sMppp8O3AHMtu6WTQYhgxKji4ydJfk8P3Tie6gnyaKfVCb8uIy77g4M2Cdbi8Coq0bUB4xHF-qcGNSi-i-xYP_B-IL8T_vJ98_auphF2i7cfTwRhXuIay8WehiNKMUwdNK8ysBZbb9TzGGcUpMJuxOD97qb8xbL7NvmMmjWruw04KO3S0CAMwXaneJyR1RdnXUy4W2z8g56p-6oWaeNHkPCpp8-_2r3ij1grQuylkkNQktWZBqAzUBwmFjFy7aS57Gp0AhVCDCXERA
        apiserver-id: 6dae42f8-4368-4678-94ff-3960e28e3630
        client-id: 80faf920-1908-4b52-b5ef-a8e7bedfc67a
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "3619"
        expires-on: "1687179870"
        refresh-token: 0.AQsAKj012FOxF02IJ5AsUfcjVyD5-oAIGVJLte-o577fxnoLAB0.AgABAAEAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P9e5m0gHnssc21sHkcjTfwzubEyAwhQmPGS3JwrCcWZavVnP7DbCBk31zL0jOLeBGKirAMDsaqc9-i-UfLiIFCSiG98W6fRnsvTzZQ_4yqsOQXkE2k-Te97iIiMwdK3N2F_aY2IID4G2VEaGL3ITV4vObSTvTODDJN9hZ9vYKHfikxMaiKkgtpHEQCEbkePxGwQiojUNUD9sFVHmbWt5IphkHAL6hZDwRKaQUVw9nqMQAeMuWQCQsEnJPEFhZOeZBEMmD1263kKBOZ6kHgoz0ljE7p0DMSlqzbX7TloL0BwX-CO4KknKxOz-NfRYbi-B-C2fBP44hjwdaGFe9kcD1OabfHY4KJytBSaG9duJr3b8QmMranX65DNDjVLoducq8mQIUVOqTNEgGZaeKSbrfeLkXinVw1JvIs3Iu3cV7yMu9Ex6d4o-okTR4EVOTtvC0xQpX8zrk9jyvQxfa4H2lm4X6b-yngG1YJSKbB5s5ArxktwViKlLcWiH59pB_gIebYxUz9Hr3tmos9q6Tstv7eGKCOQ6TYNstEHgjCb55IKl6o6ixq4no1TaSPhVHajH4TC88SBX_GfzNas3CYOxJiY-H2V2UxcLO1tcOv6omB3GCFoVU6gw81BSXiFS8nVwelZ1It6USsHA_b1O5_yZniAAm882Wx5GdqfEq08FycFEpAT8mrTW3WISovHMR_Mh6u1zq3vjHQkbOoLtdkeE84rgN60zi2M30htFuuDSx07KgCIA7-gZJZodN_lk5MPxWQAhE8myMWBmbkUhKaHdiCJVOEL-l8Xjqy7DBib6Fj1yZdc8yqsup-lRy0Kdw8jhdS5TN3pAgR7twPZXQCSBA-URxfsOOzZVjPN
        tenant-id: d8353d2a-b153-4d17-8827-902c51f72357
      name: azure
- name: clusterUser_ba-prdsec-app-ne-rg_ba-prdsec-app-ne-g-aks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - --client-id
      - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
      - --tenant-id
      - d8353d2a-b153-4d17-8827-902c51f72357
      - --login
      - devicecode
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false

```

**Additional context**
