### ISSUE TITLE
Can't update local helm release

### ISSUE THREAD

**Issue by MrXLR8** [kontena/lens#8219]
**Describe the bug**
Not possible to manage releases, if chart was deployed locally from cli

**To Reproduce**
1. Install your own chart
2. Go to releases, select your release
3. Try to make any changes in values that you will have in sidebar
4. Click Save
5. Progress never finished

Bonus: if you click upgrade, you can see how editor struggles to load chart version

**Expected behavior**
Changes applied, new revision deployed

**Screenshots**

![Image](https://github.com/user-attachments/assets/803dbc95-2d51-4db9-913f-5211fd2877bf)

![Image](https://github.com/user-attachments/assets/1592ee5a-083e-49d3-a62f-ceb3d6f775e7)

**Environment (please complete the following information):**
- Lens Version:
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): .exe installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Logs containing no events regarding this
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: 
    client-key-data: 
```

**Additional context**
